// Generated by Kukicha v0.0.14 (requires Go 1.26+)

package container_test

import (
	"github.com/duber000/kukicha/stdlib/container"
	"testing"
)

//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/container/container_test.kuki:9
func TestBasicTypes(t *testing.T) {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/container/container_test.kuki:11
	config := container.Config{}
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/container/container_test.kuki:12
	containerInfo := container.ContainerInfo{}
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/container/container_test.kuki:13
	imageInfo := container.ImageInfo{}
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/container/container_test.kuki:14
	buildOutput := container.BuildOutput{}
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/container/container_test.kuki:15
	auth := container.Auth{}
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/container/container_test.kuki:16
	event := container.ContainerEvent{}
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/container/container_test.kuki:20
	_ = config
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/container/container_test.kuki:21
	_ = containerInfo
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/container/container_test.kuki:22
	_ = imageInfo
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/container/container_test.kuki:23
	_ = buildOutput
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/container/container_test.kuki:24
	_ = auth
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/container/container_test.kuki:25
	_ = event
}

//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/container/container_test.kuki:28
func TestConfigBuilder(t *testing.T) {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/container/container_test.kuki:30
	cfg := container.New()
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/container/container_test.kuki:31
	cfg = container.Host(cfg, "unix:///var/run/docker.sock")
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/container/container_test.kuki:32
	cfg = container.APIVersion(cfg, "1.41")
}

//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/container/container_test.kuki:37
func TestAuthFunctions(t *testing.T) {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/container/container_test.kuki:39
	auth := container.Login("username", "password", "registry.example.com")
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/container/container_test.kuki:42
	encoded := container.AuthEncode(auth)
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/container/container_test.kuki:43
	if encoded == "" {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/container/container_test.kuki:44
		t.Error("Expected encoded to be non-empty")
	}
}

//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/container/container_test.kuki:51
func TestContainerTypes(t *testing.T) {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/container/container_test.kuki:54
	auth := container.Auth{}
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/container/container_test.kuki:56
	_ = auth
}
