// Generated by Kukicha (requires Go 1.26+)

package container

import (
	"archive/tar"
	"bufio"
	"bytes"
	"encoding/base64"
	"errors"
	"fmt"
	dockertypes "github.com/docker/docker/api/types"
	dockercontainer "github.com/docker/docker/api/types/container"
	dockerevents "github.com/docker/docker/api/types/events"
	dockerimage "github.com/docker/docker/api/types/image"
	"github.com/docker/docker/client"
	"github.com/docker/docker/pkg/stdcopy"
	ctxpkg "github.com/kukichalang/kukicha/stdlib/ctx"
	"github.com/kukichalang/kukicha/stdlib/json"
	kukistring "github.com/kukichalang/kukicha/stdlib/string"
	"io"
	"os"
	"path/filepath"
	"time"
)

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:42
type Engine struct {
	cli *client.Client
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:46
type Config struct {
	host       string
	apiVersion string
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:51
type ContainerInfo struct {
	id     string
	image  string
	status string
	state  string
	names  []string
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:59
type ImageInfo struct {
	id   string
	tags []string
	size int64
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:65
type BuildOutput struct {
	imageID string
	output  string
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:70
type Auth struct {
	username      string
	password      string
	serverAddress string
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:76
type pullStatusMsg struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:81
type buildStreamMsg struct {
	Stream string         `json:"stream"`
	Aux    buildStreamAux `json:"aux"`
	Error  string         `json:"error"`
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:87
type buildStreamAux struct {
	ID string `json:"ID"`
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:91
type dockerAuthEntry struct {
	Auth string `json:"auth"`
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:95
type dockerConfig struct {
	Auths map[string]dockerAuthEntry `json:"auths"`
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:99
type ContainerEvent struct {
	id       string
	resource string
	action   string
	actor    string
	time     string
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:107
func New() Config {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:108
	return Config{}
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:111
func Host(cfg Config, host string) Config {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:112
	cfg.host = host
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:113
	return cfg
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:116
func APIVersion(cfg Config, version string) Config {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:117
	cfg.apiVersion = version
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:118
	return cfg
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:121
func Close(engine Engine) error {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:122
	return engine.cli.Close()
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:125
func ListContainers(engine Engine) ([]ContainerInfo, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:126
	bg := ctxpkg.Background()
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:127
	containers, err_1 := engine.cli.ContainerList(ctxpkg.Value(bg), dockercontainer.ListOptions{All: true})
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:127
	if err_1 != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:127
		err_1 = fmt.Errorf("container list: %w", err_1)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:127
		return []ContainerInfo{}, err_1
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:129
	result := make([]ContainerInfo, len(containers))
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:130
	for i, c := range containers {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:131
		result[i] = ContainerInfo{id: c.ID, image: c.Image, status: c.Status, state: c.State, names: c.Names}
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:138
	return result, nil
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:141
func ListImages(engine Engine) ([]ImageInfo, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:142
	bg := ctxpkg.Background()
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:143
	images, err_2 := engine.cli.ImageList(ctxpkg.Value(bg), dockerimage.ListOptions{All: true})
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:143
	if err_2 != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:143
		err_2 = fmt.Errorf("container list images: %w", err_2)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:143
		return []ImageInfo{}, err_2
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:145
	result := make([]ImageInfo, len(images))
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:146
	for i, img := range images {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:147
		result[i] = ImageInfo{id: img.ID, tags: img.RepoTags, size: img.Size}
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:152
	return result, nil
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:155
func Stop(engine Engine, containerID string) error {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:156
	bg := ctxpkg.Background()
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:157
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:157
	err_3 := engine.cli.ContainerStop(ctxpkg.Value(bg), containerID, dockercontainer.StopOptions{})
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:157
	if err_3 != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:157
		err_3 = fmt.Errorf("container stop: %w", err_3)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:157
		return err_3
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:158
	return nil
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:161
func Remove(engine Engine, containerID string) error {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:162
	bg := ctxpkg.Background()
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:163
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:163
	err_4 := engine.cli.ContainerRemove(ctxpkg.Value(bg), containerID, dockercontainer.RemoveOptions{})
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:163
	if err_4 != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:163
		err_4 = fmt.Errorf("container remove: %w", err_4)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:163
		return err_4
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:164
	return nil
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:167
func Login(username string, password string, server string) Auth {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:168
	return Auth{username: username, password: password, serverAddress: server}
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:171
func AuthEncode(auth Auth) string {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:172
	authJSON, _ := json.Marshal(map[string]string{"username": auth.username, "password": auth.password, "serveraddress": auth.serverAddress})
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:177
	return base64.URLEncoding.EncodeToString(authJSON)
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:180
func ContainerID(c ContainerInfo) string {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:181
	return c.id
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:184
func ContainerImage(c ContainerInfo) string {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:185
	return c.image
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:188
func ContainerStatus(c ContainerInfo) string {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:189
	return c.status
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:192
func ContainerState(c ContainerInfo) string {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:193
	return c.state
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:196
func ContainerNames(c ContainerInfo) []string {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:197
	return c.names
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:200
func ImageID(img ImageInfo) string {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:201
	return img.id
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:204
func ImageTags(img ImageInfo) []string {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:205
	return img.tags
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:208
func ImageSize(img ImageInfo) int64 {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:209
	return img.size
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:212
func BuildImageID(b BuildOutput) string {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:213
	return b.imageID
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:216
func BuildLog(b BuildOutput) string {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:217
	return b.output
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:220
func EventID(event ContainerEvent) string {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:221
	return event.id
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:224
func EventResource(event ContainerEvent) string {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:225
	return event.resource
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:228
func EventAction(event ContainerEvent) string {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:229
	return event.action
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:232
func EventActor(event ContainerEvent) string {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:233
	return event.actor
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:236
func EventTime(event ContainerEvent) string {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:237
	return event.time
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:243
func containerLogs(cli *client.Client, containerID string, tail string) (string, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:244
	bg := ctxpkg.Background()
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:245
	opts := dockercontainer.LogsOptions{ShowStdout: true, ShowStderr: true}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:246
	if tail != "" {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:247
		opts.Tail = tail
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:248
	reader, err_5 := cli.ContainerLogs(ctxpkg.Value(bg), containerID, opts)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:248
	if err_5 != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:248
		err_5 = fmt.Errorf("container logs: %w", err_5)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:248
		return "", err_5
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:249
	defer reader.Close()
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:251
	stdout := bytes.Buffer{}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:252
	stderr := bytes.Buffer{}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:253
	_, err_6 := stdcopy.StdCopy(&stdout, &stderr, reader)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:253
	if err_6 != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:253
		//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:254
		raw, err_7 := io.ReadAll(reader)
		//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:254
		if err_7 != nil {
			//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:254
			err_7 = fmt.Errorf("container logs: %w", err_7)
			//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:254
			return "", err_7
		}
		//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:255
		return string(raw), nil
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:257
	combined := stdout.String()
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:258
	if stderr.Len() > 0 {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:259
		combined = (combined + stderr.String())
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:260
	return combined, nil
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:263
func Logs(engine Engine, containerID string) (string, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:264
	return containerLogs(engine.cli, containerID, "")
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:267
func LogsTail(engine Engine, containerID string, lines int64) (string, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:268
	return containerLogs(engine.cli, containerID, fmt.Sprintf("%d", lines))
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:271
func Run(engine Engine, img string, cmd []string) (string, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:272
	bg := ctxpkg.Background()
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:273
	resp, err_8 := engine.cli.ContainerCreate(ctxpkg.Value(bg), &dockercontainer.Config{Image: img, Cmd: cmd}, nil, nil, nil, "")
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:276
	if err_8 != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:276
		err_8 = fmt.Errorf("container run create: %w", err_8)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:276
		return "", err_8
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:278
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:278
	err_9 := engine.cli.ContainerStart(ctxpkg.Value(bg), resp.ID, dockercontainer.StartOptions{})
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:278
	if err_9 != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:278
		err_9 = fmt.Errorf("container run start: %w", err_9)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:278
		return "", err_9
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:280
	return resp.ID, nil
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:283
func Inspect(engine Engine, containerID string) (ContainerInfo, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:284
	bg := ctxpkg.Background()
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:285
	info, err_10 := engine.cli.ContainerInspect(ctxpkg.Value(bg), containerID)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:285
	if err_10 != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:285
		err_10 = fmt.Errorf("container inspect: %w", err_10)
		var _zero0 ContainerInfo
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:285
		return _zero0, err_10
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:287
	names := make([]string, 0)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:288
	if info.Name != "" {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:289
		names = append(names, kukistring.TrimPrefix(info.Name, "/"))
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:290
	status := ""
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:291
	state := ""
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:292
	if info.State != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:293
		status = info.State.Status
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:294
		state = info.State.Status
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:295
	return ContainerInfo{id: info.ID, image: info.Config.Image, status: status, state: state, names: names}, nil
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:305
func Exec(engine Engine, containerID string, cmd []string, handles ...ctxpkg.Handle) (string, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:306
	ctx := ctxpkg.Background()
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:307
	if len(handles) > 0 {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:308
		ctx = handles[0]
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:309
	createResp, err_11 := engine.cli.ContainerExecCreate(ctxpkg.Value(ctx), containerID, dockertypes.ExecConfig{Cmd: cmd, AttachStdout: true, AttachStderr: true})
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:313
	if err_11 != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:313
		err_11 = fmt.Errorf("container exec create: %w", err_11)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:313
		return "", err_11
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:315
	attachResp, err_12 := engine.cli.ContainerExecAttach(ctxpkg.Value(ctx), createResp.ID, dockertypes.ExecStartCheck{})
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:315
	if err_12 != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:315
		err_12 = fmt.Errorf("container exec attach: %w", err_12)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:315
		return "", err_12
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:316
	defer attachResp.Close()
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:318
	stdout := bytes.Buffer{}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:319
	stderr := bytes.Buffer{}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:320
	_, err_13 := stdcopy.StdCopy(&stdout, &stderr, attachResp.Reader)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:320
	if err_13 != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:320
		//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:321
		raw, err_14 := io.ReadAll(attachResp.Reader)
		//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:321
		if err_14 != nil {
			//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:321
			err_14 = fmt.Errorf("container exec read: %w", err_14)
			//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:321
			return "", err_14
		}
		//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:322
		return string(raw), nil
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:324
	inspectResult, err_15 := engine.cli.ContainerExecInspect(ctxpkg.Value(ctx), createResp.ID)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:324
	if err_15 != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:324
		err_15 = fmt.Errorf("container exec inspect: %w", err_15)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:324
		return "", err_15
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:326
	combined := stdout.String()
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:327
	if stderr.Len() > 0 {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:328
		combined = (combined + stderr.String())
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:329
	if inspectResult.ExitCode != 0 {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:330
		return combined, fmt.Errorf("container exec exit %v", inspectResult.ExitCode)
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:331
	return combined, nil
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:337
func Wait(engine Engine, containerID string, timeoutSeconds int64) (int64, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:338
	h := ctxpkg.Background()
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:339
	if timeoutSeconds > 0 {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:340
		h = ctxpkg.WithTimeout(h, timeoutSeconds)
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:341
	defer ctxpkg.Cancel(h)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:342
	return WaitCtx(engine, h, containerID)
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:345
func WaitCtx(engine Engine, h ctxpkg.Handle, containerID string) (int64, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:346
	goCtx := ctxpkg.Value(h)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:347
	waitCh, errCh := engine.cli.ContainerWait(goCtx, containerID, dockercontainer.WaitConditionNotRunning)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:348
	select {
	case err := <-errCh:
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:350
		if err == nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:351
			return -1, errors.New("container wait: unknown wait error")
		}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:352
		return -1, fmt.Errorf("container wait: %v", err)
	case res := <-waitCh:
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:354
		return res.StatusCode, nil
	}
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:359
func convertEvent(msg dockerevents.Message) ContainerEvent {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:360
	ts := time.Unix(msg.Time, 0).UTC().Format(time.RFC3339)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:361
	actor := msg.Actor.ID
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:362
	if //line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:362
	name, ok := msg.Actor.Attributes["name"]; ok && (name != "") {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:363
		actor = name
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:364
	return ContainerEvent{id: msg.ID, resource: string(msg.Type), action: string(msg.Action), actor: actor, time: ts}
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:373
func eventsWithContext(engine Engine, h ctxpkg.Handle) ([]ContainerEvent, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:374
	goCtx := ctxpkg.Value(h)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:375
	msgCh, errCh := engine.cli.Events(goCtx, dockertypes.EventsOptions{})
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:376
	events := make([]ContainerEvent, 0)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:377
	for {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:378
		select {
		case <-goCtx.Done():
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:380
			return events, nil
		case err := <-errCh:
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:382
			if (err == nil) || (goCtx.Err() != nil) {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:383
				return events, nil
			}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:384
			return events, fmt.Errorf("container events: %v", err)
		case msg, ok := <-msgCh:
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:386
			if !ok {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:387
				return events, nil
			}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:388
			events = append(events, convertEvent(msg))
		}
	}
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:392
func Events(engine Engine, timeoutSeconds int64) ([]ContainerEvent, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:393
	if timeoutSeconds <= 0 {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:394
		timeoutSeconds = 15
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:395
	h := ctxpkg.WithTimeout(ctxpkg.Background(), timeoutSeconds)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:396
	defer ctxpkg.Cancel(h)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:397
	return eventsWithContext(engine, h)
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:400
func EventsCtx(engine Engine, h ctxpkg.Handle) ([]ContainerEvent, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:401
	return eventsWithContext(engine, h)
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:407
func Pull(engine Engine, ref string, handles ...ctxpkg.Handle) (string, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:408
	bg := ctxpkg.Background()
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:409
	if len(handles) > 0 {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:410
		bg = handles[0]
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:411
	reader, err_16 := engine.cli.ImagePull(ctxpkg.Value(bg), ref, dockerimage.PullOptions{})
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:411
	if err_16 != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:411
		err_16 = fmt.Errorf("container pull: %w", err_16)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:411
		return "", err_16
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:412
	defer reader.Close()
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:413
	digest := ""
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:414
	scanner := bufio.NewScanner(reader)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:415
	for scanner.Scan() {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:416
		msg := pullStatusMsg{}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:417
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:417
		err_17 := json.Unmarshal(scanner.Bytes(), &msg)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:417
		if err_17 != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:417
			//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:418
			continue
		}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:419
		if kukistring.HasPrefix(msg.Status, "Digest:") {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:420
			digest = kukistring.TrimPrefix(msg.Status, "Digest: ")
		}
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:421
	if digest == "" {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:422
		digest = ref
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:423
	return digest, nil
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:426
func PullAuth(engine Engine, ref string, auth Auth) (string, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:427
	authJSON, err_18 := json.Marshal(map[string]string{"username": auth.username, "password": auth.password, "serveraddress": auth.serverAddress})
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:431
	if err_18 != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:431
		err_18 = fmt.Errorf("container pull auth: %w", err_18)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:431
		return "", err_18
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:433
	encoded := base64.URLEncoding.EncodeToString(authJSON)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:434
	reader, err_19 := engine.cli.ImagePull(ctxpkg.Value(ctxpkg.Background()), ref, dockerimage.PullOptions{RegistryAuth: encoded})
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:436
	if err_19 != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:436
		err_19 = fmt.Errorf("container pull: %w", err_19)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:436
		return "", err_19
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:437
	defer reader.Close()
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:439
	digest := ""
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:440
	scanner := bufio.NewScanner(reader)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:441
	for scanner.Scan() {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:442
		msg := pullStatusMsg{}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:443
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:443
		err_20 := json.Unmarshal(scanner.Bytes(), &msg)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:443
		if err_20 != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:443
			//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:444
			continue
		}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:445
		if kukistring.HasPrefix(msg.Status, "Digest:") {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:446
			digest = kukistring.TrimPrefix(msg.Status, "Digest: ")
		}
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:447
	if digest == "" {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:448
		digest = ref
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:449
	return digest, nil
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:454
func loadDockerAuth(serverAddress string) (string, string, string, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:455
	home, err_21 := os.UserHomeDir()
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:455
	if err_21 != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:455
		err_21 = fmt.Errorf("container auth: %w", err_21)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:455
		return "", "", "", err_21
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:456
	configPath := filepath.Join(home, ".docker", "config.json")
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:457
	data, err_22 := os.ReadFile(configPath)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:457
	if err_22 != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:457
		err_22 = fmt.Errorf("container auth: %w", err_22)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:457
		return "", "", "", err_22
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:458
	config := dockerConfig{}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:459
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:459
	err_23 := json.Unmarshal(data, &config)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:459
	if err_23 != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:459
		err_23 = fmt.Errorf("container auth parse: %w", err_23)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:459
		return "", "", "", err_23
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:460
	authEntry, ok := config.Auths[serverAddress]
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:461
	if !ok {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:462
		variations := []string{("https://" + serverAddress), ("http://" + serverAddress), kukistring.TrimPrefix(serverAddress, "https://"), kukistring.TrimPrefix(serverAddress, "http://")}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:468
		for _, v := range variations {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:469
			a, found := config.Auths[v]
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:470
			if found {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:471
				authEntry = a
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:472
				ok = true
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:473
				break
			}
		}
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:474
	if !ok {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:475
		return "", "", "", fmt.Errorf("container auth: no credentials found for %v", serverAddress)
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:476
	if authEntry.Auth == "" {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:477
		return "", "", "", fmt.Errorf("container auth: empty credentials for %v", serverAddress)
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:478
	decoded, err_24 := base64.StdEncoding.DecodeString(authEntry.Auth)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:478
	if err_24 != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:478
		err_24 = fmt.Errorf("container auth decode: %w", err_24)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:478
		return "", "", "", err_24
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:479
	parts := kukistring.SplitN(string(decoded), ":", 2)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:480
	if len(parts) != 2 {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:481
		return "", "", "", fmt.Errorf("container auth: invalid credential format for %v", serverAddress)
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:482
	return parts[0], parts[1], serverAddress, nil
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:485
func LoginFromConfig(server string) (Auth, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:486
	username, password, addr, err_25 := loadDockerAuth(server)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:486
	if err_25 != nil {
		var _zero0 Auth
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:486
		return _zero0, err_25
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:487
	return Auth{username: username, password: password, serverAddress: addr}, nil
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:494
func newClient(host string) (*client.Client, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:495
	opts := []client.Opt{client.FromEnv, client.WithAPIVersionNegotiation()}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:496
	if host != "" {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:497
		opts = append(opts, client.WithHost(host))
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:498
	cli, err_26 := client.NewClientWithOpts(opts...)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:498
	if err_26 != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:498
		err_26 = fmt.Errorf("container connect: %w", err_26)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:498
		return nil, err_26
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:499
	return cli, nil
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:502
func Connect() (Engine, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:503
	socketPaths := []string{fmt.Sprintf("/run/user/%d/podman/podman.sock", os.Getuid()), "/var/run/docker.sock", "/run/podman/podman.sock"}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:508
	host := ""
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:509
	for _, p := range socketPaths {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:510
		_, statErr := os.Stat(p)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:511
		if statErr == nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:512
			host = ("unix://" + p)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:513
			break
		}
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:514
	cli, err_27 := newClient(host)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:514
	if err_27 != nil {
		var _zero0 Engine
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:514
		return _zero0, err_27
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:515
	return Engine{cli: cli}, nil
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:518
func ConnectRemote(host string) (Engine, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:519
	cli, err_28 := newClient(host)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:519
	if err_28 != nil {
		var _zero0 Engine
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:519
		return _zero0, err_28
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:520
	return Engine{cli: cli}, nil
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:523
func Open(cfg Config) (Engine, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:524
	opts := []client.Opt{client.FromEnv, client.WithAPIVersionNegotiation()}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:525
	if cfg.host != "" {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:526
		opts = append(opts, client.WithHost(cfg.host))
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:527
	if cfg.apiVersion != "" {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:528
		opts = append(opts, client.WithVersion(cfg.apiVersion))
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:529
	cli, err_29 := client.NewClientWithOpts(opts...)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:529
	if err_29 != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:529
		err_29 = fmt.Errorf("container open: %w", err_29)
		var _zero0 Engine
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:529
		return _zero0, err_29
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:530
	return Engine{cli: cli}, nil
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:534
func buildImage(cli *client.Client, contextPath string, tag string) (string, string, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:535
	buf := bytes.Buffer{}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:536
	tw := tar.NewWriter(&buf)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:537
	absContextPath, err_30 := filepath.Abs(contextPath)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:537
	if err_30 != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:537
		err_30 = fmt.Errorf("container build: %w", err_30)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:537
		return "", "", err_30
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:538
	walkErr := filepath.WalkDir(absContextPath, func(walkPath string, d os.DirEntry, err error) error {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:539
		if err != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:540
			return err
		}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:541
		if d.IsDir() && (d.Name() == ".git") {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:542
			return filepath.SkipDir
		}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:544
		if d.Type() == os.ModeSymlink {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:545
			return nil
		}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:546
		relPath, relErr := filepath.Rel(absContextPath, walkPath)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:547
		if relErr != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:548
			return relErr
		}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:549
		if d.IsDir() {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:550
			return nil
		}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:551
		info, infoErr := d.Info()
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:552
		if infoErr != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:553
			return infoErr
		}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:554
		header, headerErr := tar.FileInfoHeader(info, "")
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:555
		if headerErr != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:556
			return headerErr
		}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:557
		header.Name = relPath
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:558
		writeErr := tw.WriteHeader(header)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:559
		if writeErr != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:560
			return writeErr
		}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:561
		f, openErr := os.Open(walkPath)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:562
		if openErr != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:563
			return openErr
		}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:564
		defer f.Close()
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:565
		_, copyErr := io.Copy(tw, f)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:566
		return copyErr
	})
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:568
	if walkErr != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:569
		return "", "", fmt.Errorf("container build context: %v", walkErr)
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:570
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:570
	err_31 := tw.Close()
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:570
	if err_31 != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:570
		err_31 = fmt.Errorf("container build tar: %w", err_31)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:570
		return "", "", err_31
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:571
	buildOpts := dockertypes.ImageBuildOptions{Tags: []string{tag}, Remove: true, Dockerfile: "Dockerfile"}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:576
	resp, err_32 := cli.ImageBuild(ctxpkg.Value(ctxpkg.Background()), &buf, buildOpts)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:576
	if err_32 != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:576
		err_32 = fmt.Errorf("container build: %w", err_32)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:576
		return "", "", err_32
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:577
	defer resp.Body.Close()
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:578
	output := bytes.Buffer{}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:579
	imageID := ""
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:580
	scanner := bufio.NewScanner(resp.Body)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:581
	for scanner.Scan() {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:582
		line := scanner.Text()
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:583
		output.WriteString(line)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:584
		output.WriteString("\n")
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:585
		msg := buildStreamMsg{}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:586
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:586
		err_33 := json.Unmarshal(scanner.Bytes(), &msg)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:586
		if err_33 != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:586
			continue
		}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:587
		if msg.Error != "" {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:588
			return "", output.String(), fmt.Errorf("container build: %v", msg.Error)
		}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:589
		if msg.Aux.ID != "" {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:590
			imageID = msg.Aux.ID
		}
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:591
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:591
	err_34 := scanner.Err()
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:591
	if err_34 != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:591
		err_34 = fmt.Errorf("container build stream: %w", err_34)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:591
		return "", "", err_34
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:592
	return imageID, output.String(), nil
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:595
func Build(engine Engine, path string, tag string) (BuildOutput, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:596
	imageID, output, err_35 := buildImage(engine.cli, path, tag)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:596
	if err_35 != nil {
		var _zero0 BuildOutput
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:596
		return _zero0, err_35
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:597
	return BuildOutput{imageID: imageID, output: output}, nil
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:600
func extractTar(reader io.Reader, destPath string) error {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:601
	tr := tar.NewReader(reader)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:602
	cleanDest := filepath.Clean(destPath)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:603
	for {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:604
		header, err := tr.Next()
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:605
		if err == io.EOF {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:606
			break
		}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:607
		if err != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:608
			return err
		}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:609
		cleanName := filepath.Clean(header.Name)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:610
		target := filepath.Join(destPath, cleanName)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:611
		if !kukistring.HasPrefix(target, (cleanDest+string(filepath.Separator))) && (filepath.Clean(target) != cleanDest) {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:612
			return fmt.Errorf("invalid archive path: %v", header.Name)
		}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:613
		switch header.Typeflag {
		case tar.TypeDir:
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:615
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:615
			err_36 := os.MkdirAll(target, os.FileMode(header.Mode))
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:615
			if err_36 != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:615
				return err_36
			}
		case tar.TypeReg:
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:617
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:617
			err_37 := os.MkdirAll(filepath.Dir(target), 493)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:617
			if err_37 != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:617
				return err_37
			}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:618
			f, err_38 := os.OpenFile(target, ((os.O_CREATE | os.O_WRONLY) | os.O_TRUNC), os.FileMode(header.Mode))
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:618
			if err_38 != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:618
				return err_38
			}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:619
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:619
			_, err_39 := io.Copy(f, tr)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:619
			if err_39 != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:619
				//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:620
				f.Close()
				//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:621
				return fmt.Errorf("%v", err_39)
			}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:622
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:622
			err_40 := f.Close()
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:622
			if err_40 != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:622
				return err_40
			}
		case tar.TypeSymlink, tar.TypeLink:
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:624
			return fmt.Errorf("archive contains unsupported link entry: %v", header.Name)
		default:
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:626
			return fmt.Errorf("archive contains unsupported entry type %v: %v", header.Typeflag, header.Name)
		}
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:627
	return nil
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:630
func createTarFromPath(sourcePath string) (io.Reader, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:631
	absSourcePath, err_41 := filepath.Abs(sourcePath)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:631
	if err_41 != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:631
		err_41 = fmt.Errorf("container copy to abs path: %w", err_41)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:631
		return nil, err_41
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:634
	info, err_42 := os.Lstat(absSourcePath)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:634
	if err_42 != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:634
		err_42 = fmt.Errorf("container copy to stat: %w", err_42)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:634
		return nil, err_42
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:636
	if info.Mode().Type() == os.ModeSymlink {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:637
		return nil, fmt.Errorf("container copy to: source path is a symlink: %v", absSourcePath)
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:638
	buf := bytes.Buffer{}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:639
	tw := tar.NewWriter(&buf)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:640
	if info.IsDir() {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:641
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:641
		err_43 := filepath.WalkDir(absSourcePath, func(walkPath string, d os.DirEntry, err error) error {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:642
			if err != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:643
				return err
			}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:645
			if d.Type() == os.ModeSymlink {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:646
				return nil
			}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:647
			fi, err_1 := d.Info()
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:647
			if err_1 != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:647
				return err_1
			}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:650
			if fi.Mode().Type() == os.ModeSymlink {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:651
				return nil
			}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:653
			rel, err_2 := filepath.Rel(filepath.Dir(absSourcePath), walkPath)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:653
			if err_2 != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:653
				return err_2
			}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:654
			header, err_3 := tar.FileInfoHeader(fi, "")
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:654
			if err_3 != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:654
				return err_3
			}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:655
			header.Name = filepath.ToSlash(rel)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:656
			if fi.IsDir() {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:657
				header.Name = (header.Name + "/")
			}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:658
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:658
			err_4 := tw.WriteHeader(header)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:658
			if err_4 != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:658
				return err_4
			}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:659
			if fi.Mode().IsRegular() {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:660
				f, err_5 := os.Open(walkPath)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:660
				if err_5 != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:660
					return err_5
				}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:661
				defer f.Close()
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:662
				_, err := io.Copy(tw, f)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:662
				if err != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:662
					return err
				}
			}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:663
			return nil
		})
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:664
		if err_43 != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:664
			err_43 = fmt.Errorf("container copy to walk: %w", err_43)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:664
			return nil, err_43
		}
	} else {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:666
		fi, err_44 := os.Stat(absSourcePath)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:666
		if err_44 != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:666
			err_44 = fmt.Errorf("container copy to stat file: %w", err_44)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:666
			return nil, err_44
		}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:667
		header, err_45 := tar.FileInfoHeader(fi, "")
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:667
		if err_45 != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:667
			err_45 = fmt.Errorf("container copy to header: %w", err_45)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:667
			return nil, err_45
		}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:668
		header.Name = filepath.ToSlash(filepath.Base(absSourcePath))
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:669
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:669
		err_46 := tw.WriteHeader(header)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:669
		if err_46 != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:669
			err_46 = fmt.Errorf("container copy to write header: %w", err_46)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:669
			return nil, err_46
		}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:670
		f, err_47 := os.Open(absSourcePath)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:670
		if err_47 != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:670
			err_47 = fmt.Errorf("container copy to open: %w", err_47)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:670
			return nil, err_47
		}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:671
		defer f.Close()
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:672
		_, err := io.Copy(tw, f)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:672
		if err != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:672
			err = fmt.Errorf("container copy to write file: %w", err)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:672
			return nil, err
		}
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:674
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:674
	err_48 := tw.Close()
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:674
	if err_48 != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:674
		err_48 = fmt.Errorf("container copy to close tar: %w", err_48)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:674
		return nil, err_48
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:675
	return &buf, nil
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:679
func CopyFrom(engine Engine, containerID string, sourcePath string, destPath string, handles ...ctxpkg.Handle) error {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:680
	ctx := ctxpkg.Background()
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:681
	if len(handles) > 0 {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:682
		ctx = handles[0]
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:683
	return copyFromWithContext(engine, ctx, containerID, sourcePath, destPath)
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:686
func copyFromWithContext(engine Engine, ctx ctxpkg.Handle, containerID string, sourcePath string, destPath string) error {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:687
	reader, _, err := engine.cli.CopyFromContainer(ctxpkg.Value(ctx), containerID, sourcePath)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:687
	if err != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:687
		err = fmt.Errorf("container copy from: %w", err)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:687
		return err
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:688
	defer reader.Close()
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:689
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:689
	err_49 := os.MkdirAll(destPath, 493)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:689
	if err_49 != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:689
		err_49 = fmt.Errorf("container copy from mkdir: %w", err_49)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:689
		return err_49
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:690
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:690
	err_50 := extractTar(reader, destPath)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:690
	if err_50 != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:690
		err_50 = fmt.Errorf("container copy from extract: %w", err_50)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:690
		return err_50
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:691
	return nil
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:695
func CopyTo(engine Engine, containerID string, sourcePath string, destPath string, handles ...ctxpkg.Handle) error {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:696
	ctx := ctxpkg.Background()
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:697
	if len(handles) > 0 {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:698
		ctx = handles[0]
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:699
	return copyToWithContext(engine, ctx, containerID, sourcePath, destPath)
}

//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:702
func copyToWithContext(engine Engine, ctx ctxpkg.Handle, containerID string, sourcePath string, destPath string) error {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:703
	archive, err_51 := createTarFromPath(sourcePath)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:703
	if err_51 != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:703
		return err_51
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:704
	copyOpts := dockercontainer.CopyToContainerOptions{AllowOverwriteDirWithFile: true}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:705
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:705
	err_52 := engine.cli.CopyToContainer(ctxpkg.Value(ctx), containerID, destPath, archive, copyOpts)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:705
	if err_52 != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:705
		err_52 = fmt.Errorf("container copy to: %w", err_52)
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:705
		return err_52
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/container/container.kuki:706
	return nil
}
