// Generated by Kukicha v0.0.16 (requires Go 1.26+)

package container

import (
	"archive/tar"
	"bufio"
	"bytes"
	"encoding/base64"
	"errors"
	"fmt"
	dockertypes "github.com/docker/docker/api/types"
	dockercontainer "github.com/docker/docker/api/types/container"
	dockerevents "github.com/docker/docker/api/types/events"
	dockerimage "github.com/docker/docker/api/types/image"
	"github.com/docker/docker/client"
	"github.com/docker/docker/pkg/stdcopy"
	ctxpkg "github.com/duber000/kukicha/stdlib/ctx"
	"github.com/duber000/kukicha/stdlib/json"
	kukistring "github.com/duber000/kukicha/stdlib/string"
	"io"
	"os"
	"path/filepath"
	"time"
)

//line /home/user/kukicha/stdlib/container/container.kuki:42
type Engine struct {
	cli *client.Client
}

//line /home/user/kukicha/stdlib/container/container.kuki:46
type Config struct {
	host       string
	apiVersion string
}

//line /home/user/kukicha/stdlib/container/container.kuki:51
type ContainerInfo struct {
	id     string
	image  string
	status string
	state  string
	names  []string
}

//line /home/user/kukicha/stdlib/container/container.kuki:59
type ImageInfo struct {
	id   string
	tags []string
	size int64
}

//line /home/user/kukicha/stdlib/container/container.kuki:65
type BuildOutput struct {
	imageID string
	output  string
}

//line /home/user/kukicha/stdlib/container/container.kuki:70
type Auth struct {
	username      string
	password      string
	serverAddress string
}

//line /home/user/kukicha/stdlib/container/container.kuki:76
type pullStatusMsg struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

//line /home/user/kukicha/stdlib/container/container.kuki:81
type buildStreamMsg struct {
	Stream string         `json:"stream"`
	Aux    buildStreamAux `json:"aux"`
	Error  string         `json:"error"`
}

//line /home/user/kukicha/stdlib/container/container.kuki:87
type buildStreamAux struct {
	ID string `json:"ID"`
}

//line /home/user/kukicha/stdlib/container/container.kuki:91
type dockerAuthEntry struct {
	Auth string `json:"auth"`
}

//line /home/user/kukicha/stdlib/container/container.kuki:95
type dockerConfig struct {
	Auths map[string]dockerAuthEntry `json:"auths"`
}

//line /home/user/kukicha/stdlib/container/container.kuki:99
type ContainerEvent struct {
	id       string
	resource string
	action   string
	actor    string
	time     string
}

//line /home/user/kukicha/stdlib/container/container.kuki:107
func New() Config {
//line /home/user/kukicha/stdlib/container/container.kuki:108
	return Config{}
}

//line /home/user/kukicha/stdlib/container/container.kuki:111
func Host(cfg Config, host string) Config {
//line /home/user/kukicha/stdlib/container/container.kuki:112
	cfg.host = host
//line /home/user/kukicha/stdlib/container/container.kuki:113
	return cfg
}

//line /home/user/kukicha/stdlib/container/container.kuki:116
func APIVersion(cfg Config, version string) Config {
//line /home/user/kukicha/stdlib/container/container.kuki:117
	cfg.apiVersion = version
//line /home/user/kukicha/stdlib/container/container.kuki:118
	return cfg
}

//line /home/user/kukicha/stdlib/container/container.kuki:121
func Close(engine Engine) error {
//line /home/user/kukicha/stdlib/container/container.kuki:122
	return engine.cli.Close()
}

//line /home/user/kukicha/stdlib/container/container.kuki:125
func ListContainers(engine Engine) ([]ContainerInfo, error) {
//line /home/user/kukicha/stdlib/container/container.kuki:126
	bg := ctxpkg.Background()
//line /home/user/kukicha/stdlib/container/container.kuki:127
	containers, err_1 := engine.cli.ContainerList(ctxpkg.Value(bg), dockercontainer.ListOptions{All: true})
	if err_1 != nil {
		err_1 = fmt.Errorf("container list: %w", err_1)
		return []ContainerInfo{}, err_1
	}
//line /home/user/kukicha/stdlib/container/container.kuki:129
	result := make([]ContainerInfo, len(containers))
//line /home/user/kukicha/stdlib/container/container.kuki:130
	for i, c := range containers {
//line /home/user/kukicha/stdlib/container/container.kuki:131
		result[i] = ContainerInfo{id: c.ID, image: c.Image, status: c.Status, state: c.State, names: c.Names}
	}
//line /home/user/kukicha/stdlib/container/container.kuki:138
	return result, nil
}

//line /home/user/kukicha/stdlib/container/container.kuki:141
func ListImages(engine Engine) ([]ImageInfo, error) {
//line /home/user/kukicha/stdlib/container/container.kuki:142
	bg := ctxpkg.Background()
//line /home/user/kukicha/stdlib/container/container.kuki:143
	images, err_2 := engine.cli.ImageList(ctxpkg.Value(bg), dockerimage.ListOptions{All: true})
	if err_2 != nil {
		err_2 = fmt.Errorf("container list images: %w", err_2)
		return []ImageInfo{}, err_2
	}
//line /home/user/kukicha/stdlib/container/container.kuki:145
	result := make([]ImageInfo, len(images))
//line /home/user/kukicha/stdlib/container/container.kuki:146
	for i, img := range images {
//line /home/user/kukicha/stdlib/container/container.kuki:147
		result[i] = ImageInfo{id: img.ID, tags: img.RepoTags, size: img.Size}
	}
//line /home/user/kukicha/stdlib/container/container.kuki:152
	return result, nil
}

//line /home/user/kukicha/stdlib/container/container.kuki:155
func Stop(engine Engine, containerID string) error {
//line /home/user/kukicha/stdlib/container/container.kuki:156
	bg := ctxpkg.Background()
//line /home/user/kukicha/stdlib/container/container.kuki:157
	err_3 := engine.cli.ContainerStop(ctxpkg.Value(bg), containerID, dockercontainer.StopOptions{})
	if err_3 != nil {
		err_3 = fmt.Errorf("container stop: %w", err_3)
		return err_3
	}
//line /home/user/kukicha/stdlib/container/container.kuki:158
	return nil
}

//line /home/user/kukicha/stdlib/container/container.kuki:161
func Remove(engine Engine, containerID string) error {
//line /home/user/kukicha/stdlib/container/container.kuki:162
	bg := ctxpkg.Background()
//line /home/user/kukicha/stdlib/container/container.kuki:163
	err_4 := engine.cli.ContainerRemove(ctxpkg.Value(bg), containerID, dockercontainer.RemoveOptions{})
	if err_4 != nil {
		err_4 = fmt.Errorf("container remove: %w", err_4)
		return err_4
	}
//line /home/user/kukicha/stdlib/container/container.kuki:164
	return nil
}

//line /home/user/kukicha/stdlib/container/container.kuki:167
func Login(username string, password string, server string) Auth {
//line /home/user/kukicha/stdlib/container/container.kuki:168
	return Auth{username: username, password: password, serverAddress: server}
}

//line /home/user/kukicha/stdlib/container/container.kuki:171
func AuthEncode(auth Auth) string {
//line /home/user/kukicha/stdlib/container/container.kuki:172
	authJSON, _ := json.Marshal(map[string]string{"username": auth.username, "password": auth.password, "serveraddress": auth.serverAddress})
//line /home/user/kukicha/stdlib/container/container.kuki:177
	return base64.URLEncoding.EncodeToString(authJSON)
}

//line /home/user/kukicha/stdlib/container/container.kuki:180
func ContainerID(c ContainerInfo) string {
//line /home/user/kukicha/stdlib/container/container.kuki:181
	return c.id
}

//line /home/user/kukicha/stdlib/container/container.kuki:184
func ContainerImage(c ContainerInfo) string {
//line /home/user/kukicha/stdlib/container/container.kuki:185
	return c.image
}

//line /home/user/kukicha/stdlib/container/container.kuki:188
func ContainerStatus(c ContainerInfo) string {
//line /home/user/kukicha/stdlib/container/container.kuki:189
	return c.status
}

//line /home/user/kukicha/stdlib/container/container.kuki:192
func ContainerState(c ContainerInfo) string {
//line /home/user/kukicha/stdlib/container/container.kuki:193
	return c.state
}

//line /home/user/kukicha/stdlib/container/container.kuki:196
func ContainerNames(c ContainerInfo) []string {
//line /home/user/kukicha/stdlib/container/container.kuki:197
	return c.names
}

//line /home/user/kukicha/stdlib/container/container.kuki:200
func ImageID(img ImageInfo) string {
//line /home/user/kukicha/stdlib/container/container.kuki:201
	return img.id
}

//line /home/user/kukicha/stdlib/container/container.kuki:204
func ImageTags(img ImageInfo) []string {
//line /home/user/kukicha/stdlib/container/container.kuki:205
	return img.tags
}

//line /home/user/kukicha/stdlib/container/container.kuki:208
func ImageSize(img ImageInfo) int64 {
//line /home/user/kukicha/stdlib/container/container.kuki:209
	return img.size
}

//line /home/user/kukicha/stdlib/container/container.kuki:212
func BuildImageID(b BuildOutput) string {
//line /home/user/kukicha/stdlib/container/container.kuki:213
	return b.imageID
}

//line /home/user/kukicha/stdlib/container/container.kuki:216
func BuildLog(b BuildOutput) string {
//line /home/user/kukicha/stdlib/container/container.kuki:217
	return b.output
}

//line /home/user/kukicha/stdlib/container/container.kuki:220
func EventID(event ContainerEvent) string {
//line /home/user/kukicha/stdlib/container/container.kuki:221
	return event.id
}

//line /home/user/kukicha/stdlib/container/container.kuki:224
func EventResource(event ContainerEvent) string {
//line /home/user/kukicha/stdlib/container/container.kuki:225
	return event.resource
}

//line /home/user/kukicha/stdlib/container/container.kuki:228
func EventAction(event ContainerEvent) string {
//line /home/user/kukicha/stdlib/container/container.kuki:229
	return event.action
}

//line /home/user/kukicha/stdlib/container/container.kuki:232
func EventActor(event ContainerEvent) string {
//line /home/user/kukicha/stdlib/container/container.kuki:233
	return event.actor
}

//line /home/user/kukicha/stdlib/container/container.kuki:236
func EventTime(event ContainerEvent) string {
//line /home/user/kukicha/stdlib/container/container.kuki:237
	return event.time
}

//line /home/user/kukicha/stdlib/container/container.kuki:243
func containerLogs(cli *client.Client, containerID string, tail string) (string, error) {
//line /home/user/kukicha/stdlib/container/container.kuki:244
	bg := ctxpkg.Background()
//line /home/user/kukicha/stdlib/container/container.kuki:245
	opts := dockercontainer.LogsOptions{ShowStdout: true, ShowStderr: true}
//line /home/user/kukicha/stdlib/container/container.kuki:246
	if tail != "" {
//line /home/user/kukicha/stdlib/container/container.kuki:247
		opts.Tail = tail
	}
//line /home/user/kukicha/stdlib/container/container.kuki:248
	reader, err_5 := cli.ContainerLogs(ctxpkg.Value(bg), containerID, opts)
	if err_5 != nil {
		err_5 = fmt.Errorf("container logs: %w", err_5)
		return "", err_5
	}
//line /home/user/kukicha/stdlib/container/container.kuki:249
	defer reader.Close()
//line /home/user/kukicha/stdlib/container/container.kuki:251
	stdout := bytes.Buffer{}
//line /home/user/kukicha/stdlib/container/container.kuki:252
	stderr := bytes.Buffer{}
//line /home/user/kukicha/stdlib/container/container.kuki:253
	_, err_6 := stdcopy.StdCopy(&stdout, &stderr, reader)
	if err_6 != nil {
		//line /home/user/kukicha/stdlib/container/container.kuki:254
		raw, err_7 := io.ReadAll(reader)
		if err_7 != nil {
			err_7 = fmt.Errorf("container logs: %w", err_7)
			return "", err_7
		}
		//line /home/user/kukicha/stdlib/container/container.kuki:255
		return string(raw), nil
	}
//line /home/user/kukicha/stdlib/container/container.kuki:257
	combined := stdout.String()
//line /home/user/kukicha/stdlib/container/container.kuki:258
	if stderr.Len() > 0 {
//line /home/user/kukicha/stdlib/container/container.kuki:259
		combined = (combined + stderr.String())
	}
//line /home/user/kukicha/stdlib/container/container.kuki:260
	return combined, nil
}

//line /home/user/kukicha/stdlib/container/container.kuki:263
func Logs(engine Engine, containerID string) (string, error) {
//line /home/user/kukicha/stdlib/container/container.kuki:264
	return containerLogs(engine.cli, containerID, "")
}

//line /home/user/kukicha/stdlib/container/container.kuki:267
func LogsTail(engine Engine, containerID string, lines int64) (string, error) {
//line /home/user/kukicha/stdlib/container/container.kuki:268
	return containerLogs(engine.cli, containerID, fmt.Sprintf("%d", lines))
}

//line /home/user/kukicha/stdlib/container/container.kuki:271
func Run(engine Engine, img string, cmd []string) (string, error) {
//line /home/user/kukicha/stdlib/container/container.kuki:272
	bg := ctxpkg.Background()
//line /home/user/kukicha/stdlib/container/container.kuki:273
	resp, err_8 := engine.cli.ContainerCreate(ctxpkg.Value(bg), &dockercontainer.Config{Image: img, Cmd: cmd}, nil, nil, nil, "")
	if err_8 != nil {
		err_8 = fmt.Errorf("container run create: %w", err_8)
		return "", err_8
	}
//line /home/user/kukicha/stdlib/container/container.kuki:278
	err_9 := engine.cli.ContainerStart(ctxpkg.Value(bg), resp.ID, dockercontainer.StartOptions{})
	if err_9 != nil {
		err_9 = fmt.Errorf("container run start: %w", err_9)
		return "", err_9
	}
//line /home/user/kukicha/stdlib/container/container.kuki:280
	return resp.ID, nil
}

//line /home/user/kukicha/stdlib/container/container.kuki:283
func Inspect(engine Engine, containerID string) (ContainerInfo, error) {
//line /home/user/kukicha/stdlib/container/container.kuki:284
	bg := ctxpkg.Background()
//line /home/user/kukicha/stdlib/container/container.kuki:285
	info, err_10 := engine.cli.ContainerInspect(ctxpkg.Value(bg), containerID)
	if err_10 != nil {
		err_10 = fmt.Errorf("container inspect: %w", err_10)
		return *new(ContainerInfo), err_10
	}
//line /home/user/kukicha/stdlib/container/container.kuki:287
	names := make([]string, 0)
//line /home/user/kukicha/stdlib/container/container.kuki:288
	if info.Name != "" {
//line /home/user/kukicha/stdlib/container/container.kuki:289
		names = append(names, kukistring.TrimPrefix(info.Name, "/"))
	}
//line /home/user/kukicha/stdlib/container/container.kuki:290
	status := ""
//line /home/user/kukicha/stdlib/container/container.kuki:291
	state := ""
//line /home/user/kukicha/stdlib/container/container.kuki:292
	if info.State != nil {
//line /home/user/kukicha/stdlib/container/container.kuki:293
		status = info.State.Status
//line /home/user/kukicha/stdlib/container/container.kuki:294
		state = info.State.Status
	}
//line /home/user/kukicha/stdlib/container/container.kuki:295
	return ContainerInfo{id: info.ID, image: info.Config.Image, status: status, state: state, names: names}, nil
}

//line /home/user/kukicha/stdlib/container/container.kuki:305
func Exec(engine Engine, containerID string, cmd []string, handles ...ctxpkg.Handle) (string, error) {
//line /home/user/kukicha/stdlib/container/container.kuki:306
	ctx := ctxpkg.Background()
//line /home/user/kukicha/stdlib/container/container.kuki:307
	if len(handles) > 0 {
//line /home/user/kukicha/stdlib/container/container.kuki:308
		ctx = handles[0]
	}
//line /home/user/kukicha/stdlib/container/container.kuki:309
	createResp, err_11 := engine.cli.ContainerExecCreate(ctxpkg.Value(ctx), containerID, dockertypes.ExecConfig{Cmd: cmd, AttachStdout: true, AttachStderr: true})
	if err_11 != nil {
		err_11 = fmt.Errorf("container exec create: %w", err_11)
		return "", err_11
	}
//line /home/user/kukicha/stdlib/container/container.kuki:315
	attachResp, err_12 := engine.cli.ContainerExecAttach(ctxpkg.Value(ctx), createResp.ID, dockertypes.ExecStartCheck{})
	if err_12 != nil {
		err_12 = fmt.Errorf("container exec attach: %w", err_12)
		return "", err_12
	}
//line /home/user/kukicha/stdlib/container/container.kuki:316
	defer attachResp.Close()
//line /home/user/kukicha/stdlib/container/container.kuki:318
	stdout := bytes.Buffer{}
//line /home/user/kukicha/stdlib/container/container.kuki:319
	stderr := bytes.Buffer{}
//line /home/user/kukicha/stdlib/container/container.kuki:320
	_, err_13 := stdcopy.StdCopy(&stdout, &stderr, attachResp.Reader)
	if err_13 != nil {
		//line /home/user/kukicha/stdlib/container/container.kuki:321
		raw, err_14 := io.ReadAll(attachResp.Reader)
		if err_14 != nil {
			err_14 = fmt.Errorf("container exec read: %w", err_14)
			return "", err_14
		}
		//line /home/user/kukicha/stdlib/container/container.kuki:322
		return string(raw), nil
	}
//line /home/user/kukicha/stdlib/container/container.kuki:324
	inspectResult, err_15 := engine.cli.ContainerExecInspect(ctxpkg.Value(ctx), createResp.ID)
	if err_15 != nil {
		err_15 = fmt.Errorf("container exec inspect: %w", err_15)
		return "", err_15
	}
//line /home/user/kukicha/stdlib/container/container.kuki:326
	combined := stdout.String()
//line /home/user/kukicha/stdlib/container/container.kuki:327
	if stderr.Len() > 0 {
//line /home/user/kukicha/stdlib/container/container.kuki:328
		combined = (combined + stderr.String())
	}
//line /home/user/kukicha/stdlib/container/container.kuki:329
	if inspectResult.ExitCode != 0 {
//line /home/user/kukicha/stdlib/container/container.kuki:330
		return combined, errors.New(fmt.Sprintf("container exec exit %v", inspectResult.ExitCode))
	}
//line /home/user/kukicha/stdlib/container/container.kuki:331
	return combined, nil
}

//line /home/user/kukicha/stdlib/container/container.kuki:337
func Wait(engine Engine, containerID string, timeoutSeconds int64) (int64, error) {
//line /home/user/kukicha/stdlib/container/container.kuki:338
	h := ctxpkg.Background()
//line /home/user/kukicha/stdlib/container/container.kuki:339
	if timeoutSeconds > 0 {
//line /home/user/kukicha/stdlib/container/container.kuki:340
		h = ctxpkg.WithTimeout(h, timeoutSeconds)
	}
//line /home/user/kukicha/stdlib/container/container.kuki:341
	defer ctxpkg.Cancel(h)
//line /home/user/kukicha/stdlib/container/container.kuki:342
	return WaitCtx(engine, h, containerID)
}

//line /home/user/kukicha/stdlib/container/container.kuki:345
func WaitCtx(engine Engine, h ctxpkg.Handle, containerID string) (int64, error) {
//line /home/user/kukicha/stdlib/container/container.kuki:346
	goCtx := ctxpkg.Value(h)
//line /home/user/kukicha/stdlib/container/container.kuki:347
	waitCh, errCh := engine.cli.ContainerWait(goCtx, containerID, dockercontainer.WaitConditionNotRunning)
//line /home/user/kukicha/stdlib/container/container.kuki:348
	select {
	case err := <-errCh:
//line /home/user/kukicha/stdlib/container/container.kuki:350
		if err == nil {
//line /home/user/kukicha/stdlib/container/container.kuki:351
			return -1, errors.New("container wait: unknown wait error")
		}
//line /home/user/kukicha/stdlib/container/container.kuki:352
		return -1, errors.New(fmt.Sprintf("container wait: %v", err))
	case res := <-waitCh:
//line /home/user/kukicha/stdlib/container/container.kuki:354
		return res.StatusCode, nil
	}
}

//line /home/user/kukicha/stdlib/container/container.kuki:359
func convertEvent(msg dockerevents.Message) ContainerEvent {
//line /home/user/kukicha/stdlib/container/container.kuki:360
	ts := time.Unix(msg.Time, 0).UTC().Format(time.RFC3339)
//line /home/user/kukicha/stdlib/container/container.kuki:361
	actor := msg.Actor.ID
//line /home/user/kukicha/stdlib/container/container.kuki:362
	name, ok := msg.Actor.Attributes["name"]
//line /home/user/kukicha/stdlib/container/container.kuki:363
	if ok && (name != "") {
//line /home/user/kukicha/stdlib/container/container.kuki:364
		actor = name
	}
//line /home/user/kukicha/stdlib/container/container.kuki:365
	return ContainerEvent{id: msg.ID, resource: string(msg.Type), action: string(msg.Action), actor: actor, time: ts}
}

//line /home/user/kukicha/stdlib/container/container.kuki:374
func eventsWithContext(engine Engine, h ctxpkg.Handle) ([]ContainerEvent, error) {
//line /home/user/kukicha/stdlib/container/container.kuki:375
	goCtx := ctxpkg.Value(h)
//line /home/user/kukicha/stdlib/container/container.kuki:376
	msgCh, errCh := engine.cli.Events(goCtx, dockertypes.EventsOptions{})
//line /home/user/kukicha/stdlib/container/container.kuki:377
	events := make([]ContainerEvent, 0)
//line /home/user/kukicha/stdlib/container/container.kuki:378
	for {
//line /home/user/kukicha/stdlib/container/container.kuki:379
		select {
		case <-goCtx.Done():
//line /home/user/kukicha/stdlib/container/container.kuki:381
			return events, nil
		case err := <-errCh:
//line /home/user/kukicha/stdlib/container/container.kuki:383
			if (err == nil) || (goCtx.Err() != nil) {
//line /home/user/kukicha/stdlib/container/container.kuki:384
				return events, nil
			}
//line /home/user/kukicha/stdlib/container/container.kuki:385
			return events, errors.New(fmt.Sprintf("container events: %v", err))
		case msg, ok := <-msgCh:
//line /home/user/kukicha/stdlib/container/container.kuki:387
			if !ok {
//line /home/user/kukicha/stdlib/container/container.kuki:388
				return events, nil
			}
//line /home/user/kukicha/stdlib/container/container.kuki:389
			events = append(events, convertEvent(msg))
		}
	}
//line /home/user/kukicha/stdlib/container/container.kuki:390
	return events, nil
}

//line /home/user/kukicha/stdlib/container/container.kuki:394
func Events(engine Engine, timeoutSeconds int64) ([]ContainerEvent, error) {
//line /home/user/kukicha/stdlib/container/container.kuki:395
	if timeoutSeconds <= 0 {
//line /home/user/kukicha/stdlib/container/container.kuki:396
		timeoutSeconds = 15
	}
//line /home/user/kukicha/stdlib/container/container.kuki:397
	h := ctxpkg.WithTimeout(ctxpkg.Background(), timeoutSeconds)
//line /home/user/kukicha/stdlib/container/container.kuki:398
	defer ctxpkg.Cancel(h)
//line /home/user/kukicha/stdlib/container/container.kuki:399
	return eventsWithContext(engine, h)
}

//line /home/user/kukicha/stdlib/container/container.kuki:402
func EventsCtx(engine Engine, h ctxpkg.Handle) ([]ContainerEvent, error) {
//line /home/user/kukicha/stdlib/container/container.kuki:403
	return eventsWithContext(engine, h)
}

//line /home/user/kukicha/stdlib/container/container.kuki:409
func Pull(engine Engine, ref string, handles ...ctxpkg.Handle) (string, error) {
//line /home/user/kukicha/stdlib/container/container.kuki:410
	bg := ctxpkg.Background()
//line /home/user/kukicha/stdlib/container/container.kuki:411
	if len(handles) > 0 {
//line /home/user/kukicha/stdlib/container/container.kuki:412
		bg = handles[0]
	}
//line /home/user/kukicha/stdlib/container/container.kuki:413
	reader, err_16 := engine.cli.ImagePull(ctxpkg.Value(bg), ref, dockerimage.PullOptions{})
	if err_16 != nil {
		err_16 = fmt.Errorf("container pull: %w", err_16)
		return "", err_16
	}
//line /home/user/kukicha/stdlib/container/container.kuki:414
	defer reader.Close()
//line /home/user/kukicha/stdlib/container/container.kuki:415
	digest := ""
//line /home/user/kukicha/stdlib/container/container.kuki:416
	scanner := bufio.NewScanner(reader)
//line /home/user/kukicha/stdlib/container/container.kuki:417
	for scanner.Scan() {
//line /home/user/kukicha/stdlib/container/container.kuki:418
		msg := pullStatusMsg{}
//line /home/user/kukicha/stdlib/container/container.kuki:419
		err_17 := json.Unmarshal(scanner.Bytes(), &msg)
		if err_17 != nil {
			//line /home/user/kukicha/stdlib/container/container.kuki:420
			continue
		}
//line /home/user/kukicha/stdlib/container/container.kuki:421
		if kukistring.HasPrefix(msg.Status, "Digest:") {
//line /home/user/kukicha/stdlib/container/container.kuki:422
			digest = kukistring.TrimPrefix(msg.Status, "Digest: ")
		}
	}
//line /home/user/kukicha/stdlib/container/container.kuki:423
	if digest == "" {
//line /home/user/kukicha/stdlib/container/container.kuki:424
		digest = ref
	}
//line /home/user/kukicha/stdlib/container/container.kuki:425
	return digest, nil
}

//line /home/user/kukicha/stdlib/container/container.kuki:428
func PullAuth(engine Engine, ref string, auth Auth) (string, error) {
//line /home/user/kukicha/stdlib/container/container.kuki:429
	authJSON, err_18 := json.Marshal(map[string]string{"username": auth.username, "password": auth.password, "serveraddress": auth.serverAddress})
	if err_18 != nil {
		err_18 = fmt.Errorf("container pull auth: %w", err_18)
		return "", err_18
	}
//line /home/user/kukicha/stdlib/container/container.kuki:435
	encoded := base64.URLEncoding.EncodeToString(authJSON)
//line /home/user/kukicha/stdlib/container/container.kuki:436
	reader, err_19 := engine.cli.ImagePull(ctxpkg.Value(ctxpkg.Background()), ref, dockerimage.PullOptions{RegistryAuth: encoded})
	if err_19 != nil {
		err_19 = fmt.Errorf("container pull: %w", err_19)
		return "", err_19
	}
//line /home/user/kukicha/stdlib/container/container.kuki:439
	defer reader.Close()
//line /home/user/kukicha/stdlib/container/container.kuki:441
	digest := ""
//line /home/user/kukicha/stdlib/container/container.kuki:442
	scanner := bufio.NewScanner(reader)
//line /home/user/kukicha/stdlib/container/container.kuki:443
	for scanner.Scan() {
//line /home/user/kukicha/stdlib/container/container.kuki:444
		msg := pullStatusMsg{}
//line /home/user/kukicha/stdlib/container/container.kuki:445
		err_20 := json.Unmarshal(scanner.Bytes(), &msg)
		if err_20 != nil {
			//line /home/user/kukicha/stdlib/container/container.kuki:446
			continue
		}
//line /home/user/kukicha/stdlib/container/container.kuki:447
		if kukistring.HasPrefix(msg.Status, "Digest:") {
//line /home/user/kukicha/stdlib/container/container.kuki:448
			digest = kukistring.TrimPrefix(msg.Status, "Digest: ")
		}
	}
//line /home/user/kukicha/stdlib/container/container.kuki:449
	if digest == "" {
//line /home/user/kukicha/stdlib/container/container.kuki:450
		digest = ref
	}
//line /home/user/kukicha/stdlib/container/container.kuki:451
	return digest, nil
}

//line /home/user/kukicha/stdlib/container/container.kuki:456
func loadDockerAuth(serverAddress string) (string, string, string, error) {
//line /home/user/kukicha/stdlib/container/container.kuki:457
	home, err_21 := os.UserHomeDir()
	if err_21 != nil {
		err_21 = fmt.Errorf("container auth: %w", err_21)
		return "", "", "", err_21
	}
//line /home/user/kukicha/stdlib/container/container.kuki:458
	configPath := filepath.Join(home, ".docker", "config.json")
//line /home/user/kukicha/stdlib/container/container.kuki:459
	data, err_22 := os.ReadFile(configPath)
	if err_22 != nil {
		err_22 = fmt.Errorf("container auth: %w", err_22)
		return "", "", "", err_22
	}
//line /home/user/kukicha/stdlib/container/container.kuki:460
	config := dockerConfig{}
//line /home/user/kukicha/stdlib/container/container.kuki:461
	err_23 := json.Unmarshal(data, &config)
	if err_23 != nil {
		err_23 = fmt.Errorf("container auth parse: %w", err_23)
		return "", "", "", err_23
	}
//line /home/user/kukicha/stdlib/container/container.kuki:462
	authEntry, ok := config.Auths[serverAddress]
//line /home/user/kukicha/stdlib/container/container.kuki:463
	if !ok {
//line /home/user/kukicha/stdlib/container/container.kuki:464
		variations := []string{("https://" + serverAddress), ("http://" + serverAddress), kukistring.TrimPrefix(serverAddress, "https://"), kukistring.TrimPrefix(serverAddress, "http://")}
//line /home/user/kukicha/stdlib/container/container.kuki:470
		for _, v := range variations {
//line /home/user/kukicha/stdlib/container/container.kuki:471
			a, found := config.Auths[v]
//line /home/user/kukicha/stdlib/container/container.kuki:472
			if found {
//line /home/user/kukicha/stdlib/container/container.kuki:473
				authEntry = a
//line /home/user/kukicha/stdlib/container/container.kuki:474
				ok = true
//line /home/user/kukicha/stdlib/container/container.kuki:475
				break
			}
		}
	}
//line /home/user/kukicha/stdlib/container/container.kuki:476
	if !ok {
//line /home/user/kukicha/stdlib/container/container.kuki:477
		return "", "", "", errors.New(fmt.Sprintf("container auth: no credentials found for %v", serverAddress))
	}
//line /home/user/kukicha/stdlib/container/container.kuki:478
	if authEntry.Auth == "" {
//line /home/user/kukicha/stdlib/container/container.kuki:479
		return "", "", "", errors.New(fmt.Sprintf("container auth: empty credentials for %v", serverAddress))
	}
//line /home/user/kukicha/stdlib/container/container.kuki:480
	decoded, err_24 := base64.StdEncoding.DecodeString(authEntry.Auth)
	if err_24 != nil {
		err_24 = fmt.Errorf("container auth decode: %w", err_24)
		return "", "", "", err_24
	}
//line /home/user/kukicha/stdlib/container/container.kuki:481
	parts := kukistring.SplitN(string(decoded), ":", 2)
//line /home/user/kukicha/stdlib/container/container.kuki:482
	if len(parts) != 2 {
//line /home/user/kukicha/stdlib/container/container.kuki:483
		return "", "", "", errors.New(fmt.Sprintf("container auth: invalid credential format for %v", serverAddress))
	}
//line /home/user/kukicha/stdlib/container/container.kuki:484
	return parts[0], parts[1], serverAddress, nil
}

//line /home/user/kukicha/stdlib/container/container.kuki:487
func LoginFromConfig(server string) (Auth, error) {
//line /home/user/kukicha/stdlib/container/container.kuki:488
	username, password, addr, err_25 := loadDockerAuth(server)
	if err_25 != nil {
		return *new(Auth), err_25
	}
//line /home/user/kukicha/stdlib/container/container.kuki:489
	return Auth{username: username, password: password, serverAddress: addr}, nil
}

//line /home/user/kukicha/stdlib/container/container.kuki:496
func newClient(host string) (*client.Client, error) {
//line /home/user/kukicha/stdlib/container/container.kuki:497
	opts := []client.Opt{client.FromEnv, client.WithAPIVersionNegotiation()}
//line /home/user/kukicha/stdlib/container/container.kuki:498
	if host != "" {
//line /home/user/kukicha/stdlib/container/container.kuki:499
		opts = append(opts, client.WithHost(host))
	}
//line /home/user/kukicha/stdlib/container/container.kuki:500
	cli, err_26 := client.NewClientWithOpts(opts...)
	if err_26 != nil {
		err_26 = fmt.Errorf("container connect: %w", err_26)
		return nil, err_26
	}
//line /home/user/kukicha/stdlib/container/container.kuki:501
	return cli, nil
}

//line /home/user/kukicha/stdlib/container/container.kuki:504
func Connect() (Engine, error) {
//line /home/user/kukicha/stdlib/container/container.kuki:505
	socketPaths := []string{fmt.Sprintf("/run/user/%d/podman/podman.sock", os.Getuid()), "/var/run/docker.sock", "/run/podman/podman.sock"}
//line /home/user/kukicha/stdlib/container/container.kuki:510
	host := ""
//line /home/user/kukicha/stdlib/container/container.kuki:511
	for _, p := range socketPaths {
//line /home/user/kukicha/stdlib/container/container.kuki:512
		_, statErr := os.Stat(p)
//line /home/user/kukicha/stdlib/container/container.kuki:513
		if statErr == nil {
//line /home/user/kukicha/stdlib/container/container.kuki:514
			host = ("unix://" + p)
//line /home/user/kukicha/stdlib/container/container.kuki:515
			break
		}
	}
//line /home/user/kukicha/stdlib/container/container.kuki:516
	cli, err_27 := newClient(host)
	if err_27 != nil {
		return *new(Engine), err_27
	}
//line /home/user/kukicha/stdlib/container/container.kuki:517
	return Engine{cli: cli}, nil
}

//line /home/user/kukicha/stdlib/container/container.kuki:520
func ConnectRemote(host string) (Engine, error) {
//line /home/user/kukicha/stdlib/container/container.kuki:521
	cli, err_28 := newClient(host)
	if err_28 != nil {
		return *new(Engine), err_28
	}
//line /home/user/kukicha/stdlib/container/container.kuki:522
	return Engine{cli: cli}, nil
}

//line /home/user/kukicha/stdlib/container/container.kuki:525
func Open(cfg Config) (Engine, error) {
//line /home/user/kukicha/stdlib/container/container.kuki:526
	opts := []client.Opt{client.FromEnv, client.WithAPIVersionNegotiation()}
//line /home/user/kukicha/stdlib/container/container.kuki:527
	if cfg.host != "" {
//line /home/user/kukicha/stdlib/container/container.kuki:528
		opts = append(opts, client.WithHost(cfg.host))
	}
//line /home/user/kukicha/stdlib/container/container.kuki:529
	if cfg.apiVersion != "" {
//line /home/user/kukicha/stdlib/container/container.kuki:530
		opts = append(opts, client.WithVersion(cfg.apiVersion))
	}
//line /home/user/kukicha/stdlib/container/container.kuki:531
	cli, err_29 := client.NewClientWithOpts(opts...)
	if err_29 != nil {
		err_29 = fmt.Errorf("container open: %w", err_29)
		return *new(Engine), err_29
	}
//line /home/user/kukicha/stdlib/container/container.kuki:532
	return Engine{cli: cli}, nil
}

//line /home/user/kukicha/stdlib/container/container.kuki:536
func buildImage(cli *client.Client, contextPath string, tag string) (string, string, error) {
//line /home/user/kukicha/stdlib/container/container.kuki:537
	buf := bytes.Buffer{}
//line /home/user/kukicha/stdlib/container/container.kuki:538
	tw := tar.NewWriter(&buf)
//line /home/user/kukicha/stdlib/container/container.kuki:539
	absContextPath, err_30 := filepath.Abs(contextPath)
	if err_30 != nil {
		err_30 = fmt.Errorf("container build: %w", err_30)
		return "", "", err_30
	}
//line /home/user/kukicha/stdlib/container/container.kuki:540
	walkErr := filepath.WalkDir(absContextPath, func(walkPath string, d os.DirEntry, err error) error {
//line /home/user/kukicha/stdlib/container/container.kuki:541
		if err != nil {
//line /home/user/kukicha/stdlib/container/container.kuki:542
			return err
		}
//line /home/user/kukicha/stdlib/container/container.kuki:543
		if d.IsDir() && (d.Name() == ".git") {
//line /home/user/kukicha/stdlib/container/container.kuki:544
			return filepath.SkipDir
		}
//line /home/user/kukicha/stdlib/container/container.kuki:546
		if d.Type() == os.ModeSymlink {
//line /home/user/kukicha/stdlib/container/container.kuki:547
			return nil
		}
//line /home/user/kukicha/stdlib/container/container.kuki:548
		relPath, relErr := filepath.Rel(absContextPath, walkPath)
//line /home/user/kukicha/stdlib/container/container.kuki:549
		if relErr != nil {
//line /home/user/kukicha/stdlib/container/container.kuki:550
			return relErr
		}
//line /home/user/kukicha/stdlib/container/container.kuki:551
		if d.IsDir() {
//line /home/user/kukicha/stdlib/container/container.kuki:552
			return nil
		}
//line /home/user/kukicha/stdlib/container/container.kuki:553
		info, infoErr := d.Info()
//line /home/user/kukicha/stdlib/container/container.kuki:554
		if infoErr != nil {
//line /home/user/kukicha/stdlib/container/container.kuki:555
			return infoErr
		}
//line /home/user/kukicha/stdlib/container/container.kuki:556
		header, headerErr := tar.FileInfoHeader(info, "")
//line /home/user/kukicha/stdlib/container/container.kuki:557
		if headerErr != nil {
//line /home/user/kukicha/stdlib/container/container.kuki:558
			return headerErr
		}
//line /home/user/kukicha/stdlib/container/container.kuki:559
		header.Name = relPath
//line /home/user/kukicha/stdlib/container/container.kuki:560
		writeErr := tw.WriteHeader(header)
//line /home/user/kukicha/stdlib/container/container.kuki:561
		if writeErr != nil {
//line /home/user/kukicha/stdlib/container/container.kuki:562
			return writeErr
		}
//line /home/user/kukicha/stdlib/container/container.kuki:563
		f, openErr := os.Open(walkPath)
//line /home/user/kukicha/stdlib/container/container.kuki:564
		if openErr != nil {
//line /home/user/kukicha/stdlib/container/container.kuki:565
			return openErr
		}
//line /home/user/kukicha/stdlib/container/container.kuki:566
		defer f.Close()
//line /home/user/kukicha/stdlib/container/container.kuki:567
		_, copyErr := io.Copy(tw, f)
//line /home/user/kukicha/stdlib/container/container.kuki:568
		return copyErr
	})
//line /home/user/kukicha/stdlib/container/container.kuki:570
	if walkErr != nil {
//line /home/user/kukicha/stdlib/container/container.kuki:571
		return "", "", errors.New(fmt.Sprintf("container build context: %v", walkErr))
	}
//line /home/user/kukicha/stdlib/container/container.kuki:572
	err_31 := tw.Close()
	if err_31 != nil {
		err_31 = fmt.Errorf("container build tar: %w", err_31)
		return "", "", err_31
	}
//line /home/user/kukicha/stdlib/container/container.kuki:573
	buildOpts := dockertypes.ImageBuildOptions{Tags: []string{tag}, Remove: true, Dockerfile: "Dockerfile"}
//line /home/user/kukicha/stdlib/container/container.kuki:578
	resp, err_32 := cli.ImageBuild(ctxpkg.Value(ctxpkg.Background()), &buf, buildOpts)
	if err_32 != nil {
		err_32 = fmt.Errorf("container build: %w", err_32)
		return "", "", err_32
	}
//line /home/user/kukicha/stdlib/container/container.kuki:579
	defer resp.Body.Close()
//line /home/user/kukicha/stdlib/container/container.kuki:580
	output := bytes.Buffer{}
//line /home/user/kukicha/stdlib/container/container.kuki:581
	imageID := ""
//line /home/user/kukicha/stdlib/container/container.kuki:582
	scanner := bufio.NewScanner(resp.Body)
//line /home/user/kukicha/stdlib/container/container.kuki:583
	for scanner.Scan() {
//line /home/user/kukicha/stdlib/container/container.kuki:584
		line := scanner.Text()
//line /home/user/kukicha/stdlib/container/container.kuki:585
		output.WriteString(line)
//line /home/user/kukicha/stdlib/container/container.kuki:586
		output.WriteString("\n")
//line /home/user/kukicha/stdlib/container/container.kuki:587
		msg := buildStreamMsg{}
//line /home/user/kukicha/stdlib/container/container.kuki:588
		err_33 := json.Unmarshal(scanner.Bytes(), &msg)
		if err_33 != nil {
			continue
		}
//line /home/user/kukicha/stdlib/container/container.kuki:589
		if msg.Error != "" {
//line /home/user/kukicha/stdlib/container/container.kuki:590
			return "", output.String(), errors.New(fmt.Sprintf("container build: %v", msg.Error))
		}
//line /home/user/kukicha/stdlib/container/container.kuki:591
		if msg.Aux.ID != "" {
//line /home/user/kukicha/stdlib/container/container.kuki:592
			imageID = msg.Aux.ID
		}
	}
//line /home/user/kukicha/stdlib/container/container.kuki:593
	err_34 := scanner.Err()
	if err_34 != nil {
		err_34 = fmt.Errorf("container build stream: %w", err_34)
		return "", "", err_34
	}
//line /home/user/kukicha/stdlib/container/container.kuki:594
	return imageID, output.String(), nil
}

//line /home/user/kukicha/stdlib/container/container.kuki:597
func Build(engine Engine, path string, tag string) (BuildOutput, error) {
//line /home/user/kukicha/stdlib/container/container.kuki:598
	imageID, output, err_35 := buildImage(engine.cli, path, tag)
	if err_35 != nil {
		return *new(BuildOutput), err_35
	}
//line /home/user/kukicha/stdlib/container/container.kuki:599
	return BuildOutput{imageID: imageID, output: output}, nil
}

//line /home/user/kukicha/stdlib/container/container.kuki:602
func extractTar(reader io.Reader, destPath string) error {
//line /home/user/kukicha/stdlib/container/container.kuki:603
	tr := tar.NewReader(reader)
//line /home/user/kukicha/stdlib/container/container.kuki:604
	cleanDest := filepath.Clean(destPath)
//line /home/user/kukicha/stdlib/container/container.kuki:605
	for {
//line /home/user/kukicha/stdlib/container/container.kuki:606
		header, err := tr.Next()
//line /home/user/kukicha/stdlib/container/container.kuki:607
		if err == io.EOF {
//line /home/user/kukicha/stdlib/container/container.kuki:608
			break
		}
//line /home/user/kukicha/stdlib/container/container.kuki:609
		if err != nil {
//line /home/user/kukicha/stdlib/container/container.kuki:610
			return err
		}
//line /home/user/kukicha/stdlib/container/container.kuki:611
		cleanName := filepath.Clean(header.Name)
//line /home/user/kukicha/stdlib/container/container.kuki:612
		target := filepath.Join(destPath, cleanName)
//line /home/user/kukicha/stdlib/container/container.kuki:613
		if !kukistring.HasPrefix(target, (cleanDest+string(filepath.Separator))) && (filepath.Clean(target) != cleanDest) {
//line /home/user/kukicha/stdlib/container/container.kuki:614
			return errors.New(fmt.Sprintf("invalid archive path: %v", header.Name))
		}
//line /home/user/kukicha/stdlib/container/container.kuki:615
		switch header.Typeflag {
		case tar.TypeDir:
//line /home/user/kukicha/stdlib/container/container.kuki:617
			err_36 := os.MkdirAll(target, os.FileMode(header.Mode))
			if err_36 != nil {
				return err_36
			}
		case tar.TypeReg:
//line /home/user/kukicha/stdlib/container/container.kuki:619
			err_37 := os.MkdirAll(filepath.Dir(target), 493)
			if err_37 != nil {
				return err_37
			}
//line /home/user/kukicha/stdlib/container/container.kuki:620
			f, err_38 := os.OpenFile(target, ((os.O_CREATE | os.O_WRONLY) | os.O_TRUNC), os.FileMode(header.Mode))
			if err_38 != nil {
				return err_38
			}
//line /home/user/kukicha/stdlib/container/container.kuki:621
			_, err_39 := io.Copy(f, tr)
			if err_39 != nil {
				//line /home/user/kukicha/stdlib/container/container.kuki:622
				f.Close()
				//line /home/user/kukicha/stdlib/container/container.kuki:623
				return errors.New(fmt.Sprintf("%v", err_39))
			}
//line /home/user/kukicha/stdlib/container/container.kuki:624
			err_40 := f.Close()
			if err_40 != nil {
				return err_40
			}
		case tar.TypeSymlink, tar.TypeLink:
//line /home/user/kukicha/stdlib/container/container.kuki:626
			return errors.New(fmt.Sprintf("archive contains unsupported link entry: %v", header.Name))
		default:
//line /home/user/kukicha/stdlib/container/container.kuki:628
			return errors.New(fmt.Sprintf("archive contains unsupported entry type %v: %v", header.Typeflag, header.Name))
		}
	}
//line /home/user/kukicha/stdlib/container/container.kuki:629
	return nil
}

//line /home/user/kukicha/stdlib/container/container.kuki:632
func createTarFromPath(sourcePath string) (io.Reader, error) {
//line /home/user/kukicha/stdlib/container/container.kuki:633
	absSourcePath, err_41 := filepath.Abs(sourcePath)
	if err_41 != nil {
		err_41 = fmt.Errorf("container copy to abs path: %w", err_41)
		return nil, err_41
	}
//line /home/user/kukicha/stdlib/container/container.kuki:636
	info, err_42 := os.Lstat(absSourcePath)
	if err_42 != nil {
		err_42 = fmt.Errorf("container copy to stat: %w", err_42)
		return nil, err_42
	}
//line /home/user/kukicha/stdlib/container/container.kuki:638
	if info.Mode().Type() == os.ModeSymlink {
//line /home/user/kukicha/stdlib/container/container.kuki:639
		return nil, errors.New(fmt.Sprintf("container copy to: source path is a symlink: %v", absSourcePath))
	}
//line /home/user/kukicha/stdlib/container/container.kuki:640
	buf := bytes.Buffer{}
//line /home/user/kukicha/stdlib/container/container.kuki:641
	tw := tar.NewWriter(&buf)
//line /home/user/kukicha/stdlib/container/container.kuki:642
	if info.IsDir() {
//line /home/user/kukicha/stdlib/container/container.kuki:643
		err_43 := filepath.WalkDir(absSourcePath, func(walkPath string, d os.DirEntry, err error) error {
//line /home/user/kukicha/stdlib/container/container.kuki:644
			if err != nil {
//line /home/user/kukicha/stdlib/container/container.kuki:645
				return err
			}
//line /home/user/kukicha/stdlib/container/container.kuki:647
			if d.Type() == os.ModeSymlink {
//line /home/user/kukicha/stdlib/container/container.kuki:648
				return nil
			}
//line /home/user/kukicha/stdlib/container/container.kuki:649
			fi, err_1 := d.Info()
			if err_1 != nil {
				return err_1
			}
//line /home/user/kukicha/stdlib/container/container.kuki:652
			if fi.Mode().Type() == os.ModeSymlink {
//line /home/user/kukicha/stdlib/container/container.kuki:653
				return nil
			}
//line /home/user/kukicha/stdlib/container/container.kuki:655
			rel, err_2 := filepath.Rel(filepath.Dir(absSourcePath), walkPath)
			if err_2 != nil {
				return err_2
			}
//line /home/user/kukicha/stdlib/container/container.kuki:656
			header, err_3 := tar.FileInfoHeader(fi, "")
			if err_3 != nil {
				return err_3
			}
//line /home/user/kukicha/stdlib/container/container.kuki:657
			header.Name = filepath.ToSlash(rel)
//line /home/user/kukicha/stdlib/container/container.kuki:658
			if fi.IsDir() {
//line /home/user/kukicha/stdlib/container/container.kuki:659
				header.Name = (header.Name + "/")
			}
//line /home/user/kukicha/stdlib/container/container.kuki:660
			err_4 := tw.WriteHeader(header)
			if err_4 != nil {
				return err_4
			}
//line /home/user/kukicha/stdlib/container/container.kuki:661
			if fi.Mode().IsRegular() {
//line /home/user/kukicha/stdlib/container/container.kuki:662
				f, err_5 := os.Open(walkPath)
				if err_5 != nil {
					return err_5
				}
//line /home/user/kukicha/stdlib/container/container.kuki:663
				defer f.Close()
//line /home/user/kukicha/stdlib/container/container.kuki:664
				_, err := io.Copy(tw, f)
				if err != nil {
					return err
				}
			}
//line /home/user/kukicha/stdlib/container/container.kuki:665
			return nil
		})
		if err_43 != nil {
			err_43 = fmt.Errorf("container copy to walk: %w", err_43)
			return nil, err_43
		}
	} else {
//line /home/user/kukicha/stdlib/container/container.kuki:668
		fi, err_44 := os.Stat(absSourcePath)
		if err_44 != nil {
			err_44 = fmt.Errorf("container copy to stat file: %w", err_44)
			return nil, err_44
		}
//line /home/user/kukicha/stdlib/container/container.kuki:669
		header, err_45 := tar.FileInfoHeader(fi, "")
		if err_45 != nil {
			err_45 = fmt.Errorf("container copy to header: %w", err_45)
			return nil, err_45
		}
//line /home/user/kukicha/stdlib/container/container.kuki:670
		header.Name = filepath.ToSlash(filepath.Base(absSourcePath))
//line /home/user/kukicha/stdlib/container/container.kuki:671
		err_46 := tw.WriteHeader(header)
		if err_46 != nil {
			err_46 = fmt.Errorf("container copy to write header: %w", err_46)
			return nil, err_46
		}
//line /home/user/kukicha/stdlib/container/container.kuki:672
		f, err_47 := os.Open(absSourcePath)
		if err_47 != nil {
			err_47 = fmt.Errorf("container copy to open: %w", err_47)
			return nil, err_47
		}
//line /home/user/kukicha/stdlib/container/container.kuki:673
		defer f.Close()
//line /home/user/kukicha/stdlib/container/container.kuki:674
		_, err := io.Copy(tw, f)
		if err != nil {
			err = fmt.Errorf("container copy to write file: %w", err)
			return nil, err
		}
	}
//line /home/user/kukicha/stdlib/container/container.kuki:676
	err_48 := tw.Close()
	if err_48 != nil {
		err_48 = fmt.Errorf("container copy to close tar: %w", err_48)
		return nil, err_48
	}
//line /home/user/kukicha/stdlib/container/container.kuki:677
	return &buf, nil
}

//line /home/user/kukicha/stdlib/container/container.kuki:681
func CopyFrom(engine Engine, containerID string, sourcePath string, destPath string, handles ...ctxpkg.Handle) error {
//line /home/user/kukicha/stdlib/container/container.kuki:682
	ctx := ctxpkg.Background()
//line /home/user/kukicha/stdlib/container/container.kuki:683
	if len(handles) > 0 {
//line /home/user/kukicha/stdlib/container/container.kuki:684
		ctx = handles[0]
	}
//line /home/user/kukicha/stdlib/container/container.kuki:685
	return copyFromWithContext(engine, ctx, containerID, sourcePath, destPath)
}

//line /home/user/kukicha/stdlib/container/container.kuki:688
func copyFromWithContext(engine Engine, ctx ctxpkg.Handle, containerID string, sourcePath string, destPath string) error {
//line /home/user/kukicha/stdlib/container/container.kuki:689
	reader, _, err := engine.cli.CopyFromContainer(ctxpkg.Value(ctx), containerID, sourcePath)
	if err != nil {
		err = fmt.Errorf("container copy from: %w", err)
		return err
	}
//line /home/user/kukicha/stdlib/container/container.kuki:690
	defer reader.Close()
//line /home/user/kukicha/stdlib/container/container.kuki:691
	err_49 := os.MkdirAll(destPath, 493)
	if err_49 != nil {
		err_49 = fmt.Errorf("container copy from mkdir: %w", err_49)
		return err_49
	}
//line /home/user/kukicha/stdlib/container/container.kuki:692
	err_50 := extractTar(reader, destPath)
	if err_50 != nil {
		err_50 = fmt.Errorf("container copy from extract: %w", err_50)
		return err_50
	}
//line /home/user/kukicha/stdlib/container/container.kuki:693
	return nil
}

//line /home/user/kukicha/stdlib/container/container.kuki:697
func CopyTo(engine Engine, containerID string, sourcePath string, destPath string, handles ...ctxpkg.Handle) error {
//line /home/user/kukicha/stdlib/container/container.kuki:698
	ctx := ctxpkg.Background()
//line /home/user/kukicha/stdlib/container/container.kuki:699
	if len(handles) > 0 {
//line /home/user/kukicha/stdlib/container/container.kuki:700
		ctx = handles[0]
	}
//line /home/user/kukicha/stdlib/container/container.kuki:701
	return copyToWithContext(engine, ctx, containerID, sourcePath, destPath)
}

//line /home/user/kukicha/stdlib/container/container.kuki:704
func copyToWithContext(engine Engine, ctx ctxpkg.Handle, containerID string, sourcePath string, destPath string) error {
//line /home/user/kukicha/stdlib/container/container.kuki:705
	archive, err_51 := createTarFromPath(sourcePath)
	if err_51 != nil {
		return err_51
	}
//line /home/user/kukicha/stdlib/container/container.kuki:706
	copyOpts := dockercontainer.CopyToContainerOptions{AllowOverwriteDirWithFile: true}
//line /home/user/kukicha/stdlib/container/container.kuki:707
	err_52 := engine.cli.CopyToContainer(ctxpkg.Value(ctx), containerID, destPath, archive, copyOpts)
	if err_52 != nil {
		err_52 = fmt.Errorf("container copy to: %w", err_52)
		return err_52
	}
//line /home/user/kukicha/stdlib/container/container.kuki:708
	return nil
}
