// Generated by Kukicha (requires Go 1.26+)

package template_test

import (
	"github.com/kukichalang/kukicha/stdlib/template"
	"github.com/kukichalang/kukicha/stdlib/test"
	"testing"
)

//line stdlib/template/template_test.kuki:10
type RenderSimpleCase struct {
	name     string
	template string
	data     map[string]any
	want     string
	wantErr  bool
}

//line stdlib/template/template_test.kuki:17
func TestRenderSimple(t *testing.T) {
//line stdlib/template/template_test.kuki:18
	cases := []RenderSimpleCase{RenderSimpleCase{name: "renders template with data", template: "Hello {{.Name}}", data: map[string]any{"Name": "Ari"}, want: "Hello Ari", wantErr: false}, RenderSimpleCase{name: "renders empty template", template: "", data: map[string]any{}, want: "", wantErr: false}, RenderSimpleCase{name: "invalid template returns error", template: "{{", data: map[string]any{}, want: "", wantErr: true}}
//line stdlib/template/template_test.kuki:42
	for _, tc := range cases {
//line stdlib/template/template_test.kuki:43
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/template/template_test.kuki:44
			result, err := template.RenderSimple(tc.template, tc.data)
//line stdlib/template/template_test.kuki:45
			if tc.wantErr {
//line stdlib/template/template_test.kuki:46
				test.AssertError(t, err)
			} else {
//line stdlib/template/template_test.kuki:48
				test.AssertNoError(t, err)
//line stdlib/template/template_test.kuki:49
				test.AssertEqual(t, result, tc.want)
			}
		})
	}
}

//line stdlib/template/template_test.kuki:53
type ExecuteCase struct {
	name     string
	template string
	data     map[string]any
	want     string
	wantErr  bool
}

//line stdlib/template/template_test.kuki:60
func TestExecute(t *testing.T) {
//line stdlib/template/template_test.kuki:61
	cases := []ExecuteCase{ExecuteCase{name: "renders template via builder", template: "Greetings {{.Name}}!", data: map[string]any{"Name": "Eve"}, want: "Greetings Eve!", wantErr: false}, ExecuteCase{name: "empty template", template: "", data: map[string]any{}, want: "", wantErr: false}, ExecuteCase{name: "invalid builder template returns error", template: "{{", data: map[string]any{}, want: "", wantErr: true}}
//line stdlib/template/template_test.kuki:85
	for _, tc := range cases {
//line stdlib/template/template_test.kuki:86
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/template/template_test.kuki:87
			td := template.Parse(tc.template)
//line stdlib/template/template_test.kuki:88
			td = template.Data(td, tc.data)
//line stdlib/template/template_test.kuki:89
			final, err := template.Execute(td)
//line stdlib/template/template_test.kuki:90
			if tc.wantErr {
//line stdlib/template/template_test.kuki:91
				test.AssertError(t, err)
			} else {
//line stdlib/template/template_test.kuki:93
				test.AssertNoError(t, err)
//line stdlib/template/template_test.kuki:94
				test.AssertEqual(t, final, tc.want)
			}
		})
	}
}

//line stdlib/template/template_test.kuki:98
type HTMLRenderSimpleCase struct {
	name     string
	template string
	data     map[string]any
	want     string
	wantErr  bool
}

//line stdlib/template/template_test.kuki:105
func TestHTMLRenderSimple(t *testing.T) {
//line stdlib/template/template_test.kuki:106
	cases := []HTMLRenderSimpleCase{HTMLRenderSimpleCase{name: "escapes HTML content", template: "<b>{{.Value}}</b>", data: map[string]any{"Value": "<script>"}, want: "<b>&lt;script&gt;</b>", wantErr: false}, HTMLRenderSimpleCase{name: "renders plain text", template: "Hello {{.Name}}", data: map[string]any{"Name": "World"}, want: "Hello World", wantErr: false}, HTMLRenderSimpleCase{name: "invalid html template returns error", template: "{{", data: map[string]any{}, want: "", wantErr: true}}
//line stdlib/template/template_test.kuki:130
	for _, tc := range cases {
//line stdlib/template/template_test.kuki:131
		t.Run(tc.name, func(t *testing.T) {
//line stdlib/template/template_test.kuki:132
			result, err := template.HTMLRenderSimple(tc.template, tc.data)
//line stdlib/template/template_test.kuki:133
			if tc.wantErr {
//line stdlib/template/template_test.kuki:134
				test.AssertError(t, err)
			} else {
//line stdlib/template/template_test.kuki:136
				test.AssertNoError(t, err)
//line stdlib/template/template_test.kuki:137
				test.AssertEqual(t, result, tc.want)
			}
		})
	}
}
