// Generated by Kukicha v0.0.14 (requires Go 1.26+)

package must_test

import (
	"github.com/duber000/kukicha/stdlib/must"
	kukistring "github.com/duber000/kukicha/stdlib/string"
	"github.com/duber000/kukicha/stdlib/test"
	"os"
	"testing"
)

//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/must/must_test.kuki:12
type DoCase struct {
	name  string
	value string
	err   error
	want  string
}

//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/must/must_test.kuki:18
func TestDo(t *testing.T) {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/must/must_test.kuki:19
	cases := []DoCase{DoCase{name: "returns value when no error", value: "ok", err: nil, want: "ok"}}
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/must/must_test.kuki:27
	for _, tc := range cases {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/must/must_test.kuki:28
		t.Run(tc.name, func(t *testing.T) {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/must/must_test.kuki:29
			got := must.Do(tc.value, tc.err)
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/must/must_test.kuki:30
			test.AssertEqual(t, got, tc.want)
		})
	}
}

//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/must/must_test.kuki:34
type OkCase struct {
	name      string
	err       error
	wantPanic bool
}

//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/must/must_test.kuki:39
func TestOk(t *testing.T) {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/must/must_test.kuki:40
	cases := []OkCase{OkCase{name: "succeeds when error empty", err: nil, wantPanic: false}}
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/must/must_test.kuki:47
	for _, tc := range cases {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/must/must_test.kuki:48
		t.Run(tc.name, func(t *testing.T) {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/must/must_test.kuki:49
			must.Ok(tc.err)
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/must/must_test.kuki:50
			test.AssertNoError(t, tc.err)
		})
	}
}

//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/must/must_test.kuki:54
type EnvCase struct {
	name     string
	envKey   string
	envValue string
	want     string
}

//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/must/must_test.kuki:60
func TestEnvHelpers(t *testing.T) {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/must/must_test.kuki:61
	cases := []EnvCase{EnvCase{name: "returns set env value", envKey: "MUST_TEST", envValue: "value", want: "value"}, EnvCase{name: "returns default when env missing", envKey: "MISSING_TEST", envValue: "", want: "default"}}
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/must/must_test.kuki:75
	for _, tc := range cases {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/must/must_test.kuki:76
		t.Run(tc.name, func(t *testing.T) {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/must/must_test.kuki:77
			if len(tc.envValue) > 0 {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/must/must_test.kuki:78
				os.Setenv(tc.envKey, tc.envValue)
			}
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/must/must_test.kuki:80
			if tc.want == "default" {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/must/must_test.kuki:81
				got := must.EnvOr(tc.envKey, "default")
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/must/must_test.kuki:82
				test.AssertEqual(t, got, "default")
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/must/must_test.kuki:83
				os.Unsetenv(tc.envKey)
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/must/must_test.kuki:84
				gotDefault := must.EnvOr(tc.envKey, "default")
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/must/must_test.kuki:85
				test.AssertEqual(t, gotDefault, "default")
			} else {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/must/must_test.kuki:87
				got := must.Env(tc.envKey)
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/must/must_test.kuki:88
				test.AssertEqual(t, got, tc.want)
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/must/must_test.kuki:89
				gotOr := must.EnvOr(tc.envKey, "default")
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/must/must_test.kuki:90
				test.AssertEqual(t, gotOr, tc.want)
			}
		})
	}
}

//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/must/must_test.kuki:94
type AssertionCase struct {
	name      string
	condition bool
	wantPanic bool
}

//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/must/must_test.kuki:99
func TestAssertionHelpers(t *testing.T) {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/must/must_test.kuki:100
	cases := []AssertionCase{AssertionCase{name: "True succeeds on true", condition: true, wantPanic: false}, AssertionCase{name: "False succeeds on false", condition: false, wantPanic: false}, AssertionCase{name: "NotEmpty succeeds on non-empty", condition: true, wantPanic: false}, AssertionCase{name: "NotNil succeeds on non-nil", condition: true, wantPanic: false}}
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/must/must_test.kuki:106
	for _, tc := range cases {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/must/must_test.kuki:107
		t.Run(tc.name, func(t *testing.T) {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/must/must_test.kuki:108
			if kukistring.Contains(tc.name, "True") {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/must/must_test.kuki:109
				must.True(tc.condition, "message")
			} else if kukistring.Contains(tc.name, "False") {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/must/must_test.kuki:111
				must.False(tc.condition, "message")
			} else if kukistring.Contains(tc.name, "Empty") {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/must/must_test.kuki:113
				must.NotEmpty("x", "name")
			} else if kukistring.Contains(tc.name, "Nil") {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/must/must_test.kuki:115
				must.NotNil("value", "value")
			}
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/must/must_test.kuki:116
			test.AssertNoError(t, nil)
		})
	}
}
