// Generated by Kukicha (requires Go 1.26+)

package must

import (
	"fmt"
	"github.com/kukichalang/kukicha/stdlib/env"
	"strconv"
)

//line stdlib/must/must.kuki:14
func Do(value any, err error) any {
//line stdlib/must/must.kuki:15
	if err != nil {
//line stdlib/must/must.kuki:16
		panic(fmt.Sprintf("must: %v", err))
	}
//line stdlib/must/must.kuki:17
	return value
}

//line stdlib/must/must.kuki:21
func DoMsg(value any, err error, message string) any {
//line stdlib/must/must.kuki:22
	if err != nil {
//line stdlib/must/must.kuki:23
		panic(fmt.Sprintf("%v: %v", message, err))
	}
//line stdlib/must/must.kuki:24
	return value
}

//line stdlib/must/must.kuki:28
func Ok(err error) {
//line stdlib/must/must.kuki:29
	if err != nil {
//line stdlib/must/must.kuki:30
		panic(fmt.Sprintf("must: %v", err))
	}
}

//line stdlib/must/must.kuki:34
func OkMsg(err error, message string) {
//line stdlib/must/must.kuki:35
	if err != nil {
//line stdlib/must/must.kuki:36
		panic(fmt.Sprintf("%v: %v", message, err))
	}
}

//line stdlib/must/must.kuki:42
func Env(key string) string {
//line stdlib/must/must.kuki:43
	value := env.GetOr(key, "")
//line stdlib/must/must.kuki:44
	if value == "" {
//line stdlib/must/must.kuki:45
		panic(fmt.Sprintf("must: environment variable %v is required but not set", key))
	}
//line stdlib/must/must.kuki:46
	return value
}

//line stdlib/must/must.kuki:51
func EnvOr(key string, defaultValue string) string {
//line stdlib/must/must.kuki:52
	value := env.GetOr(key, "")
//line stdlib/must/must.kuki:53
	if value == "" {
//line stdlib/must/must.kuki:54
		return defaultValue
	}
//line stdlib/must/must.kuki:55
	return value
}

//line stdlib/must/must.kuki:59
func EnvInt(key string) int {
//line stdlib/must/must.kuki:60
	value := env.GetOr(key, "")
//line stdlib/must/must.kuki:61
	if value == "" {
//line stdlib/must/must.kuki:62
		panic(fmt.Sprintf("must: environment variable %v is required but not set", key))
	}
//line stdlib/must/must.kuki:63
	val, err_1 := strconv.Atoi(value)
//line stdlib/must/must.kuki:63
	if err_1 != nil {
//line stdlib/must/must.kuki:63
		panic(fmt.Sprintf("must: environment variable %v must be a valid integer", key))
	}
//line stdlib/must/must.kuki:64
	return val
}

//line stdlib/must/must.kuki:69
func EnvIntOr(key string, defaultValue int) int {
//line stdlib/must/must.kuki:70
	value := env.GetOr(key, "")
//line stdlib/must/must.kuki:71
	if value == "" {
//line stdlib/must/must.kuki:72
		return defaultValue
	}
//line stdlib/must/must.kuki:73
	val, err_2 := strconv.Atoi(value)
//line stdlib/must/must.kuki:73
	if err_2 != nil {
//line stdlib/must/must.kuki:73
		panic(fmt.Sprintf("must: environment variable %v must be a valid integer", key))
	}
//line stdlib/must/must.kuki:74
	return val
}

//line stdlib/must/must.kuki:79
func EnvBool(key string) bool {
//line stdlib/must/must.kuki:80
	value := env.GetOr(key, "")
//line stdlib/must/must.kuki:81
	if value == "" {
//line stdlib/must/must.kuki:82
		panic(fmt.Sprintf("must: environment variable %v is required but not set", key))
	}
//line stdlib/must/must.kuki:83
	val, err_3 := env.ParseBool(value)
//line stdlib/must/must.kuki:83
	if err_3 != nil {
//line stdlib/must/must.kuki:83
		panic(fmt.Sprintf("must: environment variable %v must be a valid boolean", key))
	}
//line stdlib/must/must.kuki:84
	return val
}

//line stdlib/must/must.kuki:89
func EnvBoolOr(key string, defaultValue bool) bool {
//line stdlib/must/must.kuki:90
	value := env.GetOr(key, "")
//line stdlib/must/must.kuki:91
	if value == "" {
//line stdlib/must/must.kuki:92
		return defaultValue
	}
//line stdlib/must/must.kuki:93
	val, err_4 := env.ParseBool(value)
//line stdlib/must/must.kuki:93
	if err_4 != nil {
//line stdlib/must/must.kuki:93
		panic(fmt.Sprintf("must: environment variable %v must be a valid boolean", key))
	}
//line stdlib/must/must.kuki:94
	return val
}

//line stdlib/must/must.kuki:99
func EnvList(key string, separator string) []string {
//line stdlib/must/must.kuki:100
	value := env.GetOr(key, "")
//line stdlib/must/must.kuki:101
	if value == "" {
//line stdlib/must/must.kuki:102
		panic(fmt.Sprintf("must: environment variable %v is required but not set", key))
	}
//line stdlib/must/must.kuki:103
	return env.SplitAndTrim(value, separator)
}

//line stdlib/must/must.kuki:107
func EnvListOr(key string, separator string, defaultValue []string) []string {
//line stdlib/must/must.kuki:108
	value := env.GetOr(key, "")
//line stdlib/must/must.kuki:109
	if value == "" {
//line stdlib/must/must.kuki:110
		return defaultValue
	}
//line stdlib/must/must.kuki:111
	return env.SplitAndTrim(value, separator)
}

//line stdlib/must/must.kuki:118
func True(condition bool, message string) {
//line stdlib/must/must.kuki:119
	if !condition {
//line stdlib/must/must.kuki:120
		panic(fmt.Sprintf("assertion failed: %v", message))
	}
}

//line stdlib/must/must.kuki:124
func False(condition bool, message string) {
//line stdlib/must/must.kuki:125
	if condition {
//line stdlib/must/must.kuki:126
		panic(fmt.Sprintf("assertion failed: %v", message))
	}
}

//line stdlib/must/must.kuki:130
func NotEmpty(s string, name string) {
//line stdlib/must/must.kuki:131
	if s == "" {
//line stdlib/must/must.kuki:132
		panic(fmt.Sprintf("%v cannot be empty", name))
	}
}

//line stdlib/must/must.kuki:137
func NotNil(value any, name string) {
//line stdlib/must/must.kuki:138
	if value == nil {
//line stdlib/must/must.kuki:139
		panic(fmt.Sprintf("%v cannot be nil", name))
	}
}
