// Generated by Kukicha (requires Go 1.26+)

package db

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"reflect"
	strpkg "strings"
	"unicode"
)

//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:22
type Pool struct {
	conn *sql.DB
}

//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:26
type Row struct {
	row *sql.Row
}

//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:30
type Rows struct {
	rows *sql.Rows
}

//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:34
type Tx struct {
	tx *sql.Tx
}

//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:38
type TxOptions struct {
	isolationLevel string
	readOnly       bool
}

//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:48
func Open(driver string, connString string) (Pool, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:49
	conn, err_1 := sql.Open(driver, connString)
	if err_1 != nil {
		var _zero0 Pool
		return _zero0, err_1
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:50
	err_2 := conn.Ping()
	if err_2 != nil {
		var _zero0 Pool
		return _zero0, err_2
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:51
	pool := Pool{conn: conn}
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:52
	return pool, nil
}

//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:56
func Close(pool Pool) error {
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:57
	return pool.conn.Close()
}

//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:61
func Ping(pool Pool) error {
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:62
	return pool.conn.Ping()
}

//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:72
func Query(pool Pool, query string, args ...any) (Rows, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:73
	rows, err_3 := pool.conn.Query(query, args...)
	if err_3 != nil {
		var _zero0 Rows
		return _zero0, err_3
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:74
	result := Rows{rows: rows}
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:75
	return result, nil
}

//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:80
func QueryRow(pool Pool, query string, args ...any) Row {
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:81
	row := pool.conn.QueryRow(query, args...)
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:82
	return Row{row: row}
}

//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:88
func Exec(pool Pool, query string, args ...any) (int64, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:89
	result, err_4 := pool.conn.Exec(query, args...)
	if err_4 != nil {
		return 0, err_4
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:90
	affected, err_5 := result.RowsAffected()
	if err_5 != nil {
		return 0, err_5
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:91
	return affected, nil
}

//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:102
func ScanAll(rows Rows, sample any) (any, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:103
	defer rows.rows.Close()
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:105
	columns, err_6 := rows.rows.Columns()
	if err_6 != nil {
		var _zero0 any
		return _zero0, err_6
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:107
	sliceType := reflect.TypeOf(sample)
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:108
	elemType := sliceType.Elem()
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:109
	resultSlice := reflect.MakeSlice(sliceType, 0, 0)
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:111
	for rows.rows.Next() {
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:112
		elemPtr := reflect.New(elemType)
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:113
		fieldPtrs := structScanners(elemPtr.Elem(), elemType, columns)
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:114
		err_7 := rows.rows.Scan(fieldPtrs...)
		if err_7 != nil {
			var _zero0 any
			return _zero0, err_7
		}
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:115
		resultSlice = reflect.Append(resultSlice, elemPtr.Elem())
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:117
	err_8 := rows.rows.Err()
	if err_8 != nil {
		var _zero0 any
		return _zero0, err_8
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:118
	return resultSlice.Interface(), nil
}

//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:124
func ScanOne(rows Rows, sample any) (any, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:125
	defer rows.rows.Close()
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:127
	columns, err_9 := rows.rows.Columns()
	if err_9 != nil {
		var _zero0 any
		return _zero0, err_9
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:129
	elemType := reflect.TypeOf(sample)
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:130
	elemPtr := reflect.New(elemType)
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:132
	if !rows.rows.Next() {
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:133
		err_10 := rows.rows.Err()
		if err_10 != nil {
			var _zero0 any
			return _zero0, err_10
		}
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:134
		return sample, errors.New("db.ScanOne: no rows returned")
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:136
	fieldPtrs := structScanners(elemPtr.Elem(), elemType, columns)
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:137
	err_11 := rows.rows.Scan(fieldPtrs...)
	if err_11 != nil {
		var _zero0 any
		return _zero0, err_11
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:139
	if rows.rows.Next() {
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:140
		return sample, errors.New("db.ScanOne: more than one row returned")
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:142
	err_12 := rows.rows.Err()
	if err_12 != nil {
		var _zero0 any
		return _zero0, err_12
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:143
	return elemPtr.Elem().Interface(), nil
}

//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:147
func ScanRow(row Row, sample any) (any, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:148
	elemType := reflect.TypeOf(sample)
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:149
	elemPtr := reflect.New(elemType)
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:152
	numFields := elemType.NumField()
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:153
	scanners := make([]any, 0, numFields)
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:154
	for i := range numFields {
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:155
		field := elemType.Field(i)
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:156
		if field.IsExported() {
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:157
			scanners = append(scanners, &nullSafeField{target: elemPtr.Elem().Field(i)})
		}
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:159
	err_13 := row.row.Scan(scanners...)
	if err_13 != nil {
		var _zero0 any
		return _zero0, err_13
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:160
	return elemPtr.Elem().Interface(), nil
}

//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:165
func CloseRows(rows Rows) error {
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:166
	return rows.rows.Close()
}

//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:178
func Transaction(pool Pool, fn func(Tx) error) error {
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:179
	sqlTx, err_14 := pool.conn.Begin()
	if err_14 != nil {
		return err_14
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:180
	return finishTx(sqlTx, fn)
}

//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:185
func TransactionWith(pool Pool, opts TxOptions, fn func(Tx) error) error {
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:186
	txOpts := sql.TxOptions{ReadOnly: opts.readOnly}
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:187
	if opts.isolationLevel == "read_uncommitted" {
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:188
		txOpts.Isolation = sql.LevelReadUncommitted
	} else if opts.isolationLevel == "read_committed" {
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:190
		txOpts.Isolation = sql.LevelReadCommitted
	} else if opts.isolationLevel == "repeatable_read" {
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:192
		txOpts.Isolation = sql.LevelRepeatableRead
	} else if opts.isolationLevel == "serializable" {
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:194
		txOpts.Isolation = sql.LevelSerializable
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:196
	sqlTx, err_15 := pool.conn.BeginTx(context.Background(), &txOpts)
	if err_15 != nil {
		return err_15
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:197
	return finishTx(sqlTx, fn)
}

//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:201
func finishTx(sqlTx *sql.Tx, fn func(Tx) error) error {
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:202
	tx := Tx{tx: sqlTx}
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:203
	err := fn(tx)
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:204
	if err != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:205
		rbErr := sqlTx.Rollback()
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:206
		if rbErr != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:207
			return fmt.Errorf("tx rollback failed: %v; original: %v", rbErr, err)
		}
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:208
		return err
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:209
	return sqlTx.Commit()
}

//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:214
func TxQuery(tx Tx, query string, args ...any) (Rows, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:215
	rows, err_16 := tx.tx.Query(query, args...)
	if err_16 != nil {
		var _zero0 Rows
		return _zero0, err_16
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:216
	result := Rows{rows: rows}
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:217
	return result, nil
}

//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:222
func TxQueryRow(tx Tx, query string, args ...any) Row {
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:223
	row := tx.tx.QueryRow(query, args...)
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:224
	return Row{row: row}
}

//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:230
func TxExec(tx Tx, query string, args ...any) (int64, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:231
	result, err_17 := tx.tx.Exec(query, args...)
	if err_17 != nil {
		return 0, err_17
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:232
	affected, err_18 := result.RowsAffected()
	if err_18 != nil {
		return 0, err_18
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:233
	return affected, nil
}

//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:242
func Count(pool Pool, query string, args ...any) (int64, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:243
	row := pool.conn.QueryRow(query, args...)
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:244
	n := int64(0)
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:245
	err_19 := row.Scan(&n)
	if err_19 != nil {
		return 0, err_19
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:246
	return n, nil
}

//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:251
func Exists(pool Pool, query string, args ...any) (bool, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:252
	row := pool.conn.QueryRow(query, args...)
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:253
	dummy := 0
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:254
	err := row.Scan(&dummy)
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:255
	if err != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:256
		if err == sql.ErrNoRows {
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:257
			return false, nil
		}
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:258
		return false, err
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:259
	return true, nil
}

//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:267
type nullSafeField struct {
	target reflect.Value
}

//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:270
func (s *nullSafeField) Scan(value any) error {
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:271
	if value == nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:273
		return nil
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:275
	src := reflect.ValueOf(value)
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:276
	if src.Type().ConvertibleTo(s.target.Type()) {
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:277
		s.target.Set(src.Convert(s.target.Type()))
	} else {
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:280
		if s.target.Kind() == reflect.String {
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:281
			s.target.SetString(fmt.Sprintf("%v", value))
		} else {
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:283
			return fmt.Errorf("db: cannot convert %v to %v", src.Type(), s.target.Type())
		}
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:284
	return nil
}

//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:288
func structScanners(elem reflect.Value, elemType reflect.Type, columns []string) []any {
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:289
	numFields := elemType.NumField()
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:292
	tagMap := make(map[string]int)
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:293
	nameMap := make(map[string]int)
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:294
	snakeMap := make(map[string]int)
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:296
	for i := range numFields {
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:297
		field := elemType.Field(i)
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:298
		if !field.IsExported() {
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:299
			continue
		}
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:302
		tag := field.Tag.Get("json")
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:303
		if (tag != "") && (tag != "-") {
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:304
			parts := strpkg.Split(tag, ",")
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:305
			tagMap[parts[0]] = i
		}
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:308
		nameMap[strpkg.ToLower(field.Name)] = i
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:311
		snakeMap[camelToSnake(field.Name)] = i
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:314
	ptrs := make([]any, len(columns))
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:315
	for ci, col := range columns {
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:316
		lowerCol := strpkg.ToLower(col)
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:317
		ptrs[ci] = matchColumnToScanner(elem, tagMap, nameMap, snakeMap, col, lowerCol)
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:319
	return ptrs
}

//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:322
func matchColumnToScanner(elem reflect.Value, tagMap map[string]int, nameMap map[string]int, snakeMap map[string]int, col string, lowerCol string) any {
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:324
	idx, ok := tagMap[col]
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:325
	if ok {
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:326
		return &nullSafeField{target: elem.Field(idx)}
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:329
	idx, ok = nameMap[lowerCol]
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:330
	if ok {
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:331
		return &nullSafeField{target: elem.Field(idx)}
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:334
	idx, ok = snakeMap[lowerCol]
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:335
	if ok {
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:336
		return &nullSafeField{target: elem.Field(idx)}
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:339
	throwaway := ""
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:340
	return &throwaway
}

//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:343
func camelToSnake(s string) string {
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:344
	result := ""
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:345
	for i, r := range s {
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:346
		if unicode.IsUpper(r) {
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:347
			if i > 0 {
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:348
				result = (result + "_")
			}
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:349
			result = (result + strpkg.ToLower(fmt.Sprintf("%c", r)))
		} else {
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:351
			result = (result + fmt.Sprintf("%c", r))
		}
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/db/db.kuki:352
	return result
}
