// Generated by Kukicha v0.0.14 (requires Go 1.26+)

package json_test

import (
	"bytes"
	"github.com/duber000/kukicha/stdlib/json"
	"github.com/duber000/kukicha/stdlib/test"
	"testing"
)

//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:11
type Person struct {
	Name string `json:"name"`
	Age  int    `json:"age"`
}

//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:16
type MarshalCase struct {
	name string
}

//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:19
func TestMarshal(t *testing.T) {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:20
	cases := []MarshalCase{MarshalCase{name: "marshal person"}}
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:23
	for _, tc := range cases {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:24
		t.Run(tc.name, func(t *testing.T) {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:25
			p := Person{Name: "Alice", Age: 30}
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:26
			data, err := json.Marshal(p)
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:27
			test.AssertNoError(t, err)
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:28
			if len(data) == 0 {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:29
				t.Error("Expected non-empty JSON bytes")
			}
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:31
			data2, err2 := json.Marshal(p)
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:32
			test.AssertNoError(t, err2)
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:33
			test.AssertEqual(t, len(data), len(data2))
		})
	}
}

//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:37
type UnmarshalCase struct {
	name string
}

//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:40
func TestUnmarshal(t *testing.T) {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:41
	cases := []UnmarshalCase{UnmarshalCase{name: "unmarshal person"}}
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:44
	for _, tc := range cases {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:45
		t.Run(tc.name, func(t *testing.T) {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:46
			p := Person{Name: "Bob", Age: 25}
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:47
			data, marshalErr := json.Marshal(p)
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:48
			test.AssertNoError(t, marshalErr)
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:50
			result := *new(Person)
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:51
			unmarshalErr := json.Unmarshal(data, &result)
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:52
			test.AssertNoError(t, unmarshalErr)
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:53
			test.AssertEqual(t, result.Name, "Bob")
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:54
			test.AssertEqual(t, result.Age, 25)
		})
	}
}

//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:58
type RoundTripCase struct {
	name string
}

//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:61
func TestMarshalUnmarshalRoundTrip(t *testing.T) {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:62
	cases := []RoundTripCase{RoundTripCase{name: "round trip"}}
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:65
	for _, tc := range cases {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:66
		t.Run(tc.name, func(t *testing.T) {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:67
			original := Person{Name: "Charlie", Age: 42}
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:68
			data, err := json.Marshal(original)
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:69
			test.AssertNoError(t, err)
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:71
			restored := *new(Person)
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:72
			err2 := json.Unmarshal(data, &restored)
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:73
			test.AssertNoError(t, err2)
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:75
			test.AssertEqual(t, restored.Name, original.Name)
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:76
			test.AssertEqual(t, restored.Age, original.Age)
		})
	}
}

//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:80
type MarshalPrettyCase struct {
	name string
}

//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:83
func TestMarshalPretty(t *testing.T) {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:84
	cases := []MarshalPrettyCase{MarshalPrettyCase{name: "pretty print"}}
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:87
	for _, tc := range cases {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:88
		t.Run(tc.name, func(t *testing.T) {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:89
			p := Person{Name: "Dan", Age: 28}
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:90
			compact, err := json.Marshal(p)
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:91
			test.AssertNoError(t, err)
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:93
			pretty, err2 := json.MarshalPretty(p)
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:94
			test.AssertNoError(t, err2)
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:96
			if len(pretty) == 0 {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:97
				t.Error("Expected non-empty pretty JSON bytes")
			}
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:99
			if len(pretty) <= len(compact) {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:100
				t.Errorf("Expected pretty JSON (len=%v) to be longer than compact (len=%v)", len(pretty), len(compact))
			}
		})
	}
}

//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:104
type MarshalWriteCase struct {
	name string
}

//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:107
func TestMarshalWrite(t *testing.T) {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:108
	cases := []MarshalWriteCase{MarshalWriteCase{name: "write to buffer"}}
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:111
	for _, tc := range cases {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:112
		t.Run(tc.name, func(t *testing.T) {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:113
			p := Person{Name: "Eve", Age: 22}
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:114
			buf := bytes.Buffer{}
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:115
			err := json.MarshalWrite(&buf, p)
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:116
			test.AssertNoError(t, err)
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:117
			if buf.Len() == 0 {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:118
				t.Error("Expected non-empty buffer after MarshalWrite")
			}
		})
	}
}

//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:122
type UnmarshalReadCase struct {
	name string
}

//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:125
func TestUnmarshalRead(t *testing.T) {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:126
	cases := []UnmarshalReadCase{UnmarshalReadCase{name: "read from buffer"}}
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:129
	for _, tc := range cases {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:130
		t.Run(tc.name, func(t *testing.T) {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:131
			p := Person{Name: "Frank", Age: 35}
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:132
			buf := bytes.Buffer{}
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:133
			writeErr := json.MarshalWrite(&buf, p)
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:134
			test.AssertNoError(t, writeErr)
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:136
			result := *new(Person)
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:137
			readErr := json.UnmarshalRead(&buf, &result)
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:138
			test.AssertNoError(t, readErr)
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:139
			test.AssertEqual(t, result.Name, "Frank")
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:140
			test.AssertEqual(t, result.Age, 35)
		})
	}
}

//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:144
type EncodeCase struct {
	name string
}

//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:147
func TestEncode(t *testing.T) {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:148
	cases := []EncodeCase{EncodeCase{name: "encode to buffer"}}
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:151
	for _, tc := range cases {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:152
		t.Run(tc.name, func(t *testing.T) {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:153
			p := Person{Name: "Grace", Age: 29}
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:154
			buf := bytes.Buffer{}
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:155
			enc := json.NewEncoder(&buf)
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:156
			err := json.Encode(enc, p)
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:157
			test.AssertNoError(t, err)
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:158
			if buf.Len() == 0 {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:159
				t.Error("Expected non-empty buffer after Encode")
			}
		})
	}
}

//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:163
type DecodeCase struct {
	name string
}

//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:166
func TestDecode(t *testing.T) {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:167
	cases := []DecodeCase{DecodeCase{name: "decode from buffer"}}
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:170
	for _, tc := range cases {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:171
		t.Run(tc.name, func(t *testing.T) {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:172
			p := Person{Name: "Hank", Age: 40}
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:173
			buf := bytes.Buffer{}
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:174
			enc := json.NewEncoder(&buf)
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:175
			encErr := json.Encode(enc, p)
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:176
			test.AssertNoError(t, encErr)
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:178
			result := *new(Person)
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:179
			dec := json.NewDecoder(&buf)
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:180
			decErr := json.Decode(dec, &result)
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:181
			test.AssertNoError(t, decErr)
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:182
			test.AssertEqual(t, result.Name, "Hank")
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:183
			test.AssertEqual(t, result.Age, 40)
		})
	}
}

//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:187
type WithIndentCase struct {
	name string
}

//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:190
func TestWithIndent(t *testing.T) {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:191
	cases := []WithIndentCase{WithIndentCase{name: "indent encoding"}}
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:194
	for _, tc := range cases {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:195
		t.Run(tc.name, func(t *testing.T) {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:196
			p := Person{Name: "Iris", Age: 33}
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:197
			buf := bytes.Buffer{}
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:198
			enc := json.WithIndent(json.NewEncoder(&buf), "  ")
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:199
			err := json.Encode(enc, p)
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:200
			test.AssertNoError(t, err)
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:201
			if buf.Len() == 0 {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:202
				t.Error("Expected non-empty buffer after Encode with indent")
			}
		})
	}
}

//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:206
type UnmarshalInvalidCase struct {
	name string
}

//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:209
func TestUnmarshalInvalidJSON(t *testing.T) {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:210
	cases := []UnmarshalInvalidCase{UnmarshalInvalidCase{name: "invalid json"}}
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:213
	for _, tc := range cases {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:214
		t.Run(tc.name, func(t *testing.T) {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:215
			invalid := []byte("not valid json")
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:216
			result := *new(Person)
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:217
			err := json.Unmarshal(invalid, &result)
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/json/json_test.kuki:218
			test.AssertError(t, err)
		})
	}
}
