// Generated by Kukicha v0.0.14 (requires Go 1.26+)

package random_test

import (
	"github.com/duber000/kukicha/stdlib/random"
	"github.com/duber000/kukicha/stdlib/test"
	"testing"
)

//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/random/random_test.kuki:10
type LengthCase struct {
	name string
}

//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/random/random_test.kuki:13
func TestRandomStringLength(t *testing.T) {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/random/random_test.kuki:14
	cases := []LengthCase{LengthCase{name: "lengths"}}
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/random/random_test.kuki:17
	for _, tc := range cases {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/random/random_test.kuki:18
		t.Run(tc.name, func(t *testing.T) {
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/random/random_test.kuki:19
			s := random.String(10)
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/random/random_test.kuki:20
			test.AssertEqual(t, len(s), 10)
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/random/random_test.kuki:22
			zero := random.String(0)
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/random/random_test.kuki:23
			test.AssertEqual(t, zero, "")
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/random/random_test.kuki:25
			alpha := random.Alphanumeric(5)
//line /Users/tluker/repos/go/kukicha/.claude/worktrees/vigorous-liskov/stdlib/random/random_test.kuki:26
			test.AssertEqual(t, len(alpha), 5)
		})
	}
}
