// Generated by Kukicha (requires Go 1.26+)

package shell_test

import (
	"fmt"
	"github.com/kukichalang/kukicha/stdlib/shell"
	"github.com/kukichalang/kukicha/stdlib/slice"
	kukistring "github.com/kukichalang/kukicha/stdlib/string"
	"github.com/kukichalang/kukicha/stdlib/test"
	"testing"
)

//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:12
type ExecuteCase struct {
	name string
}

//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:15
func TestExecute(t *testing.T) {
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:16
	cases := []ExecuteCase{ExecuteCase{name: "basic"}}
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:18
	for _, tc := range cases {
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:19
		t.Run(tc.name, func(t *testing.T) {
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:20
			cmd := shell.New("echo", "hello world")
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:21
			result := shell.Execute(cmd)
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:23
			test.AssertTrue(t, shell.Success(result))
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:25
			output := string(shell.GetOutput(result))
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:26
			expected := "hello world\n"
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:27
			test.AssertEqual(t, output, expected)
		})
	}
}

//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:31
type ExecuteWithDirCase struct {
	name string
}

//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:34
func TestExecuteWithDir(t *testing.T) {
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:35
	cases := []ExecuteWithDirCase{ExecuteWithDirCase{name: "with dir"}}
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:37
	for _, tc := range cases {
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:38
		t.Run(tc.name, func(t *testing.T) {
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:39
			cmd := shell.Dir(shell.New("pwd"), "/tmp")
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:40
			result := shell.Execute(cmd)
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:42
			test.AssertTrue(t, shell.Success(result))
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:44
			output := string(shell.GetOutput(result))
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:45
			test.AssertTrue(t, kukistring.Contains(output, "tmp"))
		})
	}
}

//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:49
type ExecuteWithEnvCase struct {
	name string
}

//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:52
func TestExecuteWithEnv(t *testing.T) {
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:53
	cases := []ExecuteWithEnvCase{ExecuteWithEnvCase{name: "with env"}}
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:55
	for _, tc := range cases {
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:56
		t.Run(tc.name, func(t *testing.T) {
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:57
			cmd := shell.Env(shell.New("sh", "-c", "echo $TEST_VAR"), "TEST_VAR", "hello")
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:58
			result := shell.Execute(cmd)
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:60
			test.AssertTrue(t, shell.Success(result))
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:62
			output := string(shell.GetOutput(result))
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:63
			test.AssertTrue(t, kukistring.Contains(output, "hello"))
		})
	}
}

//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:67
type ExecuteFailedCase struct {
	name string
}

//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:70
func TestExecuteFailed(t *testing.T) {
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:71
	cases := []ExecuteFailedCase{ExecuteFailedCase{name: "failed"}}
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:73
	for _, tc := range cases {
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:74
		t.Run(tc.name, func(t *testing.T) {
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:75
			cmd := shell.New("false")
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:76
			result := shell.Execute(cmd)
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:78
			test.AssertFalse(t, shell.Success(result))
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:80
			exitCode := shell.ExitCode(result)
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:81
			if exitCode == 0 {
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:82
				t.Errorf("Expected non-zero exit code, got %v", exitCode)
			}
		})
	}
}

//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:86
type WhichCase struct {
	name string
}

//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:89
func TestWhich(t *testing.T) {
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:90
	cases := []WhichCase{WhichCase{name: "which"}}
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:92
	for _, tc := range cases {
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:93
		t.Run(tc.name, func(t *testing.T) {
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:94
			test.AssertTrue(t, shell.Which("ls"))
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:95
			test.AssertFalse(t, shell.Which("nonexistent-command-xyz"))
		})
	}
}

//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:99
type ArgsCase struct {
	name     string
	initial  []string
	extra    []string
	expected string
}

//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:105
func TestArgs(t *testing.T) {
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:106
	cases := []ArgsCase{ArgsCase{name: "append single arg", initial: []string{"--repo", "foo"}, extra: []string{"--verbose"}, expected: "hello world\n"}, ArgsCase{name: "append multiple args", initial: []string{}, extra: []string{"--foo", "bar"}, expected: "hello world\n"}}
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:108
	for _, tc := range cases {
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:109
		t.Run(tc.name, func(t *testing.T) {
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:110
			cmd := shell.New("echo", tc.initial...)
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:111
			cmd = shell.Args(cmd, tc.extra...)
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:112
			allArgs := []string{}
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:113
			allArgs = append(allArgs, tc.initial...)
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:114
			allArgs = append(allArgs, tc.extra...)
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:115
			result := shell.Execute(cmd)
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:116
			test.AssertTrue(t, shell.Success(result))
		})
	}
}

//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:120
type FlagIfCase struct {
	name           string
	condition      bool
	flag           string
	expectContains string
	expectMissing  string
}

//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:127
func TestFlagIf(t *testing.T) {
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:128
	cases := []FlagIfCase{FlagIfCase{name: "condition true adds flag", condition: true, flag: "--verbose", expectContains: "--verbose", expectMissing: ""}, FlagIfCase{name: "condition false skips flag", condition: false, flag: "--verbose", expectContains: "", expectMissing: "--verbose"}}
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:130
	for _, tc := range cases {
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:131
		t.Run(tc.name, func(t *testing.T) {
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:132
			cmd := shell.FlagIf(shell.New("echo", "hello"), tc.condition, tc.flag)
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:134
			preview := shell.Preview(cmd)
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:135
			if tc.expectContains != "" {
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:136
				test.AssertTrue(t, kukistring.Contains(preview, tc.expectContains))
			}
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:137
			if tc.expectMissing != "" {
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:138
				test.AssertFalse(t, kukistring.Contains(preview, tc.expectMissing))
			}
		})
	}
}

//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:142
type FlagIfMultiArgCase struct {
	name string
}

//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:145
func TestFlagIfMultiArg(t *testing.T) {
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:146
	cases := []FlagIfMultiArgCase{FlagIfMultiArgCase{name: "multi-arg flag"}}
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:148
	for _, tc := range cases {
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:149
		t.Run(tc.name, func(t *testing.T) {
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:150
			cmd := shell.FlagIf(shell.FlagIf(shell.New("gh", "release", "create"), true, "--target", "main"), false, "--draft")
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:154
			preview := shell.Preview(cmd)
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:155
			test.AssertTrue(t, kukistring.Contains(preview, "--target main"))
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:156
			test.AssertFalse(t, kukistring.Contains(preview, "--draft"))
		})
	}
}

//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:160
type PreviewCase struct {
	name     string
	cmdName  string
	args     []string
	expected string
}

//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:166
func TestPreview(t *testing.T) {
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:167
	cases := []PreviewCase{PreviewCase{name: "simple command", cmdName: "echo", args: []string{"hello"}, expected: "echo hello"}, PreviewCase{name: "no args", cmdName: "ls", args: []string{}, expected: "ls"}, PreviewCase{name: "multiple args", cmdName: "gh", args: []string{"release", "create", "v1.0.0", "--repo", "org/repo"}, expected: "gh release create v1.0.0 --repo org/repo"}}
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:169
	for _, tc := range cases {
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:170
		t.Run(tc.name, func(t *testing.T) {
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:171
			cmd := shell.New(tc.cmdName, tc.args...)
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:172
			got := shell.Preview(cmd)
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:173
			test.AssertEqual(t, got, tc.expected)
		})
	}
}

//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:177
type EnvCase struct {
	name string
}

//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:180
func TestEnv(t *testing.T) {
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:181
	cases := []EnvCase{EnvCase{name: "env operations"}}
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:183
	for _, tc := range cases {
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:184
		t.Run(tc.name, func(t *testing.T) {
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:185
			key := "KUKICHA_TEST_VAR"
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:186
			val := "test_value"
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:188
			err := shell.Setenv(key, val)
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:189
			test.AssertNoError(t, err)
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:191
			got := shell.Getenv(key)
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:192
			test.AssertEqual(t, got, val)
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:194
			envs := shell.Environ()
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:195
			test.AssertTrue(t, slice.Contains(envs, fmt.Sprintf("%v=%v", key, val)))
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:197
			shell.Unsetenv(key)
//line /home/runner/work/kukicha/kukicha/stdlib/shell/shell_test.kuki:198
			test.AssertEqual(t, shell.Getenv(key), "")
		})
	}
}
