// Generated by Kukicha (requires Go 1.26+)

package sqlite

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"github.com/kukichalang/kukicha/stdlib/db"
	sqlite3 "github.com/ncruces/go-sqlite3"
	_ "github.com/ncruces/go-sqlite3/driver"
	strpkg "strings"
	"unicode"
)

//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:35
func Open(path string) (db.Pool, error) {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:36
	return db.Open("sqlite3", (("file:" + path) + "?_pragma=journal_mode(WAL)&_pragma=foreign_keys(ON)&_pragma=busy_timeout(5000)"))
}

//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:41
func OpenMemory() (db.Pool, error) {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:42
	return db.Open("sqlite3", "file::memory:?_pragma=foreign_keys(ON)")
}

//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:47
func OpenWith(path string, pragmas map[string]string) (db.Pool, error) {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:48
	parts := make([]string, 0, len(pragmas))
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:49
	for k, v := range pragmas {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:50
		parts = append(parts, fmt.Sprintf("_pragma=%s(%s)", k, v))
	}
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:51
	connStr := ("file:" + path)
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:52
	if len(parts) > 0 {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:53
		connStr = ((connStr + "?") + strpkg.Join(parts, "&"))
	}
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:54
	return db.Open("sqlite3", connStr)
}

//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:63
func Pragma(pool db.Pool, name string) (string, error) {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:64
	if !isValidPragmaName(name) {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:65
		return "", fmt.Errorf("sqlite.Pragma: invalid pragma name: %v", name)
	}
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:66
	rawDB := db.RawDB(pool)
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:67
	row := rawDB.QueryRow(fmt.Sprintf("PRAGMA %s", name))
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:68
	value := ""
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:69
	// kukicha: could not infer return count; use explicit capture if incorrect
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:69
	err_1 := row.Scan(&value)
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:69
	if err_1 != nil {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:69
		return "", err_1
	}
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:70
	return value, nil
}

//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:75
func SetPragma(pool db.Pool, name string, value string) error {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:76
	if !isValidPragmaName(name) {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:77
		return fmt.Errorf("sqlite.SetPragma: invalid pragma name: %v", name)
	}
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:78
	if !isValidPragmaValue(value) {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:79
		return fmt.Errorf("sqlite.SetPragma: invalid pragma value: %v", value)
	}
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:80
	rawDB := db.RawDB(pool)
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:81
	_, err := rawDB.Exec(fmt.Sprintf("PRAGMA %s = %s", name, value))
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:82
	return err
}

//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:91
func Tables(pool db.Pool) ([]string, error) {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:92
	rawDB := db.RawDB(pool)
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:93
	rows, err_2 := rawDB.Query("SELECT name FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%' ORDER BY name")
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:93
	if err_2 != nil {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:93
		return []string{}, err_2
	}
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:94
	defer rows.Close()
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:95
	names := make([]string, 0)
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:96
	for rows.Next() {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:97
		name := ""
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:98
		// kukicha: could not infer return count; use explicit capture if incorrect
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:98
		err_3 := rows.Scan(&name)
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:98
		if err_3 != nil {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:98
			return []string{}, err_3
		}
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:99
		names = append(names, name)
	}
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:100
	// kukicha: could not infer return count; use explicit capture if incorrect
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:100
	err_4 := rows.Err()
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:100
	if err_4 != nil {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:100
		return []string{}, err_4
	}
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:101
	return names, nil
}

//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:105
func TableExists(pool db.Pool, name string) (bool, error) {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:106
	return db.Exists(pool, "SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = ?", name)
}

//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:111
func IntegrityCheck(pool db.Pool) error {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:112
	rawDB := db.RawDB(pool)
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:113
	row := rawDB.QueryRow("PRAGMA integrity_check")
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:114
	result := ""
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:115
	// kukicha: could not infer return count; use explicit capture if incorrect
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:115
	err_5 := row.Scan(&result)
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:115
	if err_5 != nil {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:115
		return err_5
	}
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:116
	if result != "ok" {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:117
		return fmt.Errorf("sqlite.IntegrityCheck: %v", result)
	}
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:118
	return nil
}

//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:122
func Vacuum(pool db.Pool) error {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:123
	rawDB := db.RawDB(pool)
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:124
	_, err := rawDB.Exec("VACUUM")
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:125
	return err
}

//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:131
func Backup(pool db.Pool, destPath string) error {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:132
	rawDB := db.RawDB(pool)
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:133
	sqlConn, err_6 := rawDB.Conn(context.Background())
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:133
	if err_6 != nil {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:133
		return err_6
	}
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:134
	defer sqlConn.Close()
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:135
	return sqlConn.Raw(makeBackupFunc(destPath))
}

//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:139
func Version(pool db.Pool) (string, error) {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:140
	rawDB := db.RawDB(pool)
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:141
	row := rawDB.QueryRow("SELECT sqlite_version()")
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:142
	version := ""
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:143
	// kukicha: could not infer return count; use explicit capture if incorrect
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:143
	err_7 := row.Scan(&version)
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:143
	if err_7 != nil {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:143
		return "", err_7
	}
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:144
	return version, nil
}

//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:160
func BatchExec(pool db.Pool, query string, rows [][]any) (int64, error) {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:161
	total := int64(0)
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:162
	err := db.Transaction(pool, func(tx db.Tx) error {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:163
		for _, row := range rows {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:164
			n, err_1 := db.TxExec(tx, query, row...)
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:164
			if err_1 != nil {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:164
				return err_1
			}
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:165
			total = (total + n)
		}
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:166
		return nil
	})
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:169
	return total, err
}

//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:186
func CreateFunction(pool db.Pool, name string, nArgs int, fn func([]string) string) error {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:187
	rawDB := db.RawDB(pool)
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:188
	rawDB.SetMaxOpenConns(1)
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:189
	sqlConn, err_8 := rawDB.Conn(context.Background())
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:189
	if err_8 != nil {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:189
		return err_8
	}
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:190
	defer sqlConn.Close()
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:191
	return sqlConn.Raw(makeCreateFuncCallback(name, nArgs, fn))
}

//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:193
func makeScalarFunc(fn func([]string) string) sqlite3.ScalarFunction {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:194
	return func(ctx sqlite3.Context, args ...sqlite3.Value) {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:195
		strArgs := make([]string, len(args))
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:196
		for i, arg := range args {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:197
			strArgs[i] = arg.Text()
		}
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:198
		ctx.ResultText(fn(strArgs))
	}
}

//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:207
func Dump(pool db.Pool) (string, error) {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:208
	rawDB := db.RawDB(pool)
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:209
	b := strpkg.Builder{}
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:212
	schemaRows, err_9 := rawDB.Query("SELECT sql FROM sqlite_master WHERE sql IS NOT NULL ORDER BY CASE type WHEN 'table' THEN 1 WHEN 'view' THEN 2 WHEN 'index' THEN 3 WHEN 'trigger' THEN 4 END")
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:212
	if err_9 != nil {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:212
		return "", err_9
	}
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:213
	defer schemaRows.Close()
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:214
	for schemaRows.Next() {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:215
		sqlText := ""
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:216
		// kukicha: could not infer return count; use explicit capture if incorrect
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:216
		err_10 := schemaRows.Scan(&sqlText)
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:216
		if err_10 != nil {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:216
			return "", err_10
		}
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:217
		b.WriteString(sqlText)
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:218
		b.WriteString(";\n")
	}
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:219
	// kukicha: could not infer return count; use explicit capture if incorrect
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:219
	err_11 := schemaRows.Err()
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:219
	if err_11 != nil {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:219
		return "", err_11
	}
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:222
	tables, err_12 := Tables(pool)
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:222
	if err_12 != nil {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:222
		return "", err_12
	}
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:223
	for _, table := range tables {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:224
		dumpErr := dumpTable(rawDB, &b, table)
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:225
		if dumpErr != nil {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:226
			return "", dumpErr
		}
	}
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:228
	return b.String(), nil
}

//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:230
func dumpTable(rawDB *sql.DB, b *strpkg.Builder, table string) error {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:231
	dataRows, err_13 := rawDB.Query(fmt.Sprintf("SELECT * FROM %s", quoteIdentifier(table)))
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:231
	if err_13 != nil {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:231
		return err_13
	}
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:232
	defer dataRows.Close()
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:233
	columns, err_14 := dataRows.Columns()
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:233
	if err_14 != nil {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:233
		return err_14
	}
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:235
	for dataRows.Next() {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:236
		values := make([]any, len(columns))
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:237
		ptrs := make([]any, len(columns))
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:238
		for i := range len(values) {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:239
			ptrs[i] = &values[i]
		}
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:240
		// kukicha: could not infer return count; use explicit capture if incorrect
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:240
		err_15 := dataRows.Scan(ptrs...)
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:240
		if err_15 != nil {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:240
			return err_15
		}
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:242
		b.WriteString(fmt.Sprintf("INSERT INTO %s VALUES(", quoteIdentifier(table)))
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:243
		for i, v := range values {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:244
			if i > 0 {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:245
				b.WriteString(", ")
			}
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:246
			b.WriteString(formatSQLValue(v))
		}
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:247
		b.WriteString(");\n")
	}
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:248
	return dataRows.Err()
}

//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:255
type rawConnector interface {
	Raw() *sqlite3.Conn
}

//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:258
func makeBackupFunc(destPath string) func(any) error {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:259
	return func(driverConn any) error {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:260
		rawer, ok := driverConn.(rawConnector)
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:261
		if !ok {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:262
			return errors.New("sqlite.Backup: driver does not support raw connection access")
		}
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:263
		return rawer.Raw().Backup("main", ("file:" + destPath))
	}
}

//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:265
func makeCreateFuncCallback(name string, nArgs int, fn func([]string) string) func(any) error {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:266
	return func(driverConn any) error {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:267
		rawer, ok := driverConn.(rawConnector)
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:268
		if !ok {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:269
			return errors.New("sqlite.CreateFunction: driver does not support raw connection access")
		}
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:270
		conn := rawer.Raw()
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:271
		return conn.CreateFunction(name, nArgs, sqlite3.DETERMINISTIC, makeScalarFunc(fn))
	}
}

//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:274
func isValidPragmaName(name string) bool {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:275
	if len(name) == 0 {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:276
		return false
	}
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:277
	for _, r := range name {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:278
		if (!unicode.IsLetter(r) && !unicode.IsDigit(r)) && (r != 95) {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:279
			return false
		}
	}
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:280
	return true
}

//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:284
func isValidPragmaValue(value string) bool {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:285
	if len(value) == 0 {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:286
		return false
	}
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:287
	v := value
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:288
	if v[0] == 45 {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:289
		v = v[1:]
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:290
		if len(v) == 0 {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:291
			return false
		}
	}
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:292
	for _, r := range v {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:293
		if (!unicode.IsLetter(r) && !unicode.IsDigit(r)) && (r != 95) {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:294
			return false
		}
	}
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:295
	return true
}

//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:298
func quoteIdentifier(name string) string {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:299
	return (("\"" + strpkg.ReplaceAll(name, "\"", "\"\"")) + "\"")
}

//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:302
func formatSQLValue(v any) string {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:303
	if v == nil {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:304
		return "NULL"
	}
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:305
	if //line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:305
	i, ok := v.(int64); ok {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:306
		return fmt.Sprintf("%d", i)
	}
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:307
	if //line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:307
	f, ok := v.(float64); ok {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:308
		return fmt.Sprintf("%g", f)
	}
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:309
	if //line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:309
	b, ok := v.(bool); ok {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:310
		if b {
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:311
			return "1"
		}
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:312
		return "0"
	}
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:314
	s := fmt.Sprintf("%v", v)
//line /home/runner/work/kukicha/kukicha/stdlib/sqlite/sqlite.kuki:315
	return (("'" + strpkg.ReplaceAll(s, "'", "''")) + "'")
}
