// Generated by Kukicha (requires Go 1.26+)

package main

import (
	"context"
	"errors"
	"fmt"
	"github.com/kukichalang/kukicha/stdlib/cli"
	"github.com/kukichalang/kukicha/stdlib/env"
	"github.com/kukichalang/kukicha/stdlib/fetch"
	"github.com/kukichalang/kukicha/stdlib/files"
	"github.com/kukichalang/kukicha/stdlib/input"
	jsonpkg "github.com/kukichalang/kukicha/stdlib/json"
	"github.com/kukichalang/kukicha/stdlib/llm"
	"github.com/kukichalang/kukicha/stdlib/mcp"
	strpkg "github.com/kukichalang/kukicha/stdlib/string"
	"io"
	"os"
	"path/filepath"
)

//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/agent.kuki:12
const defaultSystemPrompt = "You are a helpful assistant with access to a sandboxed Linux environment via tool calls. You can execute commands, read/write files, search, and manage the filesystem. Use these tools to help the user accomplish their goals. Be concise in your explanations but thorough in your tool usage."

//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/agent.kuki:14
type Agent struct {
	Bridge       *Bridge
	Config       Config
	SystemPrompt string
	MaxRounds    int
	OnText       func(string)
	OnToolCall   func(string, string)
	OnToolResult func(string, string)
}

//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/agent.kuki:23
type RunResult struct {
	Content  string
	Messages []llm.Message
	Rounds   int
}

//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/agent.kuki:28
func runAgent(ctx context.Context, a *Agent, userPrompt string, history []llm.Message) (*RunResult, error) {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/agent.kuki:29
	maxRounds := a.MaxRounds
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/agent.kuki:30
	if maxRounds == 0 {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/agent.kuki:31
		maxRounds = 15
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/agent.kuki:33
	messages := append([]llm.Message{}, history...)
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/agent.kuki:36
	if len(messages) == 0 {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/agent.kuki:37
		sys := a.SystemPrompt
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/agent.kuki:38
		if sys == "" {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/agent.kuki:39
			sys = defaultSystemPrompt
		}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/agent.kuki:40
		messages = append(messages, llm.Message{Role: "system", Content: sys})
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/agent.kuki:42
	messages = append(messages, llm.Message{Role: "user", Content: userPrompt})
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/agent.kuki:45
	tools := bridgeTools(a.Bridge)
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/agent.kuki:47
	for round := range maxRounds {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/agent.kuki:49
		client := llm.Messages(llm.APIKey(llm.Path(llm.BaseURL(llm.Model(llm.New(""), a.Config.Model), a.Config.WebUIURL), "/api/chat/completions"), a.Config.WebUIAPIKey), messages)
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/agent.kuki:52
		for _, t := range tools {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/agent.kuki:53
			client = llm.AddTool(client, t.Function.Name, t.Function.Description, t.Function.Parameters)
		}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/agent.kuki:56
		if a.OnText != nil {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/agent.kuki:57
			client = llm.Stream(client, a.OnText)
		}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/agent.kuki:59
		if len(tools) > 0 {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/agent.kuki:60
			client = llm.ToolChoiceAuto(client)
		}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/agent.kuki:63
		comp, err_1 := llm.SendRaw(client)
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/agent.kuki:63
		if err_1 != nil {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/agent.kuki:63
			return nil, fmt.Errorf("LLM request failed (round %v): %v", round, err_1)
		}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/agent.kuki:65
		content := llm.GetContent(comp)
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/agent.kuki:70
		if llm.HasToolCalls(comp) {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/agent.kuki:71
			toolCalls := llm.GetToolCalls(comp)
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/agent.kuki:74
			messages = append(messages, llm.Message{Role: "assistant", Content: content, ToolCalls: toolCalls})
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/agent.kuki:76
			for _, tc := range toolCalls {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/agent.kuki:77
				if a.OnToolCall != nil {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/agent.kuki:78
					a.OnToolCall(tc.Function.Name, tc.Function.Arguments)
				}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/agent.kuki:80
				toolResult, err_2 := callBridgeTool(ctx, a.Bridge, tc.Function.Name, tc.Function.Arguments)
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/agent.kuki:80
				if err_2 != nil {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/agent.kuki:80
					//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/agent.kuki:81
					toolResult = fmt.Sprintf("ERROR: %v", err_2)
				}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/agent.kuki:83
				if a.OnToolResult != nil {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/agent.kuki:84
					a.OnToolResult(tc.Function.Name, truncateStr(toolResult, 500))
				}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/agent.kuki:87
				messages = append(messages, llm.Message{Role: "tool", Content: toolResult, ToolCallID: tc.ID})
			}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/agent.kuki:89
			continue
		}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/agent.kuki:92
		return &RunResult{Content: content, Messages: messages, Rounds: (round + 1)}, nil
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/agent.kuki:94
	return nil, fmt.Errorf("agent hit max rounds (%v) without completing", maxRounds)
}

//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/agent.kuki:96
func truncateStr(s string, n int) string {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/agent.kuki:97
	if len(s) <= n {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/agent.kuki:98
		return s
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/agent.kuki:99
	return (s[:n] + "...")
}

//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:13
type ToolRoute struct {
	ServerName   string
	OriginalName string
}

//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:17
type BridgeServer struct {
	Name    string
	URL     string
	Session mcp.ClientSession
	Tools   []mcp.ClientTool
}

//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:23
type Bridge struct {
	Servers []*BridgeServer
	ToolMap map[string]ToolRoute
}

//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:27
func connectBridges(ctx context.Context, configs map[string]MCPServerConfig) (*Bridge, error) {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:28
	b := &Bridge{Servers: make([]*BridgeServer, 0), ToolMap: make(map[string]ToolRoute)}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:33
	for name, cfg := range configs {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:34
		session, err := connectOne(ctx, cfg)
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:35
		if err != nil {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:36
			continue
		}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:38
		server := &BridgeServer{Name: name, URL: cfg.URL, Session: session}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:45
		tools, toolsErr := mcp.ListTools(ctx, session)
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:46
		if toolsErr != nil {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:47
			mcp.Close(session)
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:48
			continue
		}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:50
		server.Tools = tools
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:51
		b.Servers = append(b.Servers, server)
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:54
		for _, t := range tools {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:55
			prefixed := fmt.Sprintf("%v_%v", name, sanitizeName(t.Name))
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:56
			b.ToolMap[prefixed] = ToolRoute{ServerName: name, OriginalName: t.Name}
		}
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:58
	return b, nil
}

//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:60
func connectOne(ctx context.Context, cfg MCPServerConfig) (mcp.ClientSession, error) {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:61
	if cfg.APIKey != "" {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:62
		return mcp.BearerConnect(ctx, cfg.URL, cfg.APIKey)
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:64
	return mcp.Connect(ctx, cfg.URL)
}

//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:66
func closeBridges(b *Bridge) error {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:67
	for _, s := range b.Servers {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:68
		mcp.Close(s.Session)
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:69
	return nil
}

//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:72
func bridgeTools(b *Bridge) []llm.Tool {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:73
	tools := make([]llm.Tool, 0, len(b.ToolMap))
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:75
	for _, s := range b.Servers {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:76
		for _, t := range s.Tools {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:77
			prefixed := fmt.Sprintf("%v_%v", s.Name, sanitizeName(t.Name))
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:78
			tools = append(tools, llm.Tool{Type: "function", Function: llm.ToolFunction{Name: prefixed, Description: fmt.Sprintf("(%v) %v", s.Name, t.Description), Parameters: t.InputSchema}})
		}
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:87
	return tools
}

//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:89
func bridgeToolCount(b *Bridge) int {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:90
	count := 0
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:91
	for _, s := range b.Servers {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:92
		count = (count + len(s.Tools))
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:93
	return count
}

//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:95
func bridgeToolNames(b *Bridge) []string {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:96
	names := make([]string, 0, len(b.ToolMap))
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:97
	for prefixed := range b.ToolMap {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:98
		names = append(names, prefixed)
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:99
	return names
}

//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:102
func callBridgeTool(ctx context.Context, b *Bridge, name string, argsJSON string) (string, error) {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:103
	route, ok := b.ToolMap[name]
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:104
	if !ok {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:105
		return "", fmt.Errorf("unknown tool: %v", name)
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:107
	found := false
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:108
	session := mcp.ClientSession{}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:109
	for _, s := range b.Servers {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:110
		if s.Name == route.ServerName {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:111
			session = s.Session
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:112
			found = true
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:113
			break
		}
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:115
	if !found {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:116
		return "", fmt.Errorf("server %v not connected", route.ServerName)
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:118
	args := make(map[string]any)
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:119
	if (argsJSON != "") && (argsJSON != "{}") {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:120
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:120
		err_3 := jsonpkg.UnmarshalString(argsJSON, &args)
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:120
		if err_3 != nil {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:120
			return "", fmt.Errorf("invalid tool arguments: %v", err_3)
		}
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:122
	result, err := mcp.CallTool(ctx, session, route.OriginalName, args)
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:123
	if err != nil {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:124
		return "", err
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:126
	if result.IsError {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:127
		return fmt.Sprintf("ERROR: %v", result.Text), nil
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:129
	return result.Text, nil
}

//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:131
func sanitizeName(name string) string {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:132
	result := strpkg.ReplaceAll(name, "/", "_")
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:133
	result = strpkg.ReplaceAll(result, " ", "_")
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:134
	result = strpkg.ReplaceAll(result, "-", "_")
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/bridge.kuki:135
	return result
}

//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/config.kuki:12
type MCPServerConfig struct {
	URL    string `json:"url"`
	APIKey string `json:"api_key"`
}

//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/config.kuki:16
type Config struct {
	WebUIURL          string                     `json:"webui_url"`
	WebUIAPIKey       string                     `json:"webui_api_key"`
	Model             string                     `json:"model"`
	MCPServers        map[string]MCPServerConfig `json:"mcp_servers"`
	TerminalMCPURL    string                     `json:"terminal_mcp_url"`
	TerminalMCPAPIKey string                     `json:"terminal_mcp_api_key"`
	MaxToolRounds     int                        `json:"max_tool_rounds"`
}

//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/config.kuki:25
func defaultConfigPath() string {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/config.kuki:26
	home, _ := os.UserHomeDir()
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/config.kuki:27
	return filepath.Join(home, ".config", "owui", "config.json")
}

//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/config.kuki:29
func loadConfig() Config {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/config.kuki:30
	cfg := Config{WebUIURL: "http://localhost:3000", TerminalMCPURL: "http://127.0.0.1:9000/mcp", Model: "llama3.1", MaxToolRounds: 15, MCPServers: make(map[string]MCPServerConfig)}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/config.kuki:33
	data, err_4 := files.ReadString(defaultConfigPath())
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/config.kuki:33
	if err_4 != nil {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/config.kuki:33
		data = ""
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/config.kuki:34
	if data != "" {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/config.kuki:35
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/config.kuki:35
		err_5 := jsonpkg.UnmarshalString(data, &cfg)
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/config.kuki:35
		if err_5 != nil {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/config.kuki:35

		}
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/config.kuki:37
	if cfg.MCPServers == nil {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/config.kuki:38
		cfg.MCPServers = make(map[string]MCPServerConfig)
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/config.kuki:41
	v := env.GetOr("OWUI_WEBUI_URL", "")
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/config.kuki:42
	if v != "" {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/config.kuki:43
		cfg.WebUIURL = v
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/config.kuki:45
	v = env.GetOr("OWUI_WEBUI_API_KEY", "")
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/config.kuki:46
	if v != "" {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/config.kuki:47
		cfg.WebUIAPIKey = v
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/config.kuki:49
	v = env.GetOr("OWUI_MODEL", "")
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/config.kuki:50
	if v != "" {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/config.kuki:51
		cfg.Model = v
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/config.kuki:53
	v = env.GetOr("OWUI_TERMINAL_MCP_URL", "")
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/config.kuki:54
	if v != "" {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/config.kuki:55
		cfg.TerminalMCPURL = v
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/config.kuki:57
	v = env.GetOr("OWUI_TERMINAL_MCP_API_KEY", "")
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/config.kuki:58
	if v != "" {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/config.kuki:59
		cfg.TerminalMCPAPIKey = v
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/config.kuki:61
	if cfg.TerminalMCPURL != "" {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/config.kuki:62
		cfg.MCPServers["terminal"] = MCPServerConfig{URL: cfg.TerminalMCPURL, APIKey: cfg.TerminalMCPAPIKey}
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/config.kuki:64
	return cfg
}

//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/config.kuki:66
func saveConfig(cfg Config) error {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/config.kuki:67
	path := defaultConfigPath()
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/config.kuki:68
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/config.kuki:68
	err_6 := os.MkdirAll(filepath.Dir(path), 0700)
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/config.kuki:68
	if err_6 != nil {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/config.kuki:68
		return fmt.Errorf("%v", err_6)
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/config.kuki:69
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/config.kuki:69
	err_7 := files.Write(cfg, path)
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/config.kuki:69
	if err_7 != nil {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/config.kuki:69
		return err_7
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/config.kuki:70
	return nil
}

//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/config.kuki:72
func validateConfig(cfg Config) error {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/config.kuki:73
	if cfg.WebUIAPIKey == "" {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/config.kuki:74
		return errors.New("Open WebUI API key required: set OWUI_WEBUI_API_KEY or run `owui configure`")
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/config.kuki:75
	return nil
}

//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:18
var version string = "dev"

//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:21
const ansiReset = "[0m"

//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:22
const ansiDim = "[2m"

//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:23
const ansiYellow = "[33m"

//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:24
const ansiBoldYellow = "[1;33m"

//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:25
const ansiBoldCyan = "[1;36m"

//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:26
const ansiRed = "[91m"

//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:27
const ansiGreen = "[32m"

//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:29
func dimFmt(s string) string {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:30
	return fmt.Sprintf("%v%v%v", ansiDim, s, ansiReset)
}

//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:32
func toolFmt(s string) string {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:33
	return fmt.Sprintf("%v%v%v", ansiYellow, s, ansiReset)
}

//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:35
func errFmt(s string) string {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:36
	return fmt.Sprintf("%v%v%v", ansiRed, s, ansiReset)
}

//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:38
func greenFmt(s string) string {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:39
	return fmt.Sprintf("%v%v%v", ansiGreen, s, ansiReset)
}

//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:41
func boldCyanFmt(s string) string {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:42
	return fmt.Sprintf("%v%v%v", ansiBoldCyan, s, ansiReset)
}

//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:44
func boldYellowFmt(s string) string {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:45
	return fmt.Sprintf("%v%v%v", ansiBoldYellow, s, ansiReset)
}

//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:49
func main() {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:50
	args := os.Args[1:]
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:53
	flagModel := ""
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:54
	flagChat := false
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:55
	flagRaw := false
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:56
	flagSystem := ""
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:57
	positional := make([]string, 0)
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:59
	i := 0
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:60
	for i < len(args) {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:61
		arg := args[i]
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:62
		if (arg == "-m") || (arg == "--model") {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:63
			i = (i + 1)
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:64
			if i < len(args) {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:65
				flagModel = args[i]
			}
		} else if strpkg.HasPrefix(arg, "--model=") {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:67
			flagModel = strpkg.TrimPrefix(arg, "--model=")
		} else if (arg == "-c") || (arg == "--chat") {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:69
			flagChat = true
		} else if arg == "--raw" {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:71
			flagRaw = true
		} else if (arg == "-S") || (arg == "--system") {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:73
			i = (i + 1)
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:74
			if i < len(args) {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:75
				flagSystem = args[i]
			}
		} else if strpkg.HasPrefix(arg, "--system=") {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:77
			flagSystem = strpkg.TrimPrefix(arg, "--system=")
		} else if (arg == "-h") || (arg == "--help") {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:79
			printUsage()
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:80
			return
		} else {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:82
			positional = append(positional, arg)
		}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:83
		i = (i + 1)
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:86
	if len(positional) > 0 {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:87
		cmd := positional[0]
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:88
		if cmd == "models" {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:89
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:89
			err_8 := cmdListModels()
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:89
			if err_8 != nil {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:89
				//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:90
				cli.Fatal(errFmt(fmt.Sprintf("error: %v", err_8)))
			}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:91
			return
		}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:92
		if cmd == "tools" {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:93
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:93
			err_9 := cmdListTools()
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:93
			if err_9 != nil {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:93
				//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:94
				cli.Fatal(errFmt(fmt.Sprintf("error: %v", err_9)))
			}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:95
			return
		}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:96
		if cmd == "health" {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:97
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:97
			err_10 := cmdHealth()
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:97
			if err_10 != nil {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:97
				//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:98
				cli.Fatal(errFmt(fmt.Sprintf("error: %v", err_10)))
			}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:99
			return
		}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:100
		if cmd == "configure" {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:101
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:101
			err_11 := cmdConfigure()
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:101
			if err_11 != nil {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:101
				//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:102
				cli.Fatal(errFmt(fmt.Sprintf("error: %v", err_11)))
			}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:103
			return
		}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:104
		if cmd == "version" {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:105
			fmt.Println(fmt.Sprintf("owui %v", version))
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:106
			return
		}
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:109
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:109
	err_12 := cmdRun(positional, flagModel, flagChat, flagRaw, flagSystem)
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:109
	if err_12 != nil {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:109
		//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:110
		cli.Fatal(errFmt(fmt.Sprintf("error: %v", err_12)))
	}
}

//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:114
func cmdRun(positional []string, flagModel string, flagChat bool, flagRaw bool, flagSystem string) error {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:115
	cfg := loadConfig()
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:116
	if flagModel != "" {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:117
		cfg.Model = flagModel
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:118
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:118
	err_13 := validateConfig(cfg)
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:118
	if err_13 != nil {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:118
		return err_13
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:120
	ctx := context.Background()
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:122
	bridge, err_14 := connectBridges(ctx, cfg.MCPServers)
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:122
	if err_14 != nil {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:122
		return fmt.Errorf("connecting to MCP servers: %v", err_14)
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:123
	defer closeBridges(bridge)
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:125
	if isTTYErr() {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:126
		fmt.Fprint(os.Stderr, fmt.Sprintf("%v %v\n", dimFmt("MCP connected:"), dimFmt(fmt.Sprintf("%v tools from configured servers", bridgeToolCount(bridge)))))
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:128
	a := &Agent{Bridge: bridge, Config: cfg, MaxRounds: cfg.MaxToolRounds}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:130
	if flagSystem != "" {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:131
		a.SystemPrompt = flagSystem
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:133
	prompt := gatherPrompt(positional)
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:136
	if flagChat {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:137
		runChat(ctx, a, prompt)
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:138
		return nil
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:141
	if prompt == "" {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:142
		return errors.New("no prompt provided — use -c for interactive chat")
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:144
	isTTY := isTTYOut()
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:146
	if isTTY {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:147
		a.OnToolCall = func(name string, toolArgs string) {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:148
			fmt.Fprint(os.Stderr, fmt.Sprintf("%v %v\n", toolFmt(fmt.Sprintf("-> %v", name)), dimFmt(truncateFmt(toolArgs, 80))))
		}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:150
		a.OnToolResult = func(name string, result string) {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:151
			fmt.Fprint(os.Stderr, fmt.Sprintf("%v %v\n", toolFmt(fmt.Sprintf("<- %v", name)), dimFmt(truncateFmt(result, 120))))
		}
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:153
	a.OnText = func(chunk string) {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:154
		if isTTY && !flagRaw {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:155
			fmt.Print(chunk)
		}
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:157
	result, err_15 := runAgent(ctx, a, prompt, []llm.Message{})
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:157
	if err_15 != nil {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:157
		return err_15
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:159
	if isTTY && !flagRaw {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:160
		fmt.Println()
	} else {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:162
		fmt.Print(result.Content)
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:164
	if isTTY {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:165
		fmt.Fprint(os.Stderr, fmt.Sprintf("%v\n", dimFmt(fmt.Sprintf("(%v tool rounds)", result.Rounds))))
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:167
	return nil
}

//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:171
type ModelEntry struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:175
type ModelsResponse struct {
	Data []ModelEntry `json:"data"`
}

//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:178
func cmdListModels() error {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:179
	cfg := loadConfig()
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:180
	if cfg.WebUIAPIKey == "" {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:181
		return errors.New("Open WebUI API key required")
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:183
	url := fmt.Sprintf("%v/api/models", strpkg.TrimRight(cfg.WebUIURL, "/"))
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:184
	// pipe step 1: fetch.Do(...)
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:184
	resp, err_17 := fetch.Do(fetch.BearerAuth(fetch.New(url), cfg.WebUIAPIKey))
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:184
	if err_17 != nil {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:184
		return err_17
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:186
	defer resp.Body.Close()
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:188
	if resp.StatusCode != 200 {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:189
		body, err_18 := fetch.Bytes(resp)
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:189
		if err_18 != nil {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:189
			return fmt.Errorf("HTTP %v", resp.StatusCode)
		}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:190
		return fmt.Errorf("HTTP %v: %v", resp.StatusCode, string(body))
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:192
	models := ModelsResponse{}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:193
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:193
	err_19 := jsonpkg.UnmarshalRead(resp.Body, &models)
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:193
	if err_19 != nil {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:193
		return err_19
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:195
	fmt.Println(boldCyanFmt("Available models:"))
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:196
	for _, m := range models.Data {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:197
		name := m.Name
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:198
		if name == "" {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:199
			name = m.ID
		}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:200
		fmt.Println(fmt.Sprintf("  %v %v", name, dimFmt(fmt.Sprintf("(%v)", m.ID))))
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:202
	return nil
}

//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:204
func cmdListTools() error {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:205
	cfg := loadConfig()
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:206
	ctx := context.Background()
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:208
	bridge, err_20 := connectBridges(ctx, cfg.MCPServers)
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:208
	if err_20 != nil {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:208
		return err_20
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:209
	defer closeBridges(bridge)
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:211
	fmt.Println(boldYellowFmt("Tools from configured servers:"))
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:212
	for _, name := range bridgeToolNames(bridge) {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:213
		fmt.Println(fmt.Sprintf("  %v", name))
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:215
	return nil
}

//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:217
func cmdHealth() error {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:218
	cfg := loadConfig()
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:219
	ctx := context.Background()
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:222
	fmt.Printf("Open WebUI  (%v)  ", cfg.WebUIURL)
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:223
	if cfg.WebUIAPIKey != "" {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:224
		url := fmt.Sprintf("%v/api/models", strpkg.TrimRight(cfg.WebUIURL, "/"))
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:225
		resp, err := fetch.Do(fetch.BearerAuth(fetch.New(url), cfg.WebUIAPIKey))
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:227
		if err != nil {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:228
			fmt.Println(errFmt("x"), err)
		} else {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:230
			resp.Body.Close()
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:231
			if resp.StatusCode == 200 {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:232
				fmt.Println(greenFmt("ok"))
			} else {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:234
				fmt.Println(errFmt("x"), fmt.Sprintf("HTTP %v", resp.StatusCode))
			}
		}
	} else {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:236
		fmt.Println(errFmt("x"), "no API key")
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:239
	for name, mcfg := range cfg.MCPServers {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:240
		fmt.Printf("%v MCP (%v)  ", name, mcfg.URL)
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:241
		m := make(map[string]MCPServerConfig)
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:242
		m[name] = mcfg
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:243
		bridge, err := connectBridges(ctx, m)
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:244
		if err != nil {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:245
			fmt.Println(errFmt("x"), err)
		} else {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:247
			fmt.Println(greenFmt("ok"), fmt.Sprintf("%v tools", bridgeToolCount(bridge)))
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:248
			closeBridges(bridge)
		}
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:250
	return nil
}

//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:252
func cmdConfigure() error {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:253
	cfg := loadConfig()
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:255
	v, err_21 := input.ReadLine(fmt.Sprintf("Open WebUI URL [%v]: ", cfg.WebUIURL))
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:255
	if err_21 != nil {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:255
		v = ""
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:256
	if v != "" {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:257
		cfg.WebUIURL = v
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:259
	var err_22 error
	v, err_22 = input.ReadLine(fmt.Sprintf("Open WebUI API Key [%v]: ", maskKey(cfg.WebUIAPIKey)))
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:259
	if err_22 != nil {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:259
		v = ""
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:260
	if v != "" {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:261
		cfg.WebUIAPIKey = v
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:263
	var err_23 error
	v, err_23 = input.ReadLine(fmt.Sprintf("Model [%v]: ", cfg.Model))
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:263
	if err_23 != nil {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:263
		v = ""
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:264
	if v != "" {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:265
		cfg.Model = v
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:267
	var err_24 error
	v, err_24 = input.ReadLine(fmt.Sprintf("terminal MCP URL [%v]: ", cfg.TerminalMCPURL))
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:267
	if err_24 != nil {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:267
		v = ""
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:268
	if v != "" {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:269
		cfg.TerminalMCPURL = v
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:271
	var err_25 error
	v, err_25 = input.ReadLine(fmt.Sprintf("terminal MCP API Key [%v]: ", maskKey(cfg.TerminalMCPAPIKey)))
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:271
	if err_25 != nil {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:271
		v = ""
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:272
	if v != "" {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:273
		cfg.TerminalMCPAPIKey = v
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:275
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:275
	err_26 := saveConfig(cfg)
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:275
	if err_26 != nil {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:275
		return err_26
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:276
	fmt.Println(greenFmt(fmt.Sprintf("Saved to %v", defaultConfigPath())))
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:277
	return nil
}

//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:281
func runChat(ctx context.Context, a *Agent, initialPrompt string) {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:282
	history := []llm.Message{}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:283
	prompt := initialPrompt
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:285
	fmt.Println(dimFmt(fmt.Sprintf("owui chat — model: %v — type 'exit' to quit", a.Config.Model)))
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:286
	fmt.Println("")
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:288
	for {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:289
		if prompt == "" {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:290
			var err_27 error
			prompt, err_27 = input.ReadLine(boldCyanFmt("you> "))
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:290
			if err_27 != nil {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:290
				break
			}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:291
			if (prompt == "exit") || (prompt == "quit") {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:292
				break
			}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:293
			if prompt == "" {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:294
				continue
			}
		}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:296
		a.OnToolCall = func(name string, toolArgs string) {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:297
			fmt.Fprint(os.Stderr, fmt.Sprintf("  %v %v\n", toolFmt(fmt.Sprintf("-> %v", name)), dimFmt(truncateFmt(toolArgs, 60))))
		}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:299
		a.OnToolResult = func(name string, result string) {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:300
			fmt.Fprint(os.Stderr, fmt.Sprintf("  %v %v\n", toolFmt(fmt.Sprintf("<- %v", name)), dimFmt(truncateFmt(result, 80))))
		}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:302
		a.OnText = nil
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:304
		result, err_28 := runAgent(ctx, a, prompt, history)
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:304
		if err_28 != nil {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:304
			//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:305
			fmt.Println(errFmt(fmt.Sprintf("error: %v", err_28)))
			//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:306
			fmt.Println("")
			//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:307
			prompt = ""
			//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:308
			continue
		}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:310
		fmt.Println("")
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:311
		fmt.Println(fmt.Sprintf("%v  %v", dimFmt(a.Config.Model), result.Content))
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:312
		if result.Rounds > 1 {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:313
			fmt.Println(dimFmt(fmt.Sprintf("  (%v rounds)", result.Rounds)))
		}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:314
		fmt.Println("")
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:316
		history = result.Messages
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:317
		prompt = ""
	}
}

//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:321
func gatherPrompt(args []string) string {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:322
	prompt := ""
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:325
	if !isTerminal(os.Stdin) && (len(args) == 0) {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:326
		data, _ := io.ReadAll(os.Stdin)
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:327
		prompt = strpkg.TrimSpace(string(data))
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:329
	if len(args) > 0 {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:330
		argText := strpkg.Join(args, " ")
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:331
		if prompt != "" {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:332
			prompt = fmt.Sprintf("%v\n\n%v", argText, prompt)
		} else {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:334
			prompt = argText
		}
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:336
	return prompt
}

//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:338
func isTerminal(f *os.File) bool {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:339
	info, err := f.Stat()
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:340
	if err != nil {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:341
		return false
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:342
	return ((info.Mode() & 0x200000) != 0)
}

//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:344
func isTTYOut() bool {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:345
	return isTerminal(os.Stdout)
}

//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:347
func isTTYErr() bool {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:348
	return isTerminal(os.Stderr)
}

//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:350
func maskKey(k string) string {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:351
	if len(k) < 8 {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:352
		return "--------"
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:353
	return fmt.Sprintf("%v...%v", k[:4], k[(len(k)-4):])
}

//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:355
func truncateFmt(s string, n int) string {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:356
	s = strpkg.ReplaceAll(s, "\n", " ")
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:357
	if len(s) <= n {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:358
		return s
	}
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:359
	return fmt.Sprintf("%v...", s[:n])
}

//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:361
func printUsage() {
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:362
	fmt.Println("owui — CLI agent: Open WebUI models + Open Terminal via MCP")
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:363
	fmt.Println("")
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:364
	fmt.Println("Usage:")
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:365
	fmt.Println("  owui [flags] [prompt]     Agent mode (one-shot or piped)")
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:366
	fmt.Println("  owui -c [prompt]          Interactive chat")
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:367
	fmt.Println("  owui models               List available models")
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:368
	fmt.Println("  owui tools                List MCP tools")
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:369
	fmt.Println("  owui health               Check connectivity")
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:370
	fmt.Println("  owui configure            Save configuration")
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:371
	fmt.Println("  owui version              Print version")
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:372
	fmt.Println("")
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:373
	fmt.Println("Flags:")
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:374
	fmt.Println("  -m, --model <model>       Override model")
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:375
	fmt.Println("  -c, --chat                Interactive chat mode")
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:376
	fmt.Println("  -S, --system <prompt>     Override system prompt")
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:377
	fmt.Println("  --raw                     Raw output (no formatting)")
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:378
	fmt.Println("")
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:379
	fmt.Println("Environment:")
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:380
	fmt.Println("  OWUI_WEBUI_URL            Open WebUI URL (default: http://localhost:3000)")
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:381
	fmt.Println("  OWUI_WEBUI_API_KEY        Open WebUI API key (required)")
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:382
	fmt.Println("  OWUI_MODEL                Model name (default: llama3.1)")
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:383
	fmt.Println("  OWUI_TERMINAL_MCP_URL     terminal MCP URL (default: http://127.0.0.1:9000/mcp)")
//line /var/home/tluker/repos/go/kukicha/examples/llm-cli/main.kuki:384
	fmt.Println("  OWUI_TERMINAL_MCP_API_KEY terminal MCP API key (optional, for authenticated servers)")
}
