// Generated by Kukicha v0.0.16 (requires Go 1.26+)

package datetime

import "time"

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:12
const ISO8601 = "iso8601"

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:13
const RFC3339 = "rfc3339"

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:14
const RFC3339Nano = "rfc3339nano"

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:15
const Date = "date"

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:16
const Time = "time"

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:17
const DateTime = "datetime"

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:18
const DateTimeT = "dateTimeT"

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:19
const Kitchen = "kitchen"

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:20
const Stamp = "stamp"

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:21
const RFC822 = "rfc822"

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:22
const RFC1123 = "rfc1123"

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:23
const ANSIC = "ansic"

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:24
const UnixDate = "unixdate"

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:31
func Format(t time.Time, format string) string {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:32
	layout := getLayout(format)
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:33
	return t.Format(layout)
}

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:38
func Parse(value string, format string) (time.Time, error) {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:39
	layout := getLayout(format)
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:40
	return time.Parse(layout, value)
}

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:44
func ParseInLocation(value string, format string, location string) (time.Time, error) {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:45
	layout := getLayout(format)
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:46
	loc, err_1 := time.LoadLocation(location)
	if err_1 != nil {
		var _zero0 time.Time
		return _zero0, err_1
	}
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:47
	return time.ParseInLocation(layout, value, loc)
}

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:51
func Now() time.Time {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:52
	return time.Now()
}

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:56
func Today() time.Time {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:57
	now := time.Now()
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:58
	return time.Date(now.Year(), now.Month(), now.Day(), 0, 0, 0, 0, now.Location())
}

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:62
func Tomorrow() time.Time {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:63
	return Today().AddDate(0, 0, 1)
}

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:67
func Yesterday() time.Time {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:68
	return Today().AddDate(0, 0, -1)
}

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:75
func Nanoseconds(n int64) time.Duration {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:76
	return time.Duration((n * 1))
}

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:80
func Microseconds(n int64) time.Duration {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:81
	return time.Duration((n * 1000))
}

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:85
func Milliseconds(n int64) time.Duration {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:86
	return time.Duration((n * 1000000))
}

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:90
func Seconds(n int64) time.Duration {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:91
	return time.Duration((n * 1000000000))
}

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:95
func Minutes(n int64) time.Duration {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:96
	return time.Duration((n * 60000000000))
}

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:100
func Hours(n int64) time.Duration {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:101
	return time.Duration((n * 3600000000000))
}

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:105
func Days(n int64) time.Duration {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:106
	return time.Duration((n * 86400000000000))
}

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:110
func Weeks(n int64) time.Duration {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:111
	return time.Duration((n * 604800000000000))
}

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:117
func AddDays(t time.Time, days int) time.Time {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:118
	return t.AddDate(0, 0, days)
}

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:122
func AddWeeks(t time.Time, weeks int) time.Time {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:123
	return t.AddDate(0, 0, (weeks * 7))
}

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:127
func AddMonths(t time.Time, months int) time.Time {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:128
	return t.AddDate(0, months, 0)
}

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:132
func AddYears(t time.Time, years int) time.Time {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:133
	return t.AddDate(years, 0, 0)
}

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:137
func SubDays(t time.Time, days int) time.Time {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:138
	return t.AddDate(0, 0, -days)
}

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:142
func SubWeeks(t time.Time, weeks int) time.Time {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:143
	return t.AddDate(0, 0, (-weeks * 7))
}

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:147
func SubMonths(t time.Time, months int) time.Time {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:148
	return t.AddDate(0, -months, 0)
}

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:152
func SubYears(t time.Time, years int) time.Time {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:153
	return t.AddDate(-years, 0, 0)
}

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:159
func IsBefore(t1 time.Time, t2 time.Time) bool {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:160
	return t1.Before(t2)
}

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:164
func IsAfter(t1 time.Time, t2 time.Time) bool {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:165
	return t1.After(t2)
}

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:169
func IsBetween(t time.Time, start time.Time, end time.Time) bool {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:170
	atOrAfterStart := t.Equal(start)
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:171
	afterStart := t.After(start)
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:172
	atOrBeforeEnd := t.Equal(end)
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:173
	beforeEnd := t.Before(end)
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:174
	return ((atOrAfterStart || afterStart) && (atOrBeforeEnd || beforeEnd))
}

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:178
func IsSameDay(t1 time.Time, t2 time.Time) bool {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:179
	y1 := t1.Year()
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:180
	m1 := t1.Month()
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:181
	d1 := t1.Day()
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:182
	y2 := t2.Year()
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:183
	m2 := t2.Month()
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:184
	d2 := t2.Day()
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:185
	return (((y1 == y2) && (m1 == m2)) && (d1 == d2))
}

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:189
func IsToday(t time.Time) bool {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:190
	return IsSameDay(t, time.Now())
}

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:194
func IsYesterday(t time.Time) bool {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:195
	return IsSameDay(t, Yesterday())
}

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:199
func IsTomorrow(t time.Time) bool {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:200
	return IsSameDay(t, Tomorrow())
}

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:204
func IsPast(t time.Time) bool {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:205
	return t.Before(time.Now())
}

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:209
func IsFuture(t time.Time) bool {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:210
	return t.After(time.Now())
}

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:216
func Year(t time.Time) int {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:217
	return t.Year()
}

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:221
func Month(t time.Time) int {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:222
	return int(t.Month())
}

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:226
func Day(t time.Time) int {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:227
	return t.Day()
}

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:231
func Hour(t time.Time) int {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:232
	return t.Hour()
}

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:236
func Minute(t time.Time) int {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:237
	return t.Minute()
}

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:241
func Second(t time.Time) int {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:242
	return t.Second()
}

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:246
func Weekday(t time.Time) int {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:247
	return int(t.Weekday())
}

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:251
func WeekdayName(t time.Time) string {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:252
	return t.Weekday().String()
}

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:258
func Unix(t time.Time) int64 {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:259
	return t.Unix()
}

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:263
func UnixMilli(t time.Time) int64 {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:264
	return t.UnixMilli()
}

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:268
func FromUnix(sec int64) time.Time {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:269
	return time.Unix(sec, 0)
}

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:273
func FromUnixMilli(msec int64) time.Time {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:274
	return time.UnixMilli(msec)
}

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:280
func Sleep(d time.Duration) {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:281
	time.Sleep(d)
}

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:285
func SleepSeconds(n int64) {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:286
	time.Sleep((time.Duration(n) * time.Second))
}

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:290
func SleepMilliseconds(n int64) {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:291
	time.Sleep((time.Duration(n) * time.Millisecond))
}

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:297
func InUTC(t time.Time) time.Time {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:298
	return t.UTC()
}

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:302
func InLocal(t time.Time) time.Time {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:303
	return t.Local()
}

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:307
func InLocation(t time.Time, location string) (time.Time, error) {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:308
	loc, err_2 := time.LoadLocation(location)
	if err_2 != nil {
		var _zero0 time.Time
		return _zero0, err_2
	}
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:309
	return t.In(loc), nil
}

//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:312
func getLayout(format string) string {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:313
	if (format == "iso8601") || (format == "ISO8601") {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:314
		return "2006-01-02T15:04:05Z07:00"
	}
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:315
	if (format == "rfc3339") || (format == "RFC3339") {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:316
		return time.RFC3339
	}
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:317
	if (format == "rfc3339nano") || (format == "RFC3339Nano") {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:318
		return time.RFC3339Nano
	}
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:319
	if format == "date" {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:320
		return "2006-01-02"
	}
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:321
	if format == "time" {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:322
		return "15:04:05"
	}
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:323
	if format == "datetime" {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:324
		return "2006-01-02 15:04:05"
	}
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:325
	if format == "dateTimeT" {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:326
		return "2006-01-02T15:04:05"
	}
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:327
	if format == "kitchen" {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:328
		return time.Kitchen
	}
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:329
	if format == "stamp" {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:330
		return time.Stamp
	}
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:331
	if format == "rfc822" {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:332
		return time.RFC822
	}
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:333
	if format == "rfc1123" {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:334
		return time.RFC1123
	}
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:335
	if format == "ansic" {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:336
		return time.ANSIC
	}
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:337
	if format == "unixdate" {
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:338
		return time.UnixDate
	}
//line /Users/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:340
	return format
}
