package main

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func brewMain(args []string) {
	brewFlags := flag.NewFlagSet("brew", flag.ContinueOnError)
	brewFlags.SetOutput(os.Stderr)
	stdout := brewFlags.Bool("stdout", false, "Write to stdout instead of file")
	removeKuki := brewFlags.Bool("remove-kuki", false, "Remove .kuki source files after brewing (requires confirmation)")
	if err := brewFlags.Parse(args); err != nil {
		fmt.Fprintln(os.Stderr, "Usage: kukicha brew [--stdout] [--remove-kuki] <file.kuki|dir>")
		os.Exit(1)
	}
	brewArgs := brewFlags.Args()
	if len(brewArgs) < 1 {
		fmt.Fprintln(os.Stderr, "Usage: kukicha brew [--stdout] [--remove-kuki] <file.kuki|dir>")
		os.Exit(1)
	}
	code := brewCommand(brewArgs[0], *stdout, *removeKuki)
	if code != 0 {
		os.Exit(code)
	}
}

func brewCommand(filename string, toStdout bool, removeKuki bool) int {
	// Compile with line directives stripped
	cr, err := compile(filename, "", "", true)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		return 1
	}

	// Strip the generated header comment
	clean := stripGeneratedHeader(cr.formatted)

	info, _ := os.Stat(filename)
	isDir := info != nil && info.IsDir()

	if toStdout {
		os.Stdout.Write(clean)
		return 0
	}

	// Determine output path
	var outputFile string
	if isDir {
		outputFile = filepath.Join(cr.absFile, "main.go")
	} else {
		outputFile = strings.TrimSuffix(cr.absFile, ".kuki") + ".go"
	}

	if err := os.WriteFile(outputFile, clean, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing output file: %v\n", err)
		return 1
	}
	fmt.Printf("Brewed %s → %s\n", filename, outputFile)

	if removeKuki {
		files, _, _ := resolveKukiFiles(filename)
		if isDir {
			files, _ = resolveKukiFilesRecursive(filename)
		}
		if !confirmRemoval(files) {
			fmt.Fprintln(os.Stderr, "Aborted. .kuki files were not removed.")
			return 0
		}
		for _, f := range files {
			if err := os.Remove(f); err != nil {
				fmt.Fprintf(os.Stderr, "Warning: could not remove %s: %v\n", f, err)
			} else {
				fmt.Printf("Removed %s\n", f)
			}
		}
	}
	return 0
}

// stripGeneratedHeader removes the "// Generated by Kukicha ..." first line
// and any immediately following blank line.
func stripGeneratedHeader(src []byte) []byte {
	s := string(src)
	after, found := strings.CutPrefix(s, "// Generated by Kukicha")
	if !found {
		return src
	}
	_, rest, ok := strings.Cut(after, "\n")
	if !ok {
		return src
	}
	// Strip one trailing blank line after the header
	rest = strings.TrimPrefix(rest, "\n")
	return []byte(rest)
}

// confirmRemoval prompts the user to confirm deletion of .kuki source files.
func confirmRemoval(files []string) bool {
	fmt.Fprintf(os.Stderr, "This will permanently remove %d .kuki file(s):\n", len(files))
	for _, f := range files {
		fmt.Fprintf(os.Stderr, "  %s\n", f)
	}
	fmt.Fprint(os.Stderr, "Continue? [y/N] ")
	scanner := bufio.NewScanner(os.Stdin)
	if scanner.Scan() {
		answer := strings.TrimSpace(strings.ToLower(scanner.Text()))
		return answer == "y" || answer == "yes"
	}
	return false
}
