// Generated by Kukicha (requires Go 1.26+)

package kube_test

import (
	"github.com/duber000/kukicha/stdlib/kube"
	"testing"
)

//line /var/home/tluker/repos/go/kukicha/stdlib/kube/kube_test.kuki:11
type NewConfigCase struct {
	name string
}

//line /var/home/tluker/repos/go/kukicha/stdlib/kube/kube_test.kuki:14
func TestNewConfig(t *testing.T) {
//line /var/home/tluker/repos/go/kukicha/stdlib/kube/kube_test.kuki:15
	cases := []NewConfigCase{NewConfigCase{name: "builder"}}
//line /var/home/tluker/repos/go/kukicha/stdlib/kube/kube_test.kuki:18
	for _, tc := range cases {
//line /var/home/tluker/repos/go/kukicha/stdlib/kube/kube_test.kuki:19
		t.Run(tc.name, func(t *testing.T) {
//line /var/home/tluker/repos/go/kukicha/stdlib/kube/kube_test.kuki:20
			cfg := kube.New()
//line /var/home/tluker/repos/go/kukicha/stdlib/kube/kube_test.kuki:21
			cfg = kube.Kubeconfig(cfg, "/tmp/test-kubeconfig")
//line /var/home/tluker/repos/go/kukicha/stdlib/kube/kube_test.kuki:22
			cfg = kube.Context(cfg, "test-context")
//line /var/home/tluker/repos/go/kukicha/stdlib/kube/kube_test.kuki:23
			_ = cfg
		})
	}
}

//line /var/home/tluker/repos/go/kukicha/stdlib/kube/kube_test.kuki:27
type InClusterCase struct {
	name string
}

//line /var/home/tluker/repos/go/kukicha/stdlib/kube/kube_test.kuki:30
func TestInCluster(t *testing.T) {
//line /var/home/tluker/repos/go/kukicha/stdlib/kube/kube_test.kuki:31
	cases := []InClusterCase{InClusterCase{name: "in cluster"}}
//line /var/home/tluker/repos/go/kukicha/stdlib/kube/kube_test.kuki:34
	for _, tc := range cases {
//line /var/home/tluker/repos/go/kukicha/stdlib/kube/kube_test.kuki:35
		t.Run(tc.name, func(t *testing.T) {
//line /var/home/tluker/repos/go/kukicha/stdlib/kube/kube_test.kuki:36
			cfg := kube.InCluster(kube.New())
//line /var/home/tluker/repos/go/kukicha/stdlib/kube/kube_test.kuki:37
			_ = cfg
		})
	}
}

//line /var/home/tluker/repos/go/kukicha/stdlib/kube/kube_test.kuki:41
type NamespaceCase struct {
	name string
}

//line /var/home/tluker/repos/go/kukicha/stdlib/kube/kube_test.kuki:44
func TestNamespace(t *testing.T) {
//line /var/home/tluker/repos/go/kukicha/stdlib/kube/kube_test.kuki:45
	cases := []NamespaceCase{NamespaceCase{name: "namespace scoping"}}
//line /var/home/tluker/repos/go/kukicha/stdlib/kube/kube_test.kuki:48
	for _, tc := range cases {
//line /var/home/tluker/repos/go/kukicha/stdlib/kube/kube_test.kuki:49
		t.Run(tc.name, func(t *testing.T) {
//line /var/home/tluker/repos/go/kukicha/stdlib/kube/kube_test.kuki:50
			c := kube.Cluster{}
//line /var/home/tluker/repos/go/kukicha/stdlib/kube/kube_test.kuki:51
			scoped := kube.Namespace(c, "production")
//line /var/home/tluker/repos/go/kukicha/stdlib/kube/kube_test.kuki:52
			_ = scoped
		})
	}
}
