// Generated by Kukicha v0.0.15 (requires Go 1.26+)

package sort

import (
	"slices"
	"sort"
)

//line /home/user/kukicha/stdlib/sort/sort.kuki:17
func Strings(items []string) []string {
//line /home/user/kukicha/stdlib/sort/sort.kuki:18
	result := slices.Clone(items)
//line /home/user/kukicha/stdlib/sort/sort.kuki:19
	slices.Sort(result)
//line /home/user/kukicha/stdlib/sort/sort.kuki:20
	return result
}

//line /home/user/kukicha/stdlib/sort/sort.kuki:24
func Ints(items []int) []int {
//line /home/user/kukicha/stdlib/sort/sort.kuki:25
	result := slices.Clone(items)
//line /home/user/kukicha/stdlib/sort/sort.kuki:26
	slices.Sort(result)
//line /home/user/kukicha/stdlib/sort/sort.kuki:27
	return result
}

//line /home/user/kukicha/stdlib/sort/sort.kuki:31
func Float64s(items []float64) []float64 {
//line /home/user/kukicha/stdlib/sort/sort.kuki:32
	result := slices.Clone(items)
//line /home/user/kukicha/stdlib/sort/sort.kuki:33
	slices.Sort(result)
//line /home/user/kukicha/stdlib/sort/sort.kuki:34
	return result
}

//line /home/user/kukicha/stdlib/sort/sort.kuki:40
func By(items []any, less func(any, any) bool) []any {
//line /home/user/kukicha/stdlib/sort/sort.kuki:41
	result := slices.Clone(items)
//line /home/user/kukicha/stdlib/sort/sort.kuki:42
	sort.SliceStable(result, func(i int, j int) bool { return less(result[i], result[j]) })
//line /home/user/kukicha/stdlib/sort/sort.kuki:43
	return result
}

//line /home/user/kukicha/stdlib/sort/sort.kuki:48
func Reverse(items []any, less func(any, any) bool) []any {
//line /home/user/kukicha/stdlib/sort/sort.kuki:49
	result := slices.Clone(items)
//line /home/user/kukicha/stdlib/sort/sort.kuki:50
	sort.SliceStable(result, func(i int, j int) bool { return less(result[j], result[i]) })
//line /home/user/kukicha/stdlib/sort/sort.kuki:51
	return result
}
