// Generated by Kukicha (requires Go 1.26+)

package sort_test

import (
	"github.com/kukichalang/kukicha/stdlib/sort"
	"github.com/kukichalang/kukicha/stdlib/test"
	"testing"
)

//line /home/user/kukicha/stdlib/sort/sort_test.kuki:10
type StringsCase struct {
	name  string
	input []string
	want  []string
}

//line /home/user/kukicha/stdlib/sort/sort_test.kuki:15
func TestStrings(t *testing.T) {
//line /home/user/kukicha/stdlib/sort/sort_test.kuki:16
	cases := []StringsCase{StringsCase{name: "already sorted", input: []string{"apple", "banana"}, want: []string{"apple", "banana"}}, StringsCase{name: "reverse order", input: []string{"banana", "apple"}, want: []string{"apple", "banana"}}, StringsCase{name: "single element", input: []string{"only"}, want: []string{"only"}}, StringsCase{name: "empty slice", input: []string{}, want: []string{}}}
//line /home/user/kukicha/stdlib/sort/sort_test.kuki:18
	for _, tc := range cases {
//line /home/user/kukicha/stdlib/sort/sort_test.kuki:19
		t.Run(tc.name, func(t *testing.T) {
//line /home/user/kukicha/stdlib/sort/sort_test.kuki:20
			got := sort.Strings(tc.input)
//line /home/user/kukicha/stdlib/sort/sort_test.kuki:21
			test.AssertEqual(t, len(got), len(tc.want))
//line /home/user/kukicha/stdlib/sort/sort_test.kuki:22
			for i := range len(got) {
//line /home/user/kukicha/stdlib/sort/sort_test.kuki:23
				test.AssertEqual(t, got[i], tc.want[i])
			}
		})
	}
}

//line /home/user/kukicha/stdlib/sort/sort_test.kuki:27
type IntsCase struct {
	name  string
	input []int
	want  []int
}

//line /home/user/kukicha/stdlib/sort/sort_test.kuki:32
func TestInts(t *testing.T) {
//line /home/user/kukicha/stdlib/sort/sort_test.kuki:33
	cases := []IntsCase{IntsCase{name: "unsorted", input: []int{3, 1, 2}, want: []int{1, 2, 3}}, IntsCase{name: "with negatives", input: []int{0, -1, 5}, want: []int{-1, 0, 5}}, IntsCase{name: "empty", input: []int{}, want: []int{}}}
//line /home/user/kukicha/stdlib/sort/sort_test.kuki:35
	for _, tc := range cases {
//line /home/user/kukicha/stdlib/sort/sort_test.kuki:36
		t.Run(tc.name, func(t *testing.T) {
//line /home/user/kukicha/stdlib/sort/sort_test.kuki:37
			got := sort.Ints(tc.input)
//line /home/user/kukicha/stdlib/sort/sort_test.kuki:38
			test.AssertEqual(t, len(got), len(tc.want))
//line /home/user/kukicha/stdlib/sort/sort_test.kuki:39
			for i := range len(got) {
//line /home/user/kukicha/stdlib/sort/sort_test.kuki:40
				test.AssertEqual(t, got[i], tc.want[i])
			}
		})
	}
}

//line /home/user/kukicha/stdlib/sort/sort_test.kuki:44
type ByCase struct {
	name string
}

//line /home/user/kukicha/stdlib/sort/sort_test.kuki:47
func TestBy(t *testing.T) {
//line /home/user/kukicha/stdlib/sort/sort_test.kuki:48
	cases := []ByCase{ByCase{name: "sort by length"}}
//line /home/user/kukicha/stdlib/sort/sort_test.kuki:50
	for _, tc := range cases {
//line /home/user/kukicha/stdlib/sort/sort_test.kuki:51
		t.Run(tc.name, func(t *testing.T) {
//line /home/user/kukicha/stdlib/sort/sort_test.kuki:52
			words := []string{"banana", "fig", "apple", "kiwi"}
//line /home/user/kukicha/stdlib/sort/sort_test.kuki:53
			sorted := sort.By(words, func(a string, b string) bool { return (len(a) < len(b)) })
//line /home/user/kukicha/stdlib/sort/sort_test.kuki:54
			test.AssertEqual(t, sorted[0], "fig")
		})
	}
}

//line /home/user/kukicha/stdlib/sort/sort_test.kuki:58
type ByKeyCase struct {
	name string
}

//line /home/user/kukicha/stdlib/sort/sort_test.kuki:61
func TestByKey(t *testing.T) {
//line /home/user/kukicha/stdlib/sort/sort_test.kuki:62
	cases := []ByKeyCase{ByKeyCase{name: "sort by string length"}}
//line /home/user/kukicha/stdlib/sort/sort_test.kuki:64
	for _, tc := range cases {
//line /home/user/kukicha/stdlib/sort/sort_test.kuki:65
		t.Run(tc.name, func(t *testing.T) {
//line /home/user/kukicha/stdlib/sort/sort_test.kuki:66
			words := []string{"banana", "fig", "apple", "kiwi"}
//line /home/user/kukicha/stdlib/sort/sort_test.kuki:67
			sorted := sort.ByKey(words, func(w string) int { return len(w) })
//line /home/user/kukicha/stdlib/sort/sort_test.kuki:68
			test.AssertEqual(t, sorted[0], "fig")
//line /home/user/kukicha/stdlib/sort/sort_test.kuki:69
			test.AssertEqual(t, sorted[1], "kiwi")
		})
	}
}

//line /home/user/kukicha/stdlib/sort/sort_test.kuki:73
type ReverseCase struct {
	name string
}

//line /home/user/kukicha/stdlib/sort/sort_test.kuki:76
func TestReverse(t *testing.T) {
//line /home/user/kukicha/stdlib/sort/sort_test.kuki:77
	cases := []ReverseCase{ReverseCase{name: "reverse ints"}}
//line /home/user/kukicha/stdlib/sort/sort_test.kuki:79
	for _, tc := range cases {
//line /home/user/kukicha/stdlib/sort/sort_test.kuki:80
		t.Run(tc.name, func(t *testing.T) {
//line /home/user/kukicha/stdlib/sort/sort_test.kuki:81
			nums := []int{1, 3, 2}
//line /home/user/kukicha/stdlib/sort/sort_test.kuki:82
			sorted := sort.Reverse(nums, func(a int, b int) bool { return (a < b) })
//line /home/user/kukicha/stdlib/sort/sort_test.kuki:83
			test.AssertEqual(t, sorted[0], 3)
		})
	}
}
