// Generated by Kukicha v0.0.16 (requires Go 1.26+)

package fetch

import (
	"bytes"
	"encoding/base64"
	"errors"
	"fmt"
	"github.com/duber000/kukicha/stdlib/json"
	"github.com/duber000/kukicha/stdlib/netguard"
	"github.com/duber000/kukicha/stdlib/retry"
	"github.com/duber000/kukicha/stdlib/sandbox"
	kukistring "github.com/duber000/kukicha/stdlib/string"
	"io"
	"net/http"
	"net/http/cookiejar"
	"net/url"
	"time"
)

//line /home/user/kukicha/stdlib/fetch/fetch.kuki:30
type Request struct {
	url              string
	headers          map[string]string
	timeoutNs        int64
	method           string
	body             any
	transport        *http.Transport
	retryMaxAttempts int
	retryDelayMs     int
	maxBodySize      int64
}

//line /home/user/kukicha/stdlib/fetch/fetch.kuki:45
func New(url string) Request {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:46
	req := Request{}
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:47
	req.url = url
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:48
	req.headers = make(map[string]string)
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:49
	req.timeoutNs = 30000000000
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:50
	req.method = "GET"
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:51
	req.body = nil
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:52
	req.retryMaxAttempts = 0
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:53
	req.retryDelayMs = 0
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:54
	return req
}

//line /home/user/kukicha/stdlib/fetch/fetch.kuki:58
func Header(req Request, name string, value string) Request {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:59
	req.headers[name] = value
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:60
	return req
}

//line /home/user/kukicha/stdlib/fetch/fetch.kuki:65
func Timeout(req Request, durationNs int64) Request {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:66
	req.timeoutNs = durationNs
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:67
	return req
}

//line /home/user/kukicha/stdlib/fetch/fetch.kuki:71
func Method(req Request, method string) Request {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:72
	req.method = method
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:73
	return req
}

//line /home/user/kukicha/stdlib/fetch/fetch.kuki:78
func Body(req Request, data any) Request {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:79
	req.body = data
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:80
	return req
}

//line /home/user/kukicha/stdlib/fetch/fetch.kuki:85
func Transport(req Request, t *http.Transport) Request {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:86
	req.transport = t
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:87
	return req
}

//line /home/user/kukicha/stdlib/fetch/fetch.kuki:92
func MaxBodySize(req Request, limit int64) Request {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:93
	req.maxBodySize = limit
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:94
	return req
}

//line /home/user/kukicha/stdlib/fetch/fetch.kuki:99
func Retry(req Request, maxAttempts int, delayMs int) Request {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:100
	req.retryMaxAttempts = maxAttempts
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:101
	if delayMs <= 0 {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:102
		req.retryDelayMs = 1000
	} else {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:104
		req.retryDelayMs = delayMs
	}
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:105
	return req
}

//line /home/user/kukicha/stdlib/fetch/fetch.kuki:108
func doOnce(req Request) (*http.Response, error) {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:109
	client := http.Client{}
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:110
	if req.transport != nil {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:111
		client.Transport = req.transport
	}
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:112
	client.Timeout = time.Duration(req.timeoutNs)
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:115
	var bodyData any
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:116
	if req.body != nil {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:118
		switch bodyStr := req.body.(type) {
		case string:
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:120
			bodyData = []byte(bodyStr)
		default:
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:123
			var err_1 error
			bodyData, err_1 = json.Marshal(req.body)
			if err_1 != nil {
				return nil, err_1
			}
		}
	}
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:125
	httpReq, err_2 := createHTTPRequest(req.method, req.url, bodyData)
	if err_2 != nil {
		return nil, err_2
	}
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:128
	for name, value := range req.headers {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:129
		httpReq.Header.Set(name, value)
	}
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:132
	if req.body != nil {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:133
		contentType := httpReq.Header.Get("Content-Type")
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:134
		if contentType == "" {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:135
			httpReq.Header.Set("Content-Type", "application/json")
		}
	}
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:137
	resp, err_3 := client.Do(httpReq)
	if err_3 != nil {
		return nil, err_3
	}
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:138
	if req.maxBodySize > 0 {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:139
		resp.Body = io.NopCloser(io.LimitReader(resp.Body, req.maxBodySize))
	}
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:140
	return resp, nil
}

//line /home/user/kukicha/stdlib/fetch/fetch.kuki:145
func Do(req Request) (*http.Response, error) {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:146
	if req.retryMaxAttempts <= 1 {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:147
		return doOnce(req)
	}
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:149
	delayMs := req.retryDelayMs
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:150
	if delayMs <= 0 {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:151
		delayMs = 1000
	}
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:152
	cfg := retry.Config{MaxAttempts: req.retryMaxAttempts, InitialDelay: delayMs, Strategy: 1}
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:154
	lastErr := errors.New("no attempts made")
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:155
	for attempt := range cfg.MaxAttempts {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:156
		resp, err := doOnce(req)
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:157
		if err == nil {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:159
			if (resp.StatusCode != 429) && (resp.StatusCode != 503) {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:160
				return resp, nil
			}
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:162
			resp.Body.Close()
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:163
			lastErr = errors.New(fmt.Sprintf("request failed: status %v", resp.StatusCode))
		} else {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:166
			lastErr = err
		}
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:167
		retry.Sleep(cfg, attempt)
	}
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:169
	return nil, lastErr
}

//line /home/user/kukicha/stdlib/fetch/fetch.kuki:172
func createHTTPRequest(method string, url string, bodyData any) (*http.Request, error) {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:173
	if bodyData != nil {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:174
		bodyBytes := bodyData.([]byte)
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:175
		req, err := http.NewRequest(method, url, bytes.NewReader(bodyBytes))
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:176
		return req, err
	}
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:177
	req, err := http.NewRequest(method, url, nil)
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:178
	return req, err
}

//line /home/user/kukicha/stdlib/fetch/fetch.kuki:184
func Get(url string) (*http.Response, error) {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:185
	resp, err_5 := Do(New(url))
	if err_5 != nil {
		return nil, err_5
	}
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:188
	return resp, nil
}

//line /home/user/kukicha/stdlib/fetch/fetch.kuki:194
func SafeGet(url string) (*http.Response, error) {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:195
	guard := netguard.NewSSRFGuard()
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:196
	transport := netguard.HTTPTransport(guard)
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:197
	resp, err_7 := Do(Transport(New(url), transport))
	if err_7 != nil {
		return nil, err_7
	}
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:201
	return resp, nil
}

//line /home/user/kukicha/stdlib/fetch/fetch.kuki:208
func Post(data any, url string) (*http.Response, error) {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:209
	resp, err_9 := Do(Body(Method(New(url), "POST"), data))
	if err_9 != nil {
		return nil, err_9
	}
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:214
	return resp, nil
}

//line /home/user/kukicha/stdlib/fetch/fetch.kuki:219
func CheckStatus(resp *http.Response) (*http.Response, error) {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:220
	if resp.StatusCode >= 400 {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:221
		return nil, errors.New(fmt.Sprintf("request failed: %v", resp.Status))
	}
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:222
	return resp, nil
}

//line /home/user/kukicha/stdlib/fetch/fetch.kuki:226
func Text(resp *http.Response) (string, error) {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:227
	defer resp.Body.Close()
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:228
	bodyBytes, err_10 := io.ReadAll(resp.Body)
	if err_10 != nil {
		return "", err_10
	}
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:229
	return string(bodyBytes), nil
}

//line /home/user/kukicha/stdlib/fetch/fetch.kuki:234
func Bytes(resp *http.Response) ([]byte, error) {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:235
	defer resp.Body.Close()
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:236
	bodyBytes, err_11 := io.ReadAll(resp.Body)
	if err_11 != nil {
		return []byte{}, err_11
	}
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:237
	return bodyBytes, nil
}

//line /home/user/kukicha/stdlib/fetch/fetch.kuki:242
func Json[T any](resp *http.Response, sample T) (T, error) {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:243
	defer resp.Body.Close()
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:244
	data := sample
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:245
	err_12 := json.UnmarshalRead(resp.Body, &data)
	if err_12 != nil {
		err_12 = fmt.Errorf("failed to decode response json: %w", err_12)
		return *new(T), err_12
	}
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:246
	return data, nil
}

//line /home/user/kukicha/stdlib/fetch/fetch.kuki:253
func Decode(resp *http.Response, target any) error {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:254
	defer resp.Body.Close()
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:255
	return json.UnmarshalRead(resp.Body, target)
}

//line /home/user/kukicha/stdlib/fetch/fetch.kuki:259
func PathEscape(value string) string {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:260
	return url.PathEscape(value)
}

//line /home/user/kukicha/stdlib/fetch/fetch.kuki:264
func QueryEscape(value string) string {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:265
	return url.QueryEscape(value)
}

//line /home/user/kukicha/stdlib/fetch/fetch.kuki:271
func URLTemplate(tmpl string, params map[string]string) (string, error) {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:272
	result := tmpl
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:273
	for key, value := range params {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:274
		placeholder := fmt.Sprintf("{%v}", key)
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:275
		result = kukistring.ReplaceAll(result, placeholder, url.PathEscape(value))
	}
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:277
	if kukistring.Contains(result, "{") || kukistring.Contains(result, "}") {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:278
		return "", errors.New(fmt.Sprintf("unresolved URL template placeholders: %v", result))
	}
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:279
	return result, nil
}

//line /home/user/kukicha/stdlib/fetch/fetch.kuki:284
func URLWithQuery(baseURL string, params map[string]string) (string, error) {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:285
	parsed, err_13 := url.Parse(baseURL)
	if err_13 != nil {
		return "", errors.New(fmt.Sprintf("%v", err_13))
	}
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:286
	query := parsed.Query()
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:287
	for key, value := range params {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:288
		query.Set(key, value)
	}
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:289
	parsed.RawQuery = query.Encode()
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:290
	return parsed.String(), nil
}

//line /home/user/kukicha/stdlib/fetch/fetch.kuki:298
func BearerAuth(req Request, token string) Request {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:299
	return Header(req, "Authorization", fmt.Sprintf("Bearer %v", token))
}

//line /home/user/kukicha/stdlib/fetch/fetch.kuki:303
func BasicAuth(req Request, username string, password string) Request {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:304
	credentials := fmt.Sprintf("%v:%v", username, password)
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:305
	encoded := base64.StdEncoding.EncodeToString([]byte(credentials))
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:306
	return Header(req, "Authorization", fmt.Sprintf("Basic %v", encoded))
}

//line /home/user/kukicha/stdlib/fetch/fetch.kuki:315
func FormData(req Request, data map[string]string) Request {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:316
	values := url.Values{}
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:317
	for key, value := range data {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:318
		values.Set(key, value)
	}
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:319
	req.body = values.Encode()
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:320
	req = Header(req, "Content-Type", "application/x-www-form-urlencoded")
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:321
	return req
}

//line /home/user/kukicha/stdlib/fetch/fetch.kuki:328
type Session struct {
	client    http.Client
	headers   map[string]string
	timeoutNs int64
}

//line /home/user/kukicha/stdlib/fetch/fetch.kuki:335
func NewSession() Session {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:336
	jar, _ := cookiejar.New(nil)
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:337
	client := http.Client{Jar: jar}
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:338
	s := Session{}
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:339
	s.client = client
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:340
	s.headers = make(map[string]string)
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:341
	s.timeoutNs = 30000000000
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:342
	return s
}

//line /home/user/kukicha/stdlib/fetch/fetch.kuki:346
func SessionHeader(s Session, name string, value string) Session {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:347
	s.headers[name] = value
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:348
	return s
}

//line /home/user/kukicha/stdlib/fetch/fetch.kuki:352
func SessionTimeout(s Session, durationNs int64) Session {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:353
	s.timeoutNs = durationNs
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:354
	return s
}

//line /home/user/kukicha/stdlib/fetch/fetch.kuki:359
func SessionDo(s Session, req Request) (*http.Response, error) {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:361
	for name, value := range s.headers {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:362
		_, exists := req.headers[name]
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:363
		if !exists {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:364
			req.headers[name] = value
		}
	}
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:367
	if req.timeoutNs == 30000000000 {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:368
		req.timeoutNs = s.timeoutNs
	}
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:371
	s.client.Timeout = time.Duration(req.timeoutNs)
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:374
	var bodyData any
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:375
	if req.body != nil {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:377
		switch bodyStr := req.body.(type) {
		case string:
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:379
			bodyData = []byte(bodyStr)
		default:
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:381
			var err_14 error
			bodyData, err_14 = json.Marshal(req.body)
			if err_14 != nil {
				return nil, err_14
			}
		}
	}
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:383
	httpReq, err_15 := createHTTPRequest(req.method, req.url, bodyData)
	if err_15 != nil {
		return nil, err_15
	}
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:385
	for name, value := range req.headers {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:386
		httpReq.Header.Set(name, value)
	}
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:389
	if req.body != nil {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:390
		contentType := httpReq.Header.Get("Content-Type")
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:391
		if contentType == "" {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:392
			httpReq.Header.Set("Content-Type", "application/json")
		}
	}
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:394
	return s.client.Do(httpReq)
}

//line /home/user/kukicha/stdlib/fetch/fetch.kuki:398
func SessionGet(s Session, url string) (*http.Response, error) {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:399
	req := New(url)
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:400
	return SessionDo(s, req)
}

//line /home/user/kukicha/stdlib/fetch/fetch.kuki:404
func SessionPost(s Session, data any, url string) (*http.Response, error) {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:405
	req := New(url)
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:406
	req = Method(req, "POST")
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:407
	req.body = data
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:408
	return SessionDo(s, req)
}

//line /home/user/kukicha/stdlib/fetch/fetch.kuki:413
func SessionTransport(s Session, t *http.Transport) Session {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:414
	s.client.Transport = t
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:415
	return s
}

//line /home/user/kukicha/stdlib/fetch/fetch.kuki:423
func DownloadTo(resp *http.Response, box sandbox.Root, path string) error {
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:424
	defer resp.Body.Close()
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:425
	bodyBytes, err_16 := io.ReadAll(resp.Body)
	if err_16 != nil {
		return err_16
	}
//line /home/user/kukicha/stdlib/fetch/fetch.kuki:426
	return sandbox.WriteString(box, string(bodyBytes), path)
}
