// Generated by Kukicha (requires Go 1.26+)

package fetch

import (
	"bytes"
	"encoding/base64"
	"errors"
	"fmt"
	"github.com/kukichalang/kukicha/stdlib/json"
	"github.com/kukichalang/kukicha/stdlib/netguard"
	"github.com/kukichalang/kukicha/stdlib/retry"
	"github.com/kukichalang/kukicha/stdlib/sandbox"
	kukistring "github.com/kukichalang/kukicha/stdlib/string"
	"io"
	"net/http"
	"net/http/cookiejar"
	"net/url"
	"time"
)

//line stdlib/fetch/fetch.kuki:31
type limitReadCloser struct {
	r io.Reader
	c io.Closer
}

//line stdlib/fetch/fetch.kuki:35
func (b *limitReadCloser) Read(p []byte) (int, error) {
//line stdlib/fetch/fetch.kuki:36
	return b.r.Read(p)
}

//line stdlib/fetch/fetch.kuki:38
func (b *limitReadCloser) Close() error {
//line stdlib/fetch/fetch.kuki:39
	return b.c.Close()
}

//line stdlib/fetch/fetch.kuki:42
type Request struct {
	url              string
	headers          map[string]string
	timeoutNs        int64
	method           string
	body             any
	transport        *http.Transport
	retryMaxAttempts int
	retryDelayMs     int
	maxBodySize      int64
}

//line stdlib/fetch/fetch.kuki:57
func New(url string) Request {
//line stdlib/fetch/fetch.kuki:58
	req := Request{}
//line stdlib/fetch/fetch.kuki:59
	req.url = url
//line stdlib/fetch/fetch.kuki:60
	req.headers = make(map[string]string)
//line stdlib/fetch/fetch.kuki:61
	req.timeoutNs = 30000000000
//line stdlib/fetch/fetch.kuki:62
	req.method = "GET"
//line stdlib/fetch/fetch.kuki:63
	req.body = nil
//line stdlib/fetch/fetch.kuki:64
	req.retryMaxAttempts = 0
//line stdlib/fetch/fetch.kuki:65
	req.retryDelayMs = 0
//line stdlib/fetch/fetch.kuki:66
	return req
}

//line stdlib/fetch/fetch.kuki:70
func Header(req Request, name string, value string) Request {
//line stdlib/fetch/fetch.kuki:71
	req.headers[name] = value
//line stdlib/fetch/fetch.kuki:72
	return req
}

//line stdlib/fetch/fetch.kuki:77
func Timeout(req Request, durationNs int64) Request {
//line stdlib/fetch/fetch.kuki:78
	req.timeoutNs = durationNs
//line stdlib/fetch/fetch.kuki:79
	return req
}

//line stdlib/fetch/fetch.kuki:83
func Method(req Request, method string) Request {
//line stdlib/fetch/fetch.kuki:84
	req.method = method
//line stdlib/fetch/fetch.kuki:85
	return req
}

//line stdlib/fetch/fetch.kuki:90
func Body(req Request, data any) Request {
//line stdlib/fetch/fetch.kuki:91
	req.body = data
//line stdlib/fetch/fetch.kuki:92
	return req
}

//line stdlib/fetch/fetch.kuki:97
func Transport(req Request, t *http.Transport) Request {
//line stdlib/fetch/fetch.kuki:98
	req.transport = t
//line stdlib/fetch/fetch.kuki:99
	return req
}

//line stdlib/fetch/fetch.kuki:104
func MaxBodySize(req Request, limit int64) Request {
//line stdlib/fetch/fetch.kuki:105
	req.maxBodySize = limit
//line stdlib/fetch/fetch.kuki:106
	return req
}

//line stdlib/fetch/fetch.kuki:111
func Retry(req Request, maxAttempts int, delayMs int) Request {
//line stdlib/fetch/fetch.kuki:112
	req.retryMaxAttempts = maxAttempts
//line stdlib/fetch/fetch.kuki:113
	if delayMs <= 0 {
//line stdlib/fetch/fetch.kuki:114
		req.retryDelayMs = 1000
	} else {
//line stdlib/fetch/fetch.kuki:116
		req.retryDelayMs = delayMs
	}
//line stdlib/fetch/fetch.kuki:117
	return req
}

//line stdlib/fetch/fetch.kuki:120
func doOnce(req Request) (*http.Response, error) {
//line stdlib/fetch/fetch.kuki:121
	client := http.Client{}
//line stdlib/fetch/fetch.kuki:122
	if req.transport != nil {
//line stdlib/fetch/fetch.kuki:123
		client.Transport = req.transport
	}
//line stdlib/fetch/fetch.kuki:124
	client.Timeout = time.Duration(req.timeoutNs)
//line stdlib/fetch/fetch.kuki:127
	var bodyData any
//line stdlib/fetch/fetch.kuki:128
	if req.body != nil {
//line stdlib/fetch/fetch.kuki:130
		switch bodyStr := req.body.(type) {
		case string:
//line stdlib/fetch/fetch.kuki:132
			bodyData = []byte(bodyStr)
		default:
//line stdlib/fetch/fetch.kuki:134
			var err_1 error
			bodyData, err_1 = json.Marshal(req.body)
//line stdlib/fetch/fetch.kuki:134
			if err_1 != nil {
//line stdlib/fetch/fetch.kuki:134
				return nil, err_1
			}
		}
	}
//line stdlib/fetch/fetch.kuki:138
	httpReq, err_2 := createHTTPRequest(req.method, req.url, bodyData)
//line stdlib/fetch/fetch.kuki:138
	if err_2 != nil {
//line stdlib/fetch/fetch.kuki:138
		return nil, err_2
	}
//line stdlib/fetch/fetch.kuki:141
	for name, value := range req.headers {
//line stdlib/fetch/fetch.kuki:142
		httpReq.Header.Set(name, value)
	}
//line stdlib/fetch/fetch.kuki:145
	if req.body != nil {
//line stdlib/fetch/fetch.kuki:146
		contentType := httpReq.Header.Get("Content-Type")
//line stdlib/fetch/fetch.kuki:147
		if contentType == "" {
//line stdlib/fetch/fetch.kuki:148
			httpReq.Header.Set("Content-Type", "application/json")
		}
	}
//line stdlib/fetch/fetch.kuki:150
	resp, err_3 := client.Do(httpReq)
//line stdlib/fetch/fetch.kuki:150
	if err_3 != nil {
//line stdlib/fetch/fetch.kuki:150
		return nil, err_3
	}
//line stdlib/fetch/fetch.kuki:151
	if req.maxBodySize > 0 {
//line stdlib/fetch/fetch.kuki:152
		resp.Body = &limitReadCloser{r: io.LimitReader(resp.Body, req.maxBodySize), c: resp.Body}
	}
//line stdlib/fetch/fetch.kuki:153
	return resp, nil
}

//line stdlib/fetch/fetch.kuki:158
func Do(req Request) (*http.Response, error) {
//line stdlib/fetch/fetch.kuki:159
	if req.retryMaxAttempts <= 1 {
//line stdlib/fetch/fetch.kuki:160
		return doOnce(req)
	}
//line stdlib/fetch/fetch.kuki:162
	delayMs := req.retryDelayMs
//line stdlib/fetch/fetch.kuki:163
	if delayMs <= 0 {
//line stdlib/fetch/fetch.kuki:164
		delayMs = 1000
	}
//line stdlib/fetch/fetch.kuki:165
	cfg := retry.Config{MaxAttempts: req.retryMaxAttempts, InitialDelay: delayMs, Strategy: 1}
//line stdlib/fetch/fetch.kuki:167
	lastErr := errors.New("no attempts made")
//line stdlib/fetch/fetch.kuki:168
	for attempt := range cfg.MaxAttempts {
//line stdlib/fetch/fetch.kuki:169
		resp, err := doOnce(req)
//line stdlib/fetch/fetch.kuki:170
		if err == nil {
//line stdlib/fetch/fetch.kuki:172
			if (resp.StatusCode != 429) && (resp.StatusCode != 503) {
//line stdlib/fetch/fetch.kuki:173
				return resp, nil
			}
//line stdlib/fetch/fetch.kuki:175
			resp.Body.Close()
//line stdlib/fetch/fetch.kuki:176
			lastErr = fmt.Errorf("request failed: status %v", resp.StatusCode)
		} else {
//line stdlib/fetch/fetch.kuki:179
			lastErr = err
		}
//line stdlib/fetch/fetch.kuki:180
		retry.Sleep(cfg, attempt)
	}
//line stdlib/fetch/fetch.kuki:182
	return nil, lastErr
}

//line stdlib/fetch/fetch.kuki:185
func createHTTPRequest(method string, url string, bodyData any) (*http.Request, error) {
//line stdlib/fetch/fetch.kuki:186
	if bodyData != nil {
//line stdlib/fetch/fetch.kuki:187
		bodyBytes := bodyData.([]byte)
//line stdlib/fetch/fetch.kuki:188
		req, err := http.NewRequest(method, url, bytes.NewReader(bodyBytes))
//line stdlib/fetch/fetch.kuki:189
		return req, err
	}
//line stdlib/fetch/fetch.kuki:190
	req, err := http.NewRequest(method, url, nil)
//line stdlib/fetch/fetch.kuki:191
	return req, err
}

//line stdlib/fetch/fetch.kuki:197
func Get(url string) (*http.Response, error) {
//line stdlib/fetch/fetch.kuki:198
	// pipe step 1: Do(...)
//line stdlib/fetch/fetch.kuki:198
	resp, err_5 := Do(New(url))
//line stdlib/fetch/fetch.kuki:198
	if err_5 != nil {
//line stdlib/fetch/fetch.kuki:198
		return nil, err_5
	}
//line stdlib/fetch/fetch.kuki:200
	return resp, nil
}

//line stdlib/fetch/fetch.kuki:206
func SafeGet(url string) (*http.Response, error) {
//line stdlib/fetch/fetch.kuki:207
	guard := netguard.NewSSRFGuard()
//line stdlib/fetch/fetch.kuki:208
	transport := netguard.HTTPTransport(guard)
//line stdlib/fetch/fetch.kuki:209
	// pipe step 1: Do(...)
//line stdlib/fetch/fetch.kuki:209
	resp, err_7 := Do(Transport(New(url), transport))
//line stdlib/fetch/fetch.kuki:209
	if err_7 != nil {
//line stdlib/fetch/fetch.kuki:209
		return nil, err_7
	}
//line stdlib/fetch/fetch.kuki:211
	return resp, nil
}

//line stdlib/fetch/fetch.kuki:218
func Post(data any, url string) (*http.Response, error) {
//line stdlib/fetch/fetch.kuki:219
	// pipe step 1: Do(...)
//line stdlib/fetch/fetch.kuki:219
	resp, err_9 := Do(Body(Method(New(url), "POST"), data))
//line stdlib/fetch/fetch.kuki:219
	if err_9 != nil {
//line stdlib/fetch/fetch.kuki:219
		return nil, err_9
	}
//line stdlib/fetch/fetch.kuki:221
	return resp, nil
}

//line stdlib/fetch/fetch.kuki:226
func CheckStatus(resp *http.Response) (*http.Response, error) {
//line stdlib/fetch/fetch.kuki:227
	if resp.StatusCode >= 400 {
//line stdlib/fetch/fetch.kuki:228
		return nil, fmt.Errorf("request failed: %v", resp.Status)
	}
//line stdlib/fetch/fetch.kuki:229
	return resp, nil
}

//line stdlib/fetch/fetch.kuki:233
func Text(resp *http.Response) (string, error) {
//line stdlib/fetch/fetch.kuki:234
	defer resp.Body.Close()
//line stdlib/fetch/fetch.kuki:235
	bodyBytes, err_10 := io.ReadAll(resp.Body)
//line stdlib/fetch/fetch.kuki:235
	if err_10 != nil {
//line stdlib/fetch/fetch.kuki:235
		return "", err_10
	}
//line stdlib/fetch/fetch.kuki:236
	return string(bodyBytes), nil
}

//line stdlib/fetch/fetch.kuki:241
func Bytes(resp *http.Response) ([]byte, error) {
//line stdlib/fetch/fetch.kuki:242
	defer resp.Body.Close()
//line stdlib/fetch/fetch.kuki:243
	bodyBytes, err_11 := io.ReadAll(resp.Body)
//line stdlib/fetch/fetch.kuki:243
	if err_11 != nil {
//line stdlib/fetch/fetch.kuki:243
		return []byte{}, err_11
	}
//line stdlib/fetch/fetch.kuki:244
	return bodyBytes, nil
}

//line stdlib/fetch/fetch.kuki:249
func Json[T any](resp *http.Response, sample T) (T, error) {
//line stdlib/fetch/fetch.kuki:250
	defer resp.Body.Close()
//line stdlib/fetch/fetch.kuki:251
	data := sample
//line stdlib/fetch/fetch.kuki:252
//line stdlib/fetch/fetch.kuki:252
	err_12 := json.UnmarshalRead(resp.Body, &data)
//line stdlib/fetch/fetch.kuki:252
	if err_12 != nil {
//line stdlib/fetch/fetch.kuki:252
		err_12 = fmt.Errorf("failed to decode response json: %w", err_12)
		var _zero0 T
//line stdlib/fetch/fetch.kuki:252
		return _zero0, err_12
	}
//line stdlib/fetch/fetch.kuki:253
	return data, nil
}

//line stdlib/fetch/fetch.kuki:260
func Decode(resp *http.Response, target any) error {
//line stdlib/fetch/fetch.kuki:261
	defer resp.Body.Close()
//line stdlib/fetch/fetch.kuki:262
	return json.UnmarshalRead(resp.Body, target)
}

//line stdlib/fetch/fetch.kuki:266
func PathEscape(value string) string {
//line stdlib/fetch/fetch.kuki:267
	return url.PathEscape(value)
}

//line stdlib/fetch/fetch.kuki:271
func QueryEscape(value string) string {
//line stdlib/fetch/fetch.kuki:272
	return url.QueryEscape(value)
}

//line stdlib/fetch/fetch.kuki:278
func URLTemplate(tmpl string, params map[string]string) (string, error) {
//line stdlib/fetch/fetch.kuki:279
	result := tmpl
//line stdlib/fetch/fetch.kuki:280
	for key, value := range params {
//line stdlib/fetch/fetch.kuki:281
		placeholder := fmt.Sprintf("{%v}", key)
//line stdlib/fetch/fetch.kuki:282
		result = kukistring.ReplaceAll(result, placeholder, url.PathEscape(value))
	}
//line stdlib/fetch/fetch.kuki:284
	if kukistring.Contains(result, "{") || kukistring.Contains(result, "}") {
//line stdlib/fetch/fetch.kuki:285
		return "", fmt.Errorf("unresolved URL template placeholders: %v", result)
	}
//line stdlib/fetch/fetch.kuki:286
	return result, nil
}

//line stdlib/fetch/fetch.kuki:291
func URLWithQuery(baseURL string, params map[string]string) (string, error) {
//line stdlib/fetch/fetch.kuki:292
	parsed, err_13 := url.Parse(baseURL)
//line stdlib/fetch/fetch.kuki:292
	if err_13 != nil {
//line stdlib/fetch/fetch.kuki:292
		return "", fmt.Errorf("%v", err_13)
	}
//line stdlib/fetch/fetch.kuki:293
	query := parsed.Query()
//line stdlib/fetch/fetch.kuki:294
	for key, value := range params {
//line stdlib/fetch/fetch.kuki:295
		query.Set(key, value)
	}
//line stdlib/fetch/fetch.kuki:296
	parsed.RawQuery = query.Encode()
//line stdlib/fetch/fetch.kuki:297
	return parsed.String(), nil
}

//line stdlib/fetch/fetch.kuki:305
func BearerAuth(req Request, token string) Request {
//line stdlib/fetch/fetch.kuki:306
	return Header(req, "Authorization", fmt.Sprintf("Bearer %v", token))
}

//line stdlib/fetch/fetch.kuki:310
func BasicAuth(req Request, username string, password string) Request {
//line stdlib/fetch/fetch.kuki:311
	credentials := fmt.Sprintf("%v:%v", username, password)
//line stdlib/fetch/fetch.kuki:312
	encoded := base64.StdEncoding.EncodeToString([]byte(credentials))
//line stdlib/fetch/fetch.kuki:313
	return Header(req, "Authorization", fmt.Sprintf("Basic %v", encoded))
}

//line stdlib/fetch/fetch.kuki:322
func FormData(req Request, data map[string]string) Request {
//line stdlib/fetch/fetch.kuki:323
	values := url.Values{}
//line stdlib/fetch/fetch.kuki:324
	for key, value := range data {
//line stdlib/fetch/fetch.kuki:325
		values.Set(key, value)
	}
//line stdlib/fetch/fetch.kuki:326
	req.body = values.Encode()
//line stdlib/fetch/fetch.kuki:327
	req = Header(req, "Content-Type", "application/x-www-form-urlencoded")
//line stdlib/fetch/fetch.kuki:328
	return req
}

//line stdlib/fetch/fetch.kuki:335
type Session struct {
	client    http.Client
	headers   map[string]string
	timeoutNs int64
}

//line stdlib/fetch/fetch.kuki:342
func NewSession() Session {
//line stdlib/fetch/fetch.kuki:343
	jar, _ := cookiejar.New(nil)
//line stdlib/fetch/fetch.kuki:344
	client := http.Client{Jar: jar}
//line stdlib/fetch/fetch.kuki:345
	s := Session{}
//line stdlib/fetch/fetch.kuki:346
	s.client = client
//line stdlib/fetch/fetch.kuki:347
	s.headers = make(map[string]string)
//line stdlib/fetch/fetch.kuki:348
	s.timeoutNs = 30000000000
//line stdlib/fetch/fetch.kuki:349
	return s
}

//line stdlib/fetch/fetch.kuki:353
func SessionHeader(s Session, name string, value string) Session {
//line stdlib/fetch/fetch.kuki:354
	s.headers[name] = value
//line stdlib/fetch/fetch.kuki:355
	return s
}

//line stdlib/fetch/fetch.kuki:359
func SessionTimeout(s Session, durationNs int64) Session {
//line stdlib/fetch/fetch.kuki:360
	s.timeoutNs = durationNs
//line stdlib/fetch/fetch.kuki:361
	return s
}

//line stdlib/fetch/fetch.kuki:366
func SessionDo(s Session, req Request) (*http.Response, error) {
//line stdlib/fetch/fetch.kuki:368
	for name, value := range s.headers {
//line stdlib/fetch/fetch.kuki:369
		_, exists := req.headers[name]
//line stdlib/fetch/fetch.kuki:370
		if !exists {
//line stdlib/fetch/fetch.kuki:371
			req.headers[name] = value
		}
	}
//line stdlib/fetch/fetch.kuki:374
	if req.timeoutNs == 30000000000 {
//line stdlib/fetch/fetch.kuki:375
		req.timeoutNs = s.timeoutNs
	}
//line stdlib/fetch/fetch.kuki:378
	s.client.Timeout = time.Duration(req.timeoutNs)
//line stdlib/fetch/fetch.kuki:381
	var bodyData any
//line stdlib/fetch/fetch.kuki:382
	if req.body != nil {
//line stdlib/fetch/fetch.kuki:384
		switch bodyStr := req.body.(type) {
		case string:
//line stdlib/fetch/fetch.kuki:386
			bodyData = []byte(bodyStr)
		default:
//line stdlib/fetch/fetch.kuki:388
			var err_14 error
			bodyData, err_14 = json.Marshal(req.body)
//line stdlib/fetch/fetch.kuki:388
			if err_14 != nil {
//line stdlib/fetch/fetch.kuki:388
				return nil, err_14
			}
		}
	}
//line stdlib/fetch/fetch.kuki:390
	httpReq, err_15 := createHTTPRequest(req.method, req.url, bodyData)
//line stdlib/fetch/fetch.kuki:390
	if err_15 != nil {
//line stdlib/fetch/fetch.kuki:390
		return nil, err_15
	}
//line stdlib/fetch/fetch.kuki:392
	for name, value := range req.headers {
//line stdlib/fetch/fetch.kuki:393
		httpReq.Header.Set(name, value)
	}
//line stdlib/fetch/fetch.kuki:396
	if req.body != nil {
//line stdlib/fetch/fetch.kuki:397
		contentType := httpReq.Header.Get("Content-Type")
//line stdlib/fetch/fetch.kuki:398
		if contentType == "" {
//line stdlib/fetch/fetch.kuki:399
			httpReq.Header.Set("Content-Type", "application/json")
		}
	}
//line stdlib/fetch/fetch.kuki:401
	return s.client.Do(httpReq)
}

//line stdlib/fetch/fetch.kuki:405
func SessionGet(s Session, url string) (*http.Response, error) {
//line stdlib/fetch/fetch.kuki:406
	req := New(url)
//line stdlib/fetch/fetch.kuki:407
	return SessionDo(s, req)
}

//line stdlib/fetch/fetch.kuki:411
func SessionPost(s Session, data any, url string) (*http.Response, error) {
//line stdlib/fetch/fetch.kuki:412
	req := New(url)
//line stdlib/fetch/fetch.kuki:413
	req = Method(req, "POST")
//line stdlib/fetch/fetch.kuki:414
	req.body = data
//line stdlib/fetch/fetch.kuki:415
	return SessionDo(s, req)
}

//line stdlib/fetch/fetch.kuki:420
func SessionTransport(s Session, t *http.Transport) Session {
//line stdlib/fetch/fetch.kuki:421
	s.client.Transport = t
//line stdlib/fetch/fetch.kuki:422
	return s
}

//line stdlib/fetch/fetch.kuki:430
func DownloadTo(resp *http.Response, box sandbox.Root, path string) error {
//line stdlib/fetch/fetch.kuki:431
	defer resp.Body.Close()
//line stdlib/fetch/fetch.kuki:432
	bodyBytes, err_16 := io.ReadAll(resp.Body)
//line stdlib/fetch/fetch.kuki:432
	if err_16 != nil {
//line stdlib/fetch/fetch.kuki:432
		return err_16
	}
//line stdlib/fetch/fetch.kuki:433
	return sandbox.WriteString(box, string(bodyBytes), path)
}
